export const MISSION_STATEMENT =
  "We are equity-focused and equality and access driven. We are problem solvers using collaborative accountability and transparency that is data-led and intentional — to make good programs better and leave no one behind. The Collaborative Advocate Foundation transforms communities by listening first, measuring always, and building technology that reflects real feelings and real experiences. Our 15-service-platform ecosystem — powered by seven academic disciplines and our MAP-GAP framework — ensures that every person has a pathway: veterans transitioning to civilian life through M2C, individuals experiencing homelessness navigating stability through LifeBridge, immigrants accessing resources regardless of documentation status through Speech Bridge, formerly incarcerated individuals rebuilding through our reentry pipeline, and every community member who has been left behind by systems not designed for them.";

export const VISION_STATEMENT =
  "A nation where no one is invisible. Where every community — regardless of zip code, documentation status, housing situation, or history — has access to a holistic, comprehensive system that listens before it builds, measures what matters, holds itself accountable with transparency, and never stops improving. Where veterans have a real transition path, not just a thank-you. Where people experiencing homelessness are counted and served, not stepped over. Where immigrants can access resources in their language without fear. Where education is the number one protective factor and data tells the truth that county averages hide.";

export const VALUES = [
  { title: "Equity-Focused, Access-Driven", desc: "Not theoretical equity — tract-level data that exposes the neighborhoods county averages hide. We measure impact for everyone: homeless individuals, immigrants, veterans, formerly incarcerated, foster youth. No one is invisible in our data.", iconName: "Scale" as const },
  { title: "Collaborative Accountability", desc: "We don't work in silos. Every partner, every platform, every stakeholder shares the same data, the same goals, and the same transparency. When we say accountability, we mean to the community — not just the funder.", iconName: "Users" as const },
  { title: "Data-Led & Intentional", desc: "We don't guess. We measure. Then we act. Eight federal data sources, locked Census baselines, tract-level analysis. Our data tells the truth that county averages hide — because a 12% poverty rate means nothing when one neighborhood is at 40%.", iconName: "BarChart3" as const },
  { title: "Leave No One Behind", desc: "Veterans transitioning through M2C. Homeless individuals navigating stability through LifeBridge. Immigrants accessing resources in their language through Speech Bridge. Formerly incarcerated rebuilding through our reentry pipeline. Youth aging out of foster care. Everyone has a pathway.", iconName: "Heart" as const },
  { title: "Holistic & Comprehensive", desc: "24 coordinated platforms. One entry point. No dead ends. If one platform identifies a need, the entire ecosystem responds — coordinated, accountable, and transparent. We serve the whole person, not just the problem that got them in the door.", iconName: "Globe" as const },
  { title: "Make Good Programs Better", desc: "We don't compete with existing organizations — we give them infrastructure to amplify their impact. MAP-GAP continuous improvement means every program gets better in 30-day cycles, not annual reports. Implementation science ensures fidelity.", iconName: "Microscope" as const },
  { title: "Education as Protection", desc: "Education is the number one protective factor. Period. Our curriculum is culturally responsive, age-adaptive, and connects to real career pathways — because learning should reflect who you are and where you're going.", iconName: "GraduationCap" as const },
  { title: "Real Feelings, Real Data", desc: "Our approach is altruistic — built on real feelings and real experiences, then validated with data and change management. The Three Realities methodology ensures community voice drives every decision: what people live, what systems intend, where the gap creates harm.", iconName: "Brain" as const },
  { title: "Transparent Measurement", desc: "If we can't measure it transparently, we can't improve it. SALP indicators track fidelity in real time. SMART goals visible to every stakeholder. Our data doesn't just report outcomes — it makes programs better.", iconName: "BookOpen" as const },
] as const;

export const DISCIPLINES = [
  {
    id: "implementation-science",
    name: "Implementation Science",
    shortName: "Impl. Science",
    color: "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300",
    borderColor: "border-blue-300 dark:border-blue-700",
    icon: "Microscope" as const,
    desc: "Translates evidence-based practices into real-world community applications through CFIR, RE-AIM, and EPIS frameworks.",
    mapGapComponent: "Fidelity tracking across all platforms — ensuring programs are implemented as designed, not just deployed.",
    platforms: ["thriveup", "isss", "betterscience", "safereport", "sankofa", "lifebridge", "wholemind", "perfectly-different"],
  },
  {
    id: "criminal-justice",
    name: "Criminal Justice",
    shortName: "Criminal Justice",
    color: "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300",
    borderColor: "border-amber-300 dark:border-amber-700",
    icon: "Scale" as const,
    desc: "Designs reentry pathways, diversion programs, and restorative justice systems that address root causes of incarceration.",
    mapGapComponent: "Reentry pathway design — from risk assessment through community reintegration, employment, and sustained stability.",
    platforms: ["thriveup", "safereport", "lifebridge", "isss"],
  },
  {
    id: "hr-management",
    name: "HR Management",
    shortName: "HR Mgmt",
    color: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300",
    borderColor: "border-emerald-300 dark:border-emerald-700",
    icon: "Briefcase" as const,
    desc: "Builds competency models, workforce pipelines, and career pathways serving individuals from intake to placement to retention.",
    mapGapComponent: "Competency modeling and workforce pipelines — structured career progression from assessment through credentialing to employment.",
    platforms: ["thriveup", "mce", "m2c", "isss"],
  },
  {
    id: "io-psychology",
    name: "I-O Psychology",
    shortName: "I-O Psych",
    color: "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300",
    borderColor: "border-purple-300 dark:border-purple-700",
    icon: "Brain" as const,
    desc: "Powers engagement design, behavioral nudges, and motivation systems that keep stakeholders invested for sustained impact.",
    mapGapComponent: "Behavioral nudge architecture and engagement design — keeping participants, staff, and communities motivated through the entire program lifecycle.",
    platforms: ["thriveup", "isss", "mce", "wholemind", "perfectly-different", "sankofa"],
  },
  {
    id: "education",
    name: "Education",
    shortName: "Education",
    color: "bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-300",
    borderColor: "border-rose-300 dark:border-rose-700",
    icon: "GraduationCap" as const,
    desc: "Builds age-adaptive curricula, AI literacy pathways, and workforce readiness programs aligned with TEKS standards — ensuring learners see themselves in the content and develop real-world skills from K-12 through adult education.",
    mapGapComponent: "Curriculum design and learning outcome measurement — 60+ deep lessons across AI literacy, workforce readiness, and social-emotional learning with interactive activities and measurable competency tracking.",
    platforms: ["thriveup", "isss", "betterscience", "mce", "m2c"],
  },
  {
    id: "social-science",
    name: "Social Science",
    shortName: "Social Science",
    color: "bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300",
    borderColor: "border-teal-300 dark:border-teal-700",
    icon: "Users" as const,
    desc: "Applies community-based participatory research, social determinants of health analysis, and culturally responsive evaluation to help communities see themselves in data — and use that data to drive their own transformation.",
    mapGapComponent: "Community intelligence mapping and SDOH analysis — GIS-powered data integration from 8 federal sources enabling communities to identify gaps, measure progress, and advocate with evidence.",
    platforms: ["thriveup", "isss", "sankofa", "lifebridge", "wholemind", "perfectly-different", "safereport"],
  },
  {
    id: "healthcare",
    name: "Healthcare & Public Health",
    shortName: "Healthcare",
    color: "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300",
    borderColor: "border-red-300 dark:border-red-700",
    icon: "Heart" as const,
    desc: "Integrates whole-person health, maternal and infant care, community health worker deployment, substance abuse prevention, and health equity analysis — closing the gap between clinical systems and the communities they should serve.",
    mapGapComponent: "Health equity measurement and CHW coordination — tracking maternal outcomes, behavioral health access, chronic disease management, and social determinants across the full care continuum from prevention through recovery.",
    platforms: ["sankofa", "whole-person-health", "lifebridge", "wholemind", "emergency-mgmt", "sankofa-feminine-health", "sankofa-maternal-health", "sankofa-mens-health"],
  },
] as const;

export const MAPGAP_CYCLE = [
  {
    step: 1,
    title: "Identify the Problem",
    subtitle: "Research & Data",
    desc: "Community data reveals the problem — suspension rates, recidivism, ACEs prevalence, unaddressed SDOH. Map it to specific grant opportunities.",
    disciplines: ["implementation-science", "social-science", "healthcare"],
    platforms: ["Community Intelligence Map", "GIS Data", "Grant Discovery Engine"],
  },
  {
    step: 2,
    title: "Design the Intervention",
    subtitle: "MAP-GAP + Three Realities",
    desc: "Use MAP-GAP and Three Realities to design a program tailored to THIS community. What research says, what politics allow, what actually works on the ground.",
    disciplines: ["implementation-science", "criminal-justice", "hr-management", "io-psychology", "education", "social-science", "healthcare"],
    platforms: ["MAP-GAP CQI", "RPLICE", "Better Science Lab"],
  },
  {
    step: 3,
    title: "Coordinate Stakeholders",
    subtitle: "Build the Network",
    desc: "Bring in CHWs, mentors, community police, educators, employers — everyone connected through shared dashboards, shared goals, transparent metrics.",
    disciplines: ["hr-management", "io-psychology", "social-science", "healthcare"],
    platforms: ["Coalition Dashboard", "Partner Network", "DFC Command Center"],
  },
  {
    step: 4,
    title: "Execute with Fidelity",
    subtitle: "SALP Indicators",
    desc: "SALP indicators measure whether the program is implemented as designed. SMART goals visible to ALL stakeholders — real time, not year-end reports.",
    disciplines: ["implementation-science", "io-psychology", "education"],
    platforms: ["Dosage Tracking", "Case Management", "Outcome Reporting"],
  },
  {
    step: 5,
    title: "Measure & Improve",
    subtitle: "Continuous Quality Improvement",
    desc: "AI-powered insights show what's working and what's not. Continuous improvement loop — assess, adjust, improve. MAP-GAP brings homeostasis.",
    disciplines: ["implementation-science", "io-psychology"],
    platforms: ["MAP-GAP CQI", "Platform Metrics", "AI Insights"],
  },
  {
    step: 6,
    title: "Capture & Replicate",
    subtitle: "MG-PATR",
    desc: "When it works, capture lessons through MG-PATR. Then pilot and adapt for the next community — accounting for new Three Realities. Never copy-paste.",
    disciplines: ["implementation-science", "criminal-justice", "hr-management", "io-psychology"],
    platforms: ["Research Hub", "Implementation Plans", "Program Templates"],
  },
] as const;

export const PROGRAM_SHOWCASES = [
  {
    id: "mbk-chicago",
    title: "My Brother's Keeper",
    location: "Chicago, IL",
    problem: "School-to-Prison Pipeline",
    problemDesc: "High suspension rates, low graduation rates, ACEs prevalence, unaddressed SDOH driving youth into the justice system.",
    grants: ["CDC/ONDCP Drug-Free Communities", "DOE Title I/IV", "DOJ Second Chance Act", "SAMHSA"],
    interventions: [
      { discipline: "Implementation Science", action: "SEL curriculum through ISSS, MTSS compliance, communication-access support via Talk Your Talk" },
      { discipline: "Criminal Justice", action: "Diversion programs through SafeReport, restorative justice, reentry support via ThriveUp" },
      { discipline: "HR Management", action: "Workforce pathways for older youth through ThriveUp and MCE, career exposure" },
      { discipline: "I-O Psychology", action: "Behavioral nudges for students, staff motivation systems, mentor engagement design" },
    ],
    stakeholders: ["Schools", "Community Mentors", "Law Enforcement", "Employers", "Parents", "CHWs"],
    platforms: ["ThriveUp Academy", "ISSS", "SafeReport", "LifeBridge", "Talk Your Talk", "Sankofa Health"],
    outcomes: "Reduced suspensions, increased graduation rates, youth diverted from justice system, families connected to SDOH resources, sustainable community ownership.",
  },
  {
    id: "mbk-dc",
    title: "My Brother's Keeper",
    location: "Washington, DC",
    problem: "Same Framework, Different Community",
    problemDesc: "Same school-to-prison pipeline challenge, but different Three Realities — different political landscape, different community assets, different ground-level dynamics.",
    grants: ["CDC/ONDCP Drug-Free Communities", "DOJ OJJDP", "DC Government Grants"],
    interventions: [
      { discipline: "Implementation Science", action: "MAP-GAP assessment reveals different implementation barriers — adapted program design" },
      { discipline: "Criminal Justice", action: "DC-specific diversion pathways, different court systems, adapted reentry supports" },
      { discipline: "HR Management", action: "Different employer landscape — adapted workforce pipelines to DC economy" },
      { discipline: "I-O Psychology", action: "Community engagement adapted to DC cultural context — different motivation drivers" },
    ],
    stakeholders: ["DC Public Schools", "Community Organizations", "DC Courts", "Federal Employers", "Parents", "Faith-Based Orgs"],
    platforms: ["ThriveUp Academy", "ISSS", "SafeReport", "LifeBridge", "M2C Transition"],
    outcomes: "Same framework, adapted execution. Three Realities ensure the program fits DC — not a copy of Chicago. MG-PATR captures both for future deployments.",
  },
  {
    id: "workforce-rural",
    title: "Rural Workforce Revitalization",
    location: "Appalachian Region",
    problem: "Economic Decline & Substance Use Crisis",
    problemDesc: "Post-industrial economic decline, opioid crisis, limited healthcare access, brain drain of young professionals. Different problem, different setting — same ecosystem.",
    grants: ["WIOA Title I", "SAMHSA Opioid Response", "EDA Economic Adjustment", "USDA Rural Development"],
    interventions: [
      { discipline: "Implementation Science", action: "Community health assessment via Sankofa, substance use prevention through parent education" },
      { discipline: "Criminal Justice", action: "Drug court diversion, reentry support for substance-related incarceration" },
      { discipline: "HR Management", action: "New industry workforce pipelines — telehealth, renewable energy, remote tech jobs" },
      { discipline: "I-O Psychology", action: "Community resilience programming, combating learned helplessness, sustaining engagement" },
    ],
    stakeholders: ["Regional Health Systems", "Community Colleges", "Employers", "Recovery Courts", "CHWs", "Faith Communities"],
    platforms: ["ThriveUp Academy", "Sankofa Health", "LifeBridge", "MCE", "HerHealth Network"],
    outcomes: "Economic diversification, reduced substance use, new career pathways, healthcare access expansion — proving the ecosystem is truly agnostic to setting and problem.",
  },
] as const;
