import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { EvidenceSummary } from "@/components/evidence-label";
import { ConsentDisclosure } from "@/components/consent-disclosure";
import { apiRequest } from "@/lib/queryClient";

export default function DataHubPage() {
  const [category, setCategory] = useState("");
  const story = useQuery<any>({ queryKey: ["/api/place-story", "48", "48453"], queryFn: async () => (await apiRequest("GET", "/api/place-story/48/48453")).json() });
  const sources = useQuery<{ sources: any[] }>({ queryKey: ["/api/data-sources"], queryFn: async () => (await apiRequest("GET", "/api/data-sources")).json() });
  const submit = useMutation({ mutationFn: async (body: { geographyKey: string; category: string; observation: string }) => (await apiRequest("POST", "/api/community-intelligence", body)).json() });
  const data = story.data;
  const stats = data ? [["Population", data.population?.toLocaleString()], ["Poverty rate", data.povertyRate == null ? "Not available" : `${data.povertyRate.toFixed(1)}%`], ["Uninsured rate", data.uninsuredRate == null ? "Not available" : `${data.uninsuredRate.toFixed(1)}%`], ["Unemployment rate", data.unemploymentRate == null ? "Not available" : `${data.unemploymentRate.toFixed(1)}%`], ["Median income", data.medianIncome == null ? "Not available" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(data.medianIncome)]] : [];
  return <main className="container mx-auto max-w-6xl space-y-8 px-4 py-10"><header><h1 className="text-4xl font-bold">#DATA — Community Intelligence Hub</h1><p className="mt-2 text-lg text-muted-foreground">Real data. Real community. Real decisions.</p></header>
    <Tabs defaultValue="evidence"><TabsList><TabsTrigger value="evidence">Community Evidence</TabsTrigger><TabsTrigger value="library">Learning Library</TabsTrigger><TabsTrigger value="submit">Submit Observation</TabsTrigger></TabsList>
      <TabsContent value="evidence" className="space-y-4"><h2 className="text-2xl font-semibold">{data?.displayName ?? "Travis County, Texas"} community evidence</h2>{story.isLoading ? <p>Loading community evidence…</p> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{stats.map(([label, value]) => <Card key={label}><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value}</p></CardContent></Card>)}</div><EvidenceSummary claims={[{ value: data.population, unit: "people", source: "ACS 5-Year 2022", sourceId: "census-acs5-2022", asOfDate: "2022-01-01", geographyKey: data.geographyKey, confidence: "verified", decisionCaption: "County data supports community planning decisions." }]} /></>}</TabsContent>
      <TabsContent value="library" className="space-y-4"><h2 className="text-2xl font-semibold">Learning Library</h2>{sources.isLoading ? <p>Loading data sources…</p> : <div className="space-y-3">{(sources.data?.sources ?? []).map((source: any) => <Card key={source.id ?? source.sourceId}><CardContent className="pt-5"><h3 className="font-semibold">{source.name}</h3><p className="text-sm text-muted-foreground">{source.description ?? source.collectionMethod}</p><p className="mt-2 text-sm">Vintage: {source.vintage ?? source.timePeriod ?? "Not specified"}</p>{(source.url ?? source.primarySourceUrl) && <a className="text-sm text-blue-600 hover:underline" href={source.url ?? source.primarySourceUrl} target="_blank" rel="noreferrer">Source website</a>}</CardContent></Card>)}</div>}</TabsContent>
      <TabsContent value="submit" className="max-w-2xl space-y-4"><h2 className="text-2xl font-semibold">Submit an observation</h2><ConsentDisclosure compact purpose="Your observation helps identify community conditions that may need review." fields={[{ name: "ZIP code", why: "To locate the observation.", required: true }, { name: "Category", why: "To route it for review.", required: true }, { name: "Observation", why: "To understand the condition you observed.", required: true }]} sharing="Submissions are reviewed by the community intelligence team and are not published as individual records." withdrawal="Contact the community intelligence team to request withdrawal before review." /><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); submit.mutate({ geographyKey: String(form.get("zip")), category, observation: String(form.get("observation")) }); }}><div><Label htmlFor="zip">ZIP code</Label><Input id="zip" name="zip" pattern="[0-9]{5}" required /></div><div><Label>Category</Label><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue placeholder="Select a category" /></SelectTrigger><SelectContent>{["housing", "health", "education", "employment", "safety", "other"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="observation">Observation</Label><Textarea id="observation" name="observation" maxLength={2000} required /></div><Button type="submit" disabled={!category || submit.isPending}>{submit.isPending ? "Submitting…" : "Submit observation"}</Button>{submit.isSuccess && <p className="text-sm text-green-700">Thank you. Your observation has been submitted for review.</p>}{submit.isError && <p className="text-sm text-destructive">Unable to submit the observation. Please try again.</p>}</form></TabsContent>
    </Tabs>
  </main>;
}