import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import {
  FileText, Sparkles, Copy, Download, ChevronDown
} from "lucide-react";

const GRANT_TYPES = [
  {
    id: "WIOA",
    label: "WIOA Title I Youth",
    description: "Workforce Innovation & Opportunity Act — Youth workforce development, career pathways, digital literacy",
    color: "bg-blue-600",
    sections: ["Program Overview", "Statement of Need", "Program Design", "Workforce Development Strategy", "Performance Outcomes", "Sustainability Plan"],
  },
  {
    id: "OJJDP",
    label: "OJJDP Second Chance Act",
    description: "Office of Juvenile Justice — Reentry support, recidivism reduction, case management, community reintegration",
    color: "bg-violet-600",
    sections: ["Program Overview", "Statement of Need", "Program Design", "Reentry Strategy", "Recidivism Reduction Plan", "Community Partnerships"],
  },
  {
    id: "SAMHSA",
    label: "SAMHSA Community Mental Health",
    description: "Substance Abuse & Mental Health Services — Behavioral health, trauma-informed care, whole-child support",
    color: "bg-emerald-600",
    sections: ["Program Overview", "Statement of Need", "Program Design", "Behavioral Health Integration", "Trauma-Informed Approach", "Cultural Competency"],
  },
];

interface NarrativeResult {
  narrative: string;
  grantType: string;
  section: string;
  metrics: {
    participants: number;
    services: number;
    serviceHours: number;
    outcomes: number;
    boardMembers: number;
  };
}

export default function GrantNarrativePage() {
  const { toast } = useToast();
  const [selectedGrant, setSelectedGrant] = useState<string | null>(null);
  const [selectedSection, setSelectedSection] = useState<string>("Program Overview");
  const [narratives, setNarratives] = useState<NarrativeResult[]>([]);
  const [expandedGrant, setExpandedGrant] = useState<string | null>(null);

  const generateMutation = useMutation({
    mutationFn: async (data: { grantType: string; section: string }) => {
      const res = await apiRequest("POST", "/api/grant-narrative/generate", data);
      return res.json() as Promise<NarrativeResult>;
    },
    onSuccess: (result) => {
      setNarratives((prev) => [result, ...prev]);
      toast({ title: "Narrative section generated" });
    },
    onError: () => {
      toast({ title: "Failed to generate narrative", variant: "destructive" });
    },
  });

  const handleGenerate = () => {
    if (!selectedGrant) return;
    generateMutation.mutate({ grantType: selectedGrant, section: selectedSection });
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "Copied to clipboard" });
  };

  const handleDownload = (result: NarrativeResult) => {
    const content = `${result.grantType} Grant Narrative — ${result.section}\n\nGenerated by ThriveUp Grant Engine\n\n${result.narrative}\n\n---\nPlatform Metrics:\n- Participants Served: ${result.metrics.participants}\n- Service Encounters: ${result.metrics.services}\n- Service Hours: ${result.metrics.serviceHours}\n- Outcomes Tracked: ${result.metrics.outcomes}\n- Advisory Board Members: ${result.metrics.boardMembers}`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${result.grantType}_${result.section.replace(/\s+/g, "_")}_Narrative.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const currentGrant = GRANT_TYPES.find((g) => g.id === selectedGrant);

  return (
    <div className="p-4 sm:p-6 max-w-6xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold" data-testid="text-narrative-title">Grant Narrative Builder</h1>
        <p className="text-muted-foreground mt-1">Generate grant-ready narrative sections with real platform data and positioning language</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {GRANT_TYPES.map((grant) => (
          <button
            key={grant.id}
            onClick={() => {
              setSelectedGrant(grant.id);
              setSelectedSection(grant.sections[0]);
              setExpandedGrant(expandedGrant === grant.id ? null : grant.id);
            }}
            className={`text-left p-4 rounded-lg border-2 transition-all ${
              selectedGrant === grant.id ? "border-primary ring-2 ring-primary/20" : "border-border hover:border-primary/50"
            }`}
            data-testid={`button-grant-${grant.id.toLowerCase()}`}
          >
            <div className="flex items-center gap-3 mb-2">
              <div className={`${grant.color} rounded-md p-2`}>
                <FileText className="h-5 w-5 text-white" />
              </div>
              <h3 className="font-semibold">{grant.label}</h3>
            </div>
            <p className="text-sm text-muted-foreground">{grant.description}</p>
          </button>
        ))}
      </div>

      {currentGrant && (
        <Card className="p-5" data-testid="card-section-selector">
          <h2 className="font-semibold text-lg mb-3">Select Narrative Section</h2>
          <div className="flex flex-wrap gap-2 mb-4">
            {currentGrant.sections.map((section) => (
              <Button
                key={section}
                variant={selectedSection === section ? "default" : "outline"}
                size="sm"
                onClick={() => setSelectedSection(section)}
                data-testid={`button-section-${section.replace(/\s+/g, "-").toLowerCase()}`}
              >
                {section}
              </Button>
            ))}
          </div>
          <div className="flex items-center gap-3">
            <Button
              onClick={handleGenerate}
              disabled={generateMutation.isPending}
              data-testid="button-generate-narrative"
            >
              <Sparkles className="mr-2 h-4 w-4" />
              {generateMutation.isPending ? "Generating..." : "Generate Narrative"}
            </Button>
            <p className="text-sm text-muted-foreground">
              Generating: <span className="font-medium">{currentGrant.label}</span> — <span className="font-medium">{selectedSection}</span>
            </p>
          </div>
        </Card>
      )}

      {narratives.length > 0 && (
        <div className="space-y-4">
          <h2 className="font-semibold text-lg">Generated Narratives</h2>
          {narratives.map((result, idx) => {
            const grant = GRANT_TYPES.find((g) => g.id === result.grantType);
            return (
              <Card key={idx} className="p-5" data-testid={`card-narrative-${idx}`}>
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Badge className={grant?.color}>{result.grantType}</Badge>
                    <span className="font-medium text-sm">{result.section}</span>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline" onClick={() => handleCopy(result.narrative)} data-testid={`button-copy-${idx}`}>
                      <Copy className="h-3.5 w-3.5 mr-1" /> Copy
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => handleDownload(result)} data-testid={`button-download-${idx}`}>
                      <Download className="h-3.5 w-3.5 mr-1" /> Download
                    </Button>
                  </div>
                </div>
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <p className="whitespace-pre-wrap text-sm leading-relaxed">{result.narrative}</p>
                </div>
                <div className="mt-4 flex flex-wrap gap-3 text-xs text-muted-foreground">
                  <span>Participants: <span className="font-medium text-foreground">{result.metrics.participants}</span></span>
                  <span>Services: <span className="font-medium text-foreground">{result.metrics.services}</span></span>
                  <span>Hours: <span className="font-medium text-foreground">{result.metrics.serviceHours}</span></span>
                  <span>Outcomes: <span className="font-medium text-foreground">{result.metrics.outcomes}</span></span>
                  <span>Board Members: <span className="font-medium text-foreground">{result.metrics.boardMembers}</span></span>
                </div>
              </Card>
            );
          })}
        </div>
      )}

      <Card className="p-5" data-testid="card-positioning-language">
        <h2 className="font-semibold text-lg mb-3">Positioning Language Reference</h2>
        <div className="space-y-3">
          {[
            { key: "Mission", value: "ThriveUp Academy empowers justice-impacted and opportunity youth through a technology-enabled, three-pillar framework that moves participants from Relief through Stabilization to Community Contribution." },
            { key: "Differentiator", value: "Unlike traditional workforce programs, ThriveUp integrates AI-powered career exploration, behavioral health screening, and real-time outcome tracking into a single platform, ensuring every participant receives holistic, data-driven support." },
            { key: "Evidence", value: "The platform's six-domain Thrive scoring system, aligned with DOJ Performance Measurement Tool requirements, enables continuous progress monitoring and evidence-based intervention adjustment." },
            { key: "Community Voice", value: "Our Community Advisory Board, composed of individuals with lived experience, community leaders, and partner agency representatives, ensures program design reflects the authentic needs and aspirations of the communities we serve." },
          ].map((item) => (
            <div key={item.key} className="p-3 bg-muted rounded-lg">
              <p className="text-sm font-medium text-primary mb-1">{item.key}</p>
              <p className="text-sm text-muted-foreground">{item.value}</p>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
