/**
 * Runtime guard for the public Community Brief evidence contract.
 *
 * This is intentionally stricter than TypeScript: public shares and exports
 * cross a trust boundary, so only a complete v1 disclosure can be rendered.
 */
const REQUEST_TYPES = new Set(["zip", "city", "address_or_place", "county", "multi_county"]);
const RESOLVED_TYPES = new Set(["zcta", "county", "multi_county"]);
// historicalCascade is intentionally NOT in the required-keys list: it was
// added after the original v1 contract shipped, so legacy cached/stored briefs
// that predate it must still pass validation (backward compat). If the claim
// is present, it is validated below; if absent, validation is unaffected.
const CLAIM_KEYS = ["observed", "tcafDerived", "tcafScenario", "aiSynthesis"] as const;

// A public share is allowed only for a brief the current server process produced
// from its Census/AI pipeline.  This is deliberately separate from the shape
// guard below: a well-formed evidence object sent by a browser is still not
// proof that its scores, demographics, or narrative were generated by us.
//
// This is an in-memory provenance record rather than a client capability. It
// does not extend the database schema or make a caller-controlled payload
// durable. A restart (or an expired record) fails closed; the caller can obtain
// a fresh authoritative brief from the public analyzer and share that result.
const SERVER_BRIEF_PROVENANCE_TTL_MS = 2 * 60 * 60 * 1000;
const SERVER_BRIEF_PROVENANCE_MAX = 300;
const serverBriefProvenance = new Map<string, { at: number; brief: Record<string, unknown> }>();

const isRecord = (value: unknown): value is Record<string, any> =>
  typeof value === "object" && value !== null && !Array.isArray(value);
const isText = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0;

function provenanceKey(brief: unknown): string | null {
  if (!isRecord(brief) || !hasValidCommunityEvidence(brief) || !isText(brief.generatedAt)) return null;
  // Evidence disclosures and the server-issued generation timestamp identify a
  // specific analyzer result. JSON is sufficient here because these values are
  // produced and serialized by this server on both sides of the lookup.
  return JSON.stringify({ evidence: brief.evidence, generatedAt: brief.generatedAt });
}

/** Register an analyzer result as eligible for a later anonymous share request. */
export function registerServerCommunityBrief(brief: Record<string, unknown>): void {
  const key = provenanceKey(brief);
  if (!key) return;
  const now = Date.now();
  serverBriefProvenance.set(key, { at: now, brief });
  for (const [candidateKey, record] of serverBriefProvenance) {
    if (now - record.at > SERVER_BRIEF_PROVENANCE_TTL_MS) serverBriefProvenance.delete(candidateKey);
  }
  while (serverBriefProvenance.size > SERVER_BRIEF_PROVENANCE_MAX) {
    const oldest = serverBriefProvenance.keys().next().value;
    if (oldest === undefined) break;
    serverBriefProvenance.delete(oldest);
  }
}

/**
 * Return the server-produced brief identified by a share request, if it is
 * still held locally. Never return the caller's object: callers supply only a
 * lookup handle, while the persisted content always comes from this record.
 */
export function findServerCommunityBrief(brief: unknown): Record<string, unknown> | null {
  const key = provenanceKey(brief);
  if (!key) return null;
  const record = serverBriefProvenance.get(key);
  if (!record) return null;
  if (Date.now() - record.at > SERVER_BRIEF_PROVENANCE_TTL_MS) {
    serverBriefProvenance.delete(key);
    return null;
  }
  return record.brief;
}

export function hasValidCommunityEvidence(brief: unknown): boolean {
  if (!isRecord(brief) || !isRecord(brief.evidence)) return false;
  const evidence = brief.evidence;
  if (evidence.version !== "community-evidence/v1" || !isRecord(evidence.geography)) return false;

  const requested = evidence.geography.requested;
  const resolved = evidence.geography.resolved;
  if (!isRecord(requested) || !isText(requested.input) || !REQUEST_TYPES.has(requested.type)) return false;
  if (!isRecord(resolved) || !RESOLVED_TYPES.has(resolved.type)
    || !isText(resolved.identifier) || !isText(resolved.label) || !isText(resolved.method)) return false;
  // Exact match is the common case; also accept a qualifier appended after the
  // base label (e.g. "ZCTA 28472 (partial)") so a future, more descriptive
  // label doesn't get rejected outright with no recovery path.
  if (resolved.type === "zcta" && (!/^\d{5}$/.test(resolved.identifier) || !resolved.label.startsWith(`ZCTA ${resolved.identifier}`))) return false;
  if (resolved.coverageWarning != null && !isText(resolved.coverageWarning)) return false;

  if (!Array.isArray(evidence.sources) || evidence.sources.length < 1) return false;
  if (!evidence.sources.every((source: unknown) => isRecord(source)
    && isText(source.publisher) && isText(source.dataset) && isText(source.vintage)
    && isText(source.url) && /^https:\/\//.test(source.url)
    && isText(source.geographyGrain) && isText(source.retrievedAt)
    && Number.isFinite(new Date(source.retrievedAt).getTime()))) return false;

  if (!isRecord(evidence.claims) || !isRecord(evidence.dataQuality)) return false;
  for (const key of CLAIM_KEYS) {
    const claim = evidence.claims[key];
    if (!isRecord(claim) || !isText(claim.label) || !["available", "unavailable"].includes(claim.status)) return false;
    if (key !== "observed" && !isText(claim.disclosure)) return false;
  }
  // historicalCascade is optional (added after v1 shipped); validate it only if present.
  if (evidence.claims.historicalCascade != null) {
    const hc = evidence.claims.historicalCascade;
    if (!isRecord(hc) || !isText(hc.label) || !["available", "unavailable"].includes(hc.status) || !isText(hc.disclosure)) return false;
  }
  return ["verified_at_resolved_grain", "limited_resolution", "unavailable"].includes(evidence.dataQuality.status)
    && Array.isArray(evidence.dataQuality.warnings)
    && evidence.dataQuality.warnings.every(isText);
}

/**
 * Force the rendered `brief.geography` to agree with the evidence contract's
 * resolved geography, in place.
 *
 * A caller-supplied brief could otherwise pair a valid evidence block for one
 * geography (e.g. a single ZCTA) with an arbitrary `brief.geography` shown
 * prominently in share pages, PDFs, and embeds (e.g. a citywide label) —
 * publishing a claim/geography mismatch the evidence contract exists to
 * prevent. This must run AFTER `hasValidCommunityEvidence(brief)` has
 * returned true, at every point a brief is persisted or re-served across a
 * public trust boundary (share POST/GET, story POST/GET, PDF export).
 */
export function canonicalizeGeographyFromEvidence(brief: Record<string, any>): void {
  const resolved = brief.evidence?.geography?.resolved;
  if (!isRecord(resolved)) return;
  const geo: Record<string, any> = isRecord(brief.geography) ? brief.geography : {};
  geo.displayName = resolved.label;
  if (resolved.type === "zcta") {
    geo.zip = resolved.identifier;
    delete geo.countyName;
  } else {
    // county / multi_county
    geo.countyName = resolved.label;
    delete geo.zip;
  }
  brief.geography = geo;
}