import { outcomeTracking, reentryPlans, reentryMilestones } from "@shared/schema";

const DEMO_PARTICIPANTS = [
  { id: "participant-001", name: "Marcus Johnson" },
  { id: "participant-002", name: "Devonte Williams" },
  { id: "participant-003", name: "Keisha Brown" },
  { id: "participant-004", name: "James Rodriguez" },
  { id: "participant-005", name: "Tyrell Washington" },
  { id: "participant-006", name: "Angela Davis-Moore" },
  { id: "participant-007", name: "Carlos Hernandez" },
  { id: "participant-008", name: "Brianna Carter" },
  { id: "participant-009", name: "DeAndre Mitchell" },
  { id: "participant-010", name: "Jasmine Thompson" },
  { id: "participant-011", name: "Robert Chen" },
  { id: "participant-012", name: "Tasha Reynolds" },
  { id: "participant-013", name: "Luis Morales" },
  { id: "participant-014", name: "Shanice Green" },
  { id: "participant-015", name: "David Nguyen" },
  { id: "participant-016", name: "Crystal Jackson" },
  { id: "participant-017", name: "Omar Franklin" },
  { id: "participant-018", name: "Aaliyah Cooper" },
  { id: "participant-019", name: "Jerome Patterson" },
  { id: "participant-020", name: "Maria Santos" },
  { id: "participant-021", name: "Darius White" },
  { id: "participant-022", name: "Latoya Harris" },
  { id: "participant-023", name: "Antonio Rivera" },
  { id: "participant-024", name: "Kendra Powell" },
  { id: "participant-025", name: "Malcolm Stewart" },
];

function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}

export async function seedOutcomeData(db: any): Promise<void> {
  const reentryPlanData = [
    { id: "plan-001", userId: "participant-001", userName: "Marcus Johnson", phase: "stabilization", status: "active", riskLevel: "medium", releaseDate: daysAgo(180), transitionStartDate: daysAgo(150), stabilizationStartDate: daysAgo(90), notes: "Enrolled in AI Workforce Academy Track 2. Stable housing secured through partner referral." },
    { id: "plan-002", userId: "participant-002", userName: "Devonte Williams", phase: "independence", status: "active", riskLevel: "low", releaseDate: daysAgo(365), transitionStartDate: daysAgo(330), stabilizationStartDate: daysAgo(240), independenceStartDate: daysAgo(120), notes: "Completed welding certification. Employed at Austin Metal Works. Mentoring new participants." },
    { id: "plan-003", userId: "participant-003", userName: "Keisha Brown", phase: "transition", status: "active", riskLevel: "high", releaseDate: daysAgo(60), transitionStartDate: daysAgo(45), notes: "Recently released. Connecting with housing and behavioral health services. Children in DFPS system." },
    { id: "plan-004", userId: "participant-005", userName: "Tyrell Washington", phase: "stabilization", status: "active", riskLevel: "medium", releaseDate: daysAgo(210), transitionStartDate: daysAgo(195), stabilizationStartDate: daysAgo(120), notes: "GED completed. Starting workforce readiness modules. Part-time employment at H-E-B." },
    { id: "plan-005", userId: "participant-006", userName: "Angela Davis-Moore", phase: "independence", status: "completed", riskLevel: "low", releaseDate: daysAgo(540), transitionStartDate: daysAgo(510), stabilizationStartDate: daysAgo(420), independenceStartDate: daysAgo(300), completionDate: daysAgo(30), notes: "Program graduate. Full-time employment as medical assistant. Reunified with family. Active community ambassador." },
    { id: "plan-006", userId: "participant-009", userName: "DeAndre Mitchell", phase: "pre_release", status: "active", riskLevel: "high", releaseDate: daysAgo(-30), notes: "Expected release in 30 days. Pre-release planning underway. Connecting with employer partners." },
    { id: "plan-007", userId: "participant-017", userName: "Omar Franklin", phase: "transition", status: "active", riskLevel: "medium", releaseDate: daysAgo(90), transitionStartDate: daysAgo(75), notes: "Veteran. Connecting with VA services and SSG Fox programs. AI literacy modules in progress." },
    { id: "plan-008", userId: "participant-019", userName: "Jerome Patterson", phase: "stabilization", status: "active", riskLevel: "low", releaseDate: daysAgo(270), transitionStartDate: daysAgo(250), stabilizationStartDate: daysAgo(180), notes: "Completed CDL training. Employed as delivery driver. Attending financial literacy workshops." },
  ];

  await db.insert(reentryPlans).values(reentryPlanData).onConflictDoNothing();

  const milestoneData = [
    { id: "ms-001", planId: "plan-001", userId: "participant-001", category: "employment", title: "Complete AI Workforce Track 2", description: "Finish all modules in AI Foundations & Ethics track", phase: "stabilization", status: "in_progress", targetDate: daysAgo(-30) },
    { id: "ms-002", planId: "plan-001", userId: "participant-001", category: "housing", title: "Secure stable housing", description: "Obtain lease through partner housing authority", phase: "stabilization", status: "completed", targetDate: daysAgo(30), completedDate: daysAgo(45) },
    { id: "ms-003", planId: "plan-001", userId: "participant-001", category: "education", title: "Earn digital literacy credential", description: "Complete digital literacy certification through ThriveUp", phase: "stabilization", status: "completed", targetDate: daysAgo(10), completedDate: daysAgo(15) },
    { id: "ms-004", planId: "plan-002", userId: "participant-002", category: "employment", title: "Obtain welding certification", description: "Complete AWS D1.1 welding certification program", phase: "stabilization", status: "completed", targetDate: daysAgo(180), completedDate: daysAgo(200) },
    { id: "ms-005", planId: "plan-002", userId: "participant-002", category: "employment", title: "Job placement - skilled trade", description: "Secure full-time employment using welding certification", phase: "independence", status: "completed", targetDate: daysAgo(150), completedDate: daysAgo(160) },
    { id: "ms-006", planId: "plan-002", userId: "participant-002", category: "housing", title: "Independent housing", description: "Transition from transitional to independent housing", phase: "independence", status: "completed", targetDate: daysAgo(120), completedDate: daysAgo(130) },
    { id: "ms-007", planId: "plan-002", userId: "participant-002", category: "behavioral_health", title: "Complete substance abuse program", description: "Graduate from 90-day outpatient substance abuse treatment", phase: "stabilization", status: "completed", targetDate: daysAgo(240), completedDate: daysAgo(250) },
    { id: "ms-008", planId: "plan-003", userId: "participant-003", category: "housing", title: "Emergency housing placement", description: "Secure emergency shelter through Salvation Army partnership", phase: "transition", status: "completed", targetDate: daysAgo(40), completedDate: daysAgo(42) },
    { id: "ms-009", planId: "plan-003", userId: "participant-003", category: "behavioral_health", title: "Mental health assessment", description: "Complete intake assessment with Integral Care", phase: "transition", status: "completed", targetDate: daysAgo(30), completedDate: daysAgo(35) },
    { id: "ms-010", planId: "plan-003", userId: "participant-003", category: "education", title: "Enroll in GED program", description: "Register for GED preparation through ACC partnership", phase: "transition", status: "in_progress", targetDate: daysAgo(-14) },
    { id: "ms-011", planId: "plan-004", userId: "participant-005", category: "education", title: "GED completion", description: "Pass all four GED subject tests", phase: "stabilization", status: "completed", targetDate: daysAgo(60), completedDate: daysAgo(75) },
    { id: "ms-012", planId: "plan-004", userId: "participant-005", category: "employment", title: "Part-time employment", description: "Secure part-time position for income stability", phase: "stabilization", status: "completed", targetDate: daysAgo(90), completedDate: daysAgo(95) },
    { id: "ms-013", planId: "plan-005", userId: "participant-006", category: "employment", title: "Medical assistant certification", description: "Complete CMA certification through ACC", phase: "stabilization", status: "completed", targetDate: daysAgo(360), completedDate: daysAgo(370) },
    { id: "ms-014", planId: "plan-005", userId: "participant-006", category: "employment", title: "Full-time healthcare employment", description: "Hired as medical assistant at CommUnityCare", phase: "independence", status: "completed", targetDate: daysAgo(300), completedDate: daysAgo(310) },
    { id: "ms-015", planId: "plan-005", userId: "participant-006", category: "housing", title: "Family reunification housing", description: "Secure 2-bedroom apartment for family reunification", phase: "independence", status: "completed", targetDate: daysAgo(200), completedDate: daysAgo(210) },
    { id: "ms-016", planId: "plan-007", userId: "participant-017", category: "employment", title: "VA benefits enrollment", description: "Complete VA benefits application and intake", phase: "transition", status: "completed", targetDate: daysAgo(60), completedDate: daysAgo(65) },
    { id: "ms-017", planId: "plan-007", userId: "participant-017", category: "behavioral_health", title: "PTSD assessment", description: "Complete PTSD screening and treatment plan with VA", phase: "transition", status: "in_progress", targetDate: daysAgo(-7) },
    { id: "ms-018", planId: "plan-008", userId: "participant-019", category: "employment", title: "CDL license obtained", description: "Pass CDL written and driving tests", phase: "stabilization", status: "completed", targetDate: daysAgo(120), completedDate: daysAgo(130) },
    { id: "ms-019", planId: "plan-008", userId: "participant-019", category: "employment", title: "Full-time driving position", description: "Hired as delivery driver at local logistics company", phase: "stabilization", status: "completed", targetDate: daysAgo(90), completedDate: daysAgo(100) },
    { id: "ms-020", planId: "plan-008", userId: "participant-019", category: "education", title: "Financial literacy completion", description: "Complete all financial literacy workshop modules", phase: "stabilization", status: "in_progress", targetDate: daysAgo(-21) },
  ];

  await db.insert(reentryMilestones).values(milestoneData).onConflictDoNothing();

  const outcomeData = [
    { id: "oc-001", userId: "participant-001", planId: "plan-001", category: "recidivism", metricName: "6mo_status", metricValue: "no_reoffense", periodMonths: 6, source: "court_records", measurementDate: daysAgo(1), isDemoData: true },
    { id: "oc-002", userId: "participant-001", planId: "plan-001", category: "employment", metricName: "job_placement", metricValue: "placed", source: "case_manager", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-003", userId: "participant-001", planId: "plan-001", category: "housing", metricName: "stability_status", metricValue: "stable", source: "housing_authority", measurementDate: daysAgo(15), isDemoData: true },
    { id: "oc-004", userId: "participant-001", planId: "plan-001", category: "education", metricName: "credential_completion", metricValue: "digital_literacy_cert", source: "academy", measurementDate: daysAgo(15), isDemoData: true },
    { id: "oc-005", userId: "participant-002", planId: "plan-002", category: "recidivism", metricName: "6mo_status", metricValue: "no_reoffense", periodMonths: 6, source: "court_records", measurementDate: daysAgo(180), isDemoData: true },
    { id: "oc-006", userId: "participant-002", planId: "plan-002", category: "recidivism", metricName: "12mo_status", metricValue: "no_reoffense", periodMonths: 12, source: "court_records", measurementDate: daysAgo(1), isDemoData: true },
    { id: "oc-007", userId: "participant-002", planId: "plan-002", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(160), isDemoData: true },
    { id: "oc-008", userId: "participant-002", planId: "plan-002", category: "employment", metricName: "retention", metricValue: "retained_90day", periodMonths: 3, source: "employer_report", measurementDate: daysAgo(70), isDemoData: true },
    { id: "oc-009", userId: "participant-002", planId: "plan-002", category: "employment", metricName: "wage_progression", metricValue: "$18.50/hr_to_$22.00/hr", source: "payroll_records", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-010", userId: "participant-002", planId: "plan-002", category: "education", metricName: "credential_completion", metricValue: "aws_welding_cert", source: "training_provider", measurementDate: daysAgo(200), isDemoData: true },
    { id: "oc-011", userId: "participant-002", planId: "plan-002", category: "housing", metricName: "stability_status", metricValue: "stable", source: "case_manager", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-012", userId: "participant-002", planId: "plan-002", category: "behavioral_health", metricName: "treatment_progress", metricValue: "completed_outpatient", source: "treatment_provider", measurementDate: daysAgo(250), isDemoData: true },
    { id: "oc-013", userId: "participant-003", planId: "plan-003", category: "housing", metricName: "stability_status", metricValue: "emergency_shelter", source: "shelter_intake", measurementDate: daysAgo(42), isDemoData: true },
    { id: "oc-014", userId: "participant-003", planId: "plan-003", category: "behavioral_health", metricName: "assessment_score", metricValue: "moderate_depression_anxiety", source: "clinical_assessment", measurementDate: daysAgo(35), isDemoData: true },
    { id: "oc-015", userId: "participant-004", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(90), isDemoData: true },
    { id: "oc-016", userId: "participant-004", category: "employment", metricName: "retention", metricValue: "retained_30day", periodMonths: 1, source: "employer_report", measurementDate: daysAgo(60), isDemoData: true },
    { id: "oc-017", userId: "participant-004", category: "education", metricName: "enrollment", metricValue: "ai_workforce_track_1", source: "academy", measurementDate: daysAgo(120), isDemoData: true },
    { id: "oc-018", userId: "participant-005", planId: "plan-004", category: "recidivism", metricName: "6mo_status", metricValue: "no_reoffense", periodMonths: 6, source: "court_records", measurementDate: daysAgo(10), isDemoData: true },
    { id: "oc-019", userId: "participant-005", planId: "plan-004", category: "employment", metricName: "job_placement", metricValue: "placed_part_time", source: "case_manager", measurementDate: daysAgo(95), isDemoData: true },
    { id: "oc-020", userId: "participant-005", planId: "plan-004", category: "education", metricName: "ged_diploma", metricValue: "ged_completed", source: "testing_center", measurementDate: daysAgo(75), isDemoData: true },
    { id: "oc-021", userId: "participant-006", planId: "plan-005", category: "recidivism", metricName: "6mo_status", metricValue: "no_reoffense", periodMonths: 6, source: "court_records", measurementDate: daysAgo(360), isDemoData: true },
    { id: "oc-022", userId: "participant-006", planId: "plan-005", category: "recidivism", metricName: "12mo_status", metricValue: "no_reoffense", periodMonths: 12, source: "court_records", measurementDate: daysAgo(180), isDemoData: true },
    { id: "oc-023", userId: "participant-006", planId: "plan-005", category: "recidivism", metricName: "36mo_status", metricValue: "no_reoffense", periodMonths: 36, source: "court_records", measurementDate: daysAgo(1), isDemoData: true },
    { id: "oc-024", userId: "participant-006", planId: "plan-005", category: "employment", metricName: "job_placement", metricValue: "placed_full_time", source: "employer_report", measurementDate: daysAgo(310), isDemoData: true },
    { id: "oc-025", userId: "participant-006", planId: "plan-005", category: "employment", metricName: "retention", metricValue: "retained_90day", periodMonths: 3, source: "employer_report", measurementDate: daysAgo(220), isDemoData: true },
    { id: "oc-026", userId: "participant-006", planId: "plan-005", category: "employment", metricName: "wage_progression", metricValue: "$15.00/hr_to_$19.50/hr", source: "payroll_records", measurementDate: daysAgo(60), isDemoData: true },
    { id: "oc-027", userId: "participant-006", planId: "plan-005", category: "education", metricName: "credential_completion", metricValue: "cma_certification", source: "training_provider", measurementDate: daysAgo(370), isDemoData: true },
    { id: "oc-028", userId: "participant-006", planId: "plan-005", category: "housing", metricName: "stability_status", metricValue: "stable_independent", source: "case_manager", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-029", userId: "participant-007", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(45), isDemoData: true },
    { id: "oc-030", userId: "participant-007", category: "employment", metricName: "retention", metricValue: "retained_30day", periodMonths: 1, source: "employer_report", measurementDate: daysAgo(15), isDemoData: true },
    { id: "oc-031", userId: "participant-007", category: "education", metricName: "enrollment", metricValue: "workforce_readiness_modules", source: "academy", measurementDate: daysAgo(90), isDemoData: true },
    { id: "oc-032", userId: "participant-008", category: "education", metricName: "enrollment", metricValue: "ai_workforce_track_3", source: "academy", measurementDate: daysAgo(60), isDemoData: true },
    { id: "oc-033", userId: "participant-008", category: "education", metricName: "credential_completion", metricValue: "ai_foundations_cert", source: "academy", measurementDate: daysAgo(20), isDemoData: true },
    { id: "oc-034", userId: "participant-008", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(10), isDemoData: true },
    { id: "oc-035", userId: "participant-010", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(120), isDemoData: true },
    { id: "oc-036", userId: "participant-010", category: "employment", metricName: "retention", metricValue: "retained_90day", periodMonths: 3, source: "employer_report", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-037", userId: "participant-010", category: "education", metricName: "credential_completion", metricValue: "customer_service_cert", source: "training_provider", measurementDate: daysAgo(150), isDemoData: true },
    { id: "oc-038", userId: "participant-011", category: "education", metricName: "enrollment", metricValue: "sel_leadership_modules", source: "academy", measurementDate: daysAgo(45), isDemoData: true },
    { id: "oc-039", userId: "participant-011", category: "behavioral_health", metricName: "assessment_score", metricValue: "low_risk_stable", source: "clinical_assessment", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-040", userId: "participant-012", category: "employment", metricName: "job_placement", metricValue: "placed", source: "case_manager", measurementDate: daysAgo(75), isDemoData: true },
    { id: "oc-041", userId: "participant-012", category: "employment", metricName: "retention", metricValue: "retained_30day", periodMonths: 1, source: "employer_report", measurementDate: daysAgo(45), isDemoData: true },
    { id: "oc-042", userId: "participant-012", category: "housing", metricName: "stability_status", metricValue: "transitional", source: "housing_authority", measurementDate: daysAgo(60), isDemoData: true },
    { id: "oc-043", userId: "participant-013", category: "education", metricName: "enrollment", metricValue: "financial_literacy", source: "academy", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-044", userId: "participant-013", category: "education", metricName: "ged_diploma", metricValue: "ged_in_progress", source: "testing_center", measurementDate: daysAgo(60), isDemoData: true },
    { id: "oc-045", userId: "participant-014", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(100), isDemoData: true },
    { id: "oc-046", userId: "participant-014", category: "employment", metricName: "retention", metricValue: "retained_90day", periodMonths: 3, source: "employer_report", measurementDate: daysAgo(10), isDemoData: true },
    { id: "oc-047", userId: "participant-014", category: "education", metricName: "credential_completion", metricValue: "phlebotomy_cert", source: "training_provider", measurementDate: daysAgo(130), isDemoData: true },
    { id: "oc-048", userId: "participant-015", category: "behavioral_health", metricName: "treatment_progress", metricValue: "in_treatment_improving", source: "treatment_provider", measurementDate: daysAgo(20), isDemoData: true },
    { id: "oc-049", userId: "participant-015", category: "housing", metricName: "stability_status", metricValue: "stable", source: "case_manager", measurementDate: daysAgo(15), isDemoData: true },
    { id: "oc-050", userId: "participant-016", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(60), isDemoData: true },
    { id: "oc-051", userId: "participant-016", category: "education", metricName: "enrollment", metricValue: "ai_workforce_track_2", source: "academy", measurementDate: daysAgo(90), isDemoData: true },
    { id: "oc-052", userId: "participant-017", planId: "plan-007", category: "recidivism", metricName: "6mo_status", metricValue: "no_reoffense", periodMonths: 6, source: "court_records", measurementDate: daysAgo(1), isDemoData: true },
    { id: "oc-053", userId: "participant-017", planId: "plan-007", category: "behavioral_health", metricName: "assessment_score", metricValue: "ptsd_moderate_improving", source: "va_assessment", measurementDate: daysAgo(20), isDemoData: true },
    { id: "oc-054", userId: "participant-018", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(40), isDemoData: true },
    { id: "oc-055", userId: "participant-018", category: "education", metricName: "credential_completion", metricValue: "medical_coding_cert", source: "training_provider", measurementDate: daysAgo(80), isDemoData: true },
    { id: "oc-056", userId: "participant-019", planId: "plan-008", category: "recidivism", metricName: "6mo_status", metricValue: "no_reoffense", periodMonths: 6, source: "court_records", measurementDate: daysAgo(90), isDemoData: true },
    { id: "oc-057", userId: "participant-019", planId: "plan-008", category: "employment", metricName: "job_placement", metricValue: "placed_full_time", source: "employer_report", measurementDate: daysAgo(100), isDemoData: true },
    { id: "oc-058", userId: "participant-019", planId: "plan-008", category: "employment", metricName: "retention", metricValue: "retained_90day", periodMonths: 3, source: "employer_report", measurementDate: daysAgo(10), isDemoData: true },
    { id: "oc-059", userId: "participant-019", planId: "plan-008", category: "education", metricName: "credential_completion", metricValue: "cdl_license", source: "dmv_records", measurementDate: daysAgo(130), isDemoData: true },
    { id: "oc-060", userId: "participant-020", category: "education", metricName: "enrollment", metricValue: "workforce_readiness_9_12", source: "academy", measurementDate: daysAgo(45), isDemoData: true },
    { id: "oc-061", userId: "participant-020", category: "education", metricName: "credential_completion", metricValue: "workforce_readiness_cert", source: "academy", measurementDate: daysAgo(10), isDemoData: true },
    { id: "oc-062", userId: "participant-021", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(55), isDemoData: true },
    { id: "oc-063", userId: "participant-021", category: "employment", metricName: "retention", metricValue: "retained_30day", periodMonths: 1, source: "employer_report", measurementDate: daysAgo(25), isDemoData: true },
    { id: "oc-064", userId: "participant-022", category: "education", metricName: "enrollment", metricValue: "ai_literacy_6_8", source: "academy", measurementDate: daysAgo(30), isDemoData: true },
    { id: "oc-065", userId: "participant-022", category: "behavioral_health", metricName: "assessment_score", metricValue: "low_risk_stable", source: "school_counselor", measurementDate: daysAgo(20), isDemoData: true },
    { id: "oc-066", userId: "participant-023", category: "education", metricName: "ged_diploma", metricValue: "ged_completed", source: "testing_center", measurementDate: daysAgo(40), isDemoData: true },
    { id: "oc-067", userId: "participant-023", category: "employment", metricName: "job_placement", metricValue: "placed", source: "case_manager", measurementDate: daysAgo(20), isDemoData: true },
    { id: "oc-068", userId: "participant-024", category: "education", metricName: "enrollment", metricValue: "sel_emotional_intelligence", source: "academy", measurementDate: daysAgo(60), isDemoData: true },
    { id: "oc-069", userId: "participant-024", category: "education", metricName: "credential_completion", metricValue: "sel_completion_cert", source: "academy", measurementDate: daysAgo(15), isDemoData: true },
    { id: "oc-070", userId: "participant-025", category: "employment", metricName: "job_placement", metricValue: "placed", source: "employer_report", measurementDate: daysAgo(80), isDemoData: true },
    { id: "oc-071", userId: "participant-025", category: "employment", metricName: "retention", metricValue: "retained_90day", periodMonths: 3, source: "employer_report", measurementDate: daysAgo(1), isDemoData: true },
    { id: "oc-072", userId: "participant-025", category: "housing", metricName: "stability_status", metricValue: "stable_independent", source: "case_manager", measurementDate: daysAgo(10), isDemoData: true },
    { id: "oc-073", userId: "participant-025", category: "education", metricName: "credential_completion", metricValue: "hvac_certification", source: "training_provider", measurementDate: daysAgo(110), isDemoData: true },
  ];

  await db.insert(outcomeTracking).values(outcomeData).onConflictDoNothing();

  console.log(`[Seed] Outcome data seeded: ${reentryPlanData.length} reentry plans, ${milestoneData.length} milestones, ${outcomeData.length} outcome measurements`);
}
