/**
 * Seed Data Sources — 20 canonical platform data sources
 *
 * Idempotent upsert. Safe to run on every deployment.
 * Run: npx tsx server/seed-data-sources.ts
 */
import { db } from "./storage";
import { dataSources } from "@shared/schema";

const SOURCES = [
  {
    id: "cdc-places",
    name: "CDC PLACES — local modeled adult health and social needs",
    owner: "Centers for Disease Control and Prevention",
    collectionMethod: "BRFSS/Census/ACS multilevel regression and poststratification; crude estimates retained separately from age-adjusted estimates",
    evidenceClass: "modeled",
    geographyLevel: "County / census tract / place / ZCTA",
    timePeriod: "Per-measure year retained; 2025 release primarily 2023 with five 2022 measures",
    refreshCadence: "Annual release; on-demand reader cache 6 hours",
    coverage: "Measure/geography-specific; KY/PA lack 2023 estimates; social needs cover 39 states and DC",
    knownLimitations: "Adult area estimates are not personal diagnoses or observed intervention outcomes. CDC advises against evaluating local intervention effects with PLACES. ZIP and ZCTA are not identical. Confidence intervals, denominators, and missing values are retained.",
    suppressionRules: "Source missing/footnoted estimates remain unavailable; no zero substitution",
    primarySourceUrl: "https://www.cdc.gov/places/current-release-notes/index.html",
    citationFormat: "CDC PLACES [release], [geography/GEOID], [measure], [observation year], crude prevalence and 95% CI",
    steward: "Government evidence / GIS / community context",
  },
  {
    id: "census-acs-5yr",
    name: "American Community Survey 5-Year Estimates",
    owner: "U.S. Census Bureau",
    collectionMethod: "Household survey (rolling 5-year average)",
    evidenceClass: "estimated",
    geographyLevel: "county / ZIP / tract / place",
    timePeriod: "Importer baseline 2018-2022; retain source-specific observation periods",
    refreshCadence: "Annual",
    coverage: "Nationwide, all geographies",
    knownLimitations: "Margin of error increases for small populations. Small-area estimates (ZIP, tract) have wider CIs than county or state. Rural areas particularly affected.",
    suppressionRules: "ACS suppresses values with CVs > 40%",
    primarySourceUrl: "https://www.census.gov/programs-surveys/acs",
    citationFormat: "U.S. Census Bureau, American Community Survey 5-Year Estimates, [table], [year]",
    steward: "Community Intelligence",
  },
  {
    id: "hud-pit-annual",
    name: "HUD Point-in-Time Count",
    owner: "U.S. Department of Housing and Urban Development",
    collectionMethod: "Single-night count by Continuums of Care (volunteer observers)",
    evidenceClass: "observed",
    geographyLevel: "CoC (Continuum of Care) — not county-level",
    timePeriod: "Annual (January count)",
    refreshCadence: "Annual",
    coverage: "Nationwide",
    knownLimitations: "Single-night snapshot significantly undercounts hidden homelessness. Rural CoCs have higher undercount rates. Youth counts began 2015. COVID years (2021) used alternative methodology.",
    suppressionRules: "HUD suppresses small cells < 11",
    primarySourceUrl: "https://www.hudexchange.info/programs/hdx/pit-hic/",
    citationFormat: "HUD, Point-in-Time Count, [CoC name], [year]",
    steward: "Community Intelligence",
  },
  {
    id: "rplice-studies",
    name: "RPLICE Implementation Science Library",
    owner: "Better Science Lab / ISS LLC",
    collectionMethod: "Curated peer-reviewed literature (CFIR 2.0, RE-AIM, EPIS, ERIC taxonomy)",
    evidenceClass: "verified",
    geographyLevel: "Varies by study",
    timePeriod: "Continuously updated",
    refreshCadence: "Ongoing",
    coverage: "Community health, workforce, education, justice, housing interventions",
    knownLimitations: "Peer-reviewed literature may lag practice by 3-7 years. Community-specific adaptations may differ from study conditions. Fidelity to original context must be assessed.",
    suppressionRules: "None",
    primarySourceUrl: "https://www.bettersciencelab.com",
    citationFormat: "RPLICE, [framework], [study title], [year]",
    steward: "RPLICE Integration",
  },
  {
    id: "usaleep-life-expectancy",
    name: "USALEEP Life Expectancy at Birth",
    owner: "CDC / NCHS / HUD",
    collectionMethod: "Administrative death records + Census denominator (tract-level)",
    evidenceClass: "estimated",
    geographyLevel: "Census tract",
    timePeriod: "2010-2015 (most recent release)",
    refreshCadence: "Irregular",
    coverage: "Nationwide tracts (with suppression for small tracts)",
    knownLimitations: "Data from 2010-2015 period — does not reflect COVID-era or post-pandemic changes. Small tracts suppressed. Pre-dates significant life-expectancy decline observed post-2019.",
    suppressionRules: "Tracts with < 5 deaths suppressed",
    primarySourceUrl: "https://www.cdc.gov/nchs/nvss/usaleep/usaleep.html",
    citationFormat: "CDC USALEEP, [tract FIPS], 2010-2015",
    steward: "Equity-Loss Engine",
  },
  {
    id: "cdc-svi",
    name: "CDC/ATSDR Social Vulnerability Index",
    owner: "CDC / ATSDR",
    collectionMethod: "Composite of 16 ACS variables across 4 themes (socioeconomic, household, minority, housing/transportation)",
    evidenceClass: "modeled",
    geographyLevel: "Census tract / county",
    timePeriod: "GIS primary source: 2022; legacy fallback may have an older vintage",
    refreshCadence: "Every 2 years",
    coverage: "Nationwide",
    knownLimitations: "Composite index — individual component scores may be more informative for targeted decisions. Input data vintage is 2016-2020 ACS. Does not capture real-time conditions.",
    suppressionRules: "None — uses ACS suppression upstream",
    primarySourceUrl: "https://www.atsdr.cdc.gov/placeandhealth/svi/",
    citationFormat: "CDC/ATSDR SVI, [county/tract FIPS], 2020",
    steward: "Community Intelligence",
  },
  {
    id: "careeronestop-occupational",
    name: "CareerOneStop Occupation Data",
    owner: "U.S. Department of Labor / ETA",
    collectionMethod: "BLS Occupational Employment and Wage Statistics + local employer survey",
    evidenceClass: "estimated",
    geographyLevel: "State / MSA (not county-level for all codes)",
    timePeriod: "Annual (current: 2023)",
    refreshCadence: "Annual",
    coverage: "Nationwide, state and MSA level",
    knownLimitations: "Below-MSA demand data not available for all occupation codes. Self-employment not captured. Gig economy significantly undercounted. Rural area demand often aggregated to MSA.",
    suppressionRules: "Cells < 10 employers suppressed",
    primarySourceUrl: "https://www.careeronestop.org",
    citationFormat: "CareerOneStop, Occupation Profile, [SOC code], [state/MSA], [year]",
    steward: "Rural Workforce",
  },
  {
    id: "hhsc-ccl-childcare",
    name: "HHSC Child Care Licensing (Texas)",
    owner: "Texas Health and Human Services Commission",
    collectionMethod: "Administrative licensing records (bc5r-88dy dataset)",
    evidenceClass: "verified",
    geographyLevel: "County (Texas only)",
    timePeriod: "Real-time (updated monthly)",
    refreshCadence: "Monthly",
    coverage: "Texas only",
    knownLimitations: "Texas only. Does not include unlicensed family care arrangements. total_capacity field (not licensed_capacity) is the correct capacity field. No lat/lon coordinates in main dataset. No TRS rating field (separate dataset).",
    suppressionRules: "None",
    primarySourceUrl: "https://www.hhs.texas.gov/child-care-licensing",
    citationFormat: "Texas HHSC Child Care Licensing, [county], [month year]",
    steward: "Childcare Intelligence",
  },
  {
    id: "census-cbp-naics",
    name: "Census County Business Patterns (NAICS 6244)",
    owner: "U.S. Census Bureau",
    collectionMethod: "Administrative business records + IRS data",
    evidenceClass: "observed",
    geographyLevel: "County",
    timePeriod: "Existing importer uses 2022; not a claim of latest published release",
    refreshCadence: "Annual",
    coverage: "Nationwide",
    knownLimitations: "Does not capture informal child care arrangements. Small establishment counts suppressed (< 3 employers). 2-year lag from reference year. NAICS 6244 = Child Day Care Services.",
    suppressionRules: "Establishments with < 3 employers suppressed with a D flag",
    primarySourceUrl: "https://www.census.gov/programs-surveys/cbp.html",
    citationFormat: "Census County Business Patterns, NAICS 6244, [county FIPS], 2022",
    steward: "Childcare Intelligence",
  },
  {
    id: "hrsa-shortage-areas",
    name: "HRSA Health Professional Shortage Areas",
    owner: "Health Resources and Services Administration",
    collectionMethod: "Administrative designation based on population-to-provider ratio",
    evidenceClass: "verified",
    geographyLevel: "County / partial county / facility-based",
    timePeriod: "Current (continuously updated)",
    refreshCadence: "Continuous",
    coverage: "Nationwide",
    knownLimitations: "Designation lags actual workforce changes by 1-3 years. Does not capture telehealth capacity. HPSA types: Primary Care, Mental Health, Dental.",
    suppressionRules: "None",
    primarySourceUrl: "https://data.hrsa.gov/tools/shortage-area",
    citationFormat: "HRSA, [HPSA type] Shortage Area, [geography], [designation date]",
    steward: "Health Intelligence",
  },
  {
    id: "usda-1890-institutions",
    name: "USDA 1890 Land-Grant Institution Registry",
    owner: "U.S. Department of Agriculture / NIFA",
    collectionMethod: "Federal statutory designation (Morrill Act of 1890)",
    evidenceClass: "verified",
    geographyLevel: "Institution (nationwide)",
    timePeriod: "Current",
    refreshCadence: "As federally designated",
    coverage: "19 1890 Land-Grant Institutions + Tuskegee University + West Virginia State University",
    knownLimitations: "Covers 1890 land-grants only — does not include all HBCUs. HBCU status requires separate IPEDS verification.",
    suppressionRules: "None",
    primarySourceUrl: "https://www.nifa.usda.gov/grants/programs/1890-institution-teaching-research-extension",
    citationFormat: "USDA NIFA, 1890 Land-Grant Institution List, current",
    steward: "HBCU Opportunity Network",
  },
  {
    id: "ipeds-institutions",
    name: "NCES IPEDS Institutional Characteristics",
    owner: "National Center for Education Statistics",
    collectionMethod: "Annual mandatory institutional survey (all Title IV institutions)",
    evidenceClass: "observed",
    geographyLevel: "Institution",
    timePeriod: "Existing registry baseline: 2022-2023 academic year",
    refreshCadence: "Annual",
    coverage: "All Title IV degree-granting institutions (~6,000)",
    knownLimitations: "Completions data lags 2 years. Does not include non-Title IV programs. HBCU flag is self-reported by institution.",
    suppressionRules: "Cells < 3 students suppressed",
    primarySourceUrl: "https://nces.ed.gov/ipeds/",
    citationFormat: "NCES IPEDS, [institution name], [data year]",
    steward: "HBCU Opportunity Network",
  },
  {
    id: "platform-referral-outcomes",
    name: "TCAF Platform Referral System",
    owner: "TCAF / ISS LLC",
    collectionMethod: "Platform administrative records (referral creation, status updates, outcomes)",
    evidenceClass: "observed",
    geographyLevel: "County / organization",
    timePeriod: "Real-time (floor-5 suppressed in aggregates)",
    refreshCadence: "Real-time",
    coverage: "Platform participants only — not representative of full community population",
    knownLimitations: "Covers platform-referred individuals only. Outcome confirmation depends on partner org response rate. Self-selection bias: platform users may differ from general population.",
    suppressionRules: "Floor-5: cells < 5 participants suppressed in all aggregate outputs",
    primarySourceUrl: null,
    citationFormat: "TCAF Platform Referral System, aggregate outcomes, [date range]",
    steward: "CHW / Case Management",
  },
  {
    id: "platform-program-enrollment",
    name: "TCAF Platform Program Enrollment",
    owner: "TCAF / ISS LLC",
    collectionMethod: "Platform administrative records (enrollment, attendance, completion)",
    evidenceClass: "observed",
    geographyLevel: "County / program",
    timePeriod: "Real-time (floor-5 suppressed in aggregates)",
    refreshCadence: "Real-time",
    coverage: "Platform participants only",
    knownLimitations: "Covers platform participants only. Completion rates depend on follow-up data entry. Outcomes are self-reported unless partner-verified.",
    suppressionRules: "Floor-5 applied to all aggregate outputs",
    primarySourceUrl: null,
    citationFormat: "TCAF Platform Program Enrollment, [program name], [date range]",
    steward: "Academy / Program Management",
  },
  {
    id: "community-intelligence-submissions",
    name: "TCAF Community Intelligence Submissions",
    owner: "TCAF / ISS LLC",
    collectionMethod: "ITI-consented community member submissions via platform",
    evidenceClass: "community-reported",
    geographyLevel: "ZIP / neighborhood (submitter-specified)",
    timePeriod: "Real-time (floor-5 suppressed)",
    refreshCadence: "Continuous",
    coverage: "Community members who have completed ITI informed consent process",
    knownLimitations: "Volunteer bias — represents engaged community members, not general population. Floor-5 suppression applies. Submissions are reviewed but not independently verified.",
    suppressionRules: "Floor-5; consent toggle (community_intelligence) required; individual identity never revealed",
    primarySourceUrl: null,
    citationFormat: "TCAF Community Intelligence, [geography], [date range]",
    steward: "#DATA / Community Intelligence",
  },
  {
    id: "partner-outcome-submissions",
    name: "TCAF Partner Org Outcome Submissions (ImpactStream)",
    owner: "TCAF / ISS LLC + partner organizations",
    collectionMethod: "Partner-submitted outcome records via ImpactStream API",
    evidenceClass: "verified",
    geographyLevel: "County / organization",
    timePeriod: "Real-time (floor-5 suppressed in aggregates)",
    refreshCadence: "Per submission",
    coverage: "Organizations enrolled in ImpactStream",
    knownLimitations: "Self-reported by partner organizations. TCAF verifies against referral records where available. Non-enrolled partners not represented.",
    suppressionRules: "Floor-5 applied to all aggregate outputs",
    primarySourceUrl: null,
    citationFormat: "TCAF ImpactStream, [organization], [date range]",
    steward: "Partner / Org Management",
  },
  {
    id: "chainweb-ripple",
    name: "Chainweb Impact Verification Events",
    owner: "TCAF / ISS LLC",
    collectionMethod: "Blockchain-style verification events across 26 intelligence engines",
    evidenceClass: "modeled",
    geographyLevel: "County / organization",
    timePeriod: "Real-time",
    refreshCadence: "Real-time (per event)",
    coverage: "Platform participants and connected organizations",
    knownLimitations: "Derived from platform activity — not independently audited external data. Ripple scores are model outputs, not directly observed outcomes. Engine coverage varies by geography.",
    suppressionRules: "Floor-5 applied to aggregate displays",
    primarySourceUrl: null,
    citationFormat: "TCAF Chainweb, engine [id], [date]",
    steward: "Chainweb / Civic Signal",
  },
  {
    id: "equity-loss-engine",
    name: "TCAF Equity-Loss Engine (Three-Frame Divergence)",
    owner: "TCAF / ISS LLC",
    collectionMethod: "Three-frame divergence vs national, state, and peer-class benchmarks using ACS + USALEEP",
    evidenceClass: "modeled",
    geographyLevel: "County",
    timePeriod: "Current (ACS 2022 + USALEEP 2010-2015 base)",
    refreshCadence: "Annual (with ACS vintage refresh)",
    coverage: "Nationwide counties",
    knownLimitations: "Peer class selection is 1 representative county — not a full peer cohort. Divergence scores are relative measures, not absolute loss figures. USALEEP base is 2010-2015 and does not reflect recent changes.",
    suppressionRules: "Floor-5 for platform-derived components",
    primarySourceUrl: null,
    citationFormat: "TCAF Equity-Loss Engine, [county FIPS], [year]",
    steward: "Equity / Policy",
  },
  {
    id: "gun-violence-registry",
    name: "TCAF Gun Violence Registry",
    owner: "TCAF / ISS LLC",
    collectionMethod: "Aggregated from GVA (Gun Violence Archive), CDC WISQARS, and community submissions; daily sync",
    evidenceClass: "observed",
    geographyLevel: "County / ZIP",
    timePeriod: "2014-present (daily sync)",
    refreshCadence: "Daily",
    coverage: "Nationwide",
    knownLimitations: "GVA undercounts rural incidents due to media coverage gaps. Community submissions subject to recall bias. CDC WISQARS has 2-year lag for detailed data.",
    suppressionRules: "Floor-5 for community-submitted data components",
    primarySourceUrl: null,
    citationFormat: "TCAF Gun Violence Registry, [county], [date range]",
    steward: "Gun Violence Intelligence",
  },
  {
    id: "rplice-cfir-assessments",
    name: "RPLICE CFIR 2.0 Assessments (Platform)",
    owner: "TCAF / ISS LLC",
    collectionMethod: "Platform-administered CFIR 2.0 assessments per organization per county",
    evidenceClass: "community-reported",
    geographyLevel: "Organization / county",
    timePeriod: "Per assessment (timestamped)",
    refreshCadence: "Per assessment cycle",
    coverage: "Organizations enrolled in CFIR assessment process",
    knownLimitations: "Self-reported by organization staff. Fidelity to CFIR 2.0 instrument depends on assessor training. Point-in-time assessment — conditions change.",
    suppressionRules: "Organization-level outputs only — never individual respondent data",
    primarySourceUrl: "https://cfirguide.org",
    citationFormat: "RPLICE CFIR 2.0 Assessment, [organization], [county], [assessment date]",
    steward: "RPLICE / Implementation Science",
  },
  {
    id: "hud-chas-housing",
    name: "HUD CHAS (Comprehensive Housing Affordability Strategy)",
    owner: "U.S. Department of Housing and Urban Development",
    collectionMethod: "Custom ACS tabulations by HUD for housing affordability analysis",
    evidenceClass: "estimated",
    geographyLevel: "County / place",
    timePeriod: "Legacy baseline 2016-2020; HUD download release now includes 2018-2022",
    refreshCadence: "Every 3-5 years",
    coverage: "Nationwide",
    knownLimitations: "5-year vintage lag. Does not capture post-pandemic housing market changes. Place-level data requires separate API endpoint from county-level.",
    suppressionRules: "ACS suppression rules applied upstream",
    primarySourceUrl: "https://www.huduser.gov/portal/datasets/cp.html",
    citationFormat: "HUD CHAS, [county/place FIPS], 2016-2020",
    steward: "Housing Intelligence",
  },
] as const;

export async function seedDataSources(): Promise<void> {
  console.log(`[seed-data-sources] Seeding ${SOURCES.length} canonical data sources...`);
  let inserted = 0;
  let updated = 0;

  for (const source of SOURCES) {
    try {
      await db
        .insert(dataSources)
        .values({
          ...source,
          primarySourceUrl: source.primarySourceUrl ?? null,
          registeredAt: new Date(),
          lastReviewedAt: new Date(),
          isActive: true,
        })
        .onConflictDoUpdate({
          target: dataSources.id,
          set: {
            name: source.name,
            owner: source.owner,
            collectionMethod: source.collectionMethod,
            evidenceClass: source.evidenceClass,
            geographyLevel: source.geographyLevel,
            timePeriod: source.timePeriod,
            refreshCadence: source.refreshCadence,
            coverage: source.coverage,
            knownLimitations: source.knownLimitations ?? null,
            suppressionRules: source.suppressionRules ?? null,
            primarySourceUrl: source.primarySourceUrl ?? null,
            citationFormat: source.citationFormat ?? null,
            steward: source.steward ?? null,
            lastReviewedAt: new Date(),
          },
        });
      // Check if it was an insert or update by checking if it existed before
      inserted++;
    } catch (err) {
      console.error(`[seed-data-sources] Error seeding ${source.id}:`, err);
    }
  }

  console.log(`[seed-data-sources] Done — ${inserted} sources upserted`);
}

// CLI entry point
// The production server is bundled as CommonJS, where import.meta.url is
// undefined. Match the source entrypoint by filename instead so importing
// this module during server startup cannot throw ERR_INVALID_URL.
const isDirectSeedExecution = /(?:^|[\\/])seed-data-sources(?:\.ts|\.js)$/.test(process.argv[1] ?? "");
if (isDirectSeedExecution) {
  seedDataSources()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
