import { careerFields } from "@shared/schema";

export async function seedNonCollegiatePathways(db: any): Promise<void> {
  const newCareers = [
    {
      name: "Certified Nursing Assistant (CNA)",
      category: "Healthcare",
      description: "Provide basic patient care in hospitals, nursing homes, and assisted living facilities. Help patients with daily activities like bathing, dressing, and eating. Training takes 4-12 weeks. High demand in the Austin area with immediate job placement.",
      educationPath: "technical-certification",
      salaryRange: "$28,000 - $38,000",
      requiredSkills: ["Patient Care", "Compassion", "Communication", "Physical Stamina", "Attention to Detail"],
      relatedSubjects: ["Science", "English"],
      gradeLevel: "9-12",
      iconName: "Heart",
      sortOrder: 56,
    },
    {
      name: "Phlebotomist",
      category: "Healthcare",
      description: "Draw blood from patients for medical testing, transfusions, and donations. Work in hospitals, clinics, and blood donation centers. Certification takes 4-8 weeks. One of the fastest healthcare credentials to earn.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $42,000",
      requiredSkills: ["Venipuncture", "Patient Communication", "Attention to Detail", "Infection Control", "Steady Hands"],
      relatedSubjects: ["Science", "Math"],
      gradeLevel: "9-12",
      iconName: "Droplets",
      sortOrder: 57,
    },
    {
      name: "Medical Assistant",
      category: "Healthcare",
      description: "Perform administrative and clinical tasks in physician offices, hospitals, and clinics. Take vital signs, prepare patients for exams, schedule appointments, and manage records. Training takes 9-12 months.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $45,000",
      requiredSkills: ["Clinical Skills", "Medical Terminology", "Organization", "Patient Communication", "EHR Systems"],
      relatedSubjects: ["Science", "Math", "English", "Technology"],
      gradeLevel: "9-12",
      iconName: "Stethoscope",
      sortOrder: 58,
    },
    {
      name: "Home Health Aide",
      category: "Healthcare",
      description: "Provide in-home care for elderly, disabled, or chronically ill patients. Assist with daily living activities, monitor health conditions, and provide companionship. Training takes 2-4 weeks. Growing demand as population ages.",
      educationPath: "technical-certification",
      salaryRange: "$25,000 - $35,000",
      requiredSkills: ["Caregiving", "Patience", "Communication", "Basic Medical Knowledge", "Reliability"],
      relatedSubjects: ["Science", "English"],
      gradeLevel: "9-12",
      iconName: "Home",
      sortOrder: 59,
    },
    {
      name: "Pharmacy Technician",
      category: "Healthcare",
      description: "Assist pharmacists in dispensing medications to patients. Measure, mix, count, and label medications. Work in retail pharmacies, hospitals, and mail-order pharmacies. Certification takes 6-12 months.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $42,000",
      requiredSkills: ["Accuracy", "Pharmacy Software", "Customer Service", "Math", "Organization"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Pill",
      sortOrder: 60,
    },
    {
      name: "Dental Assistant",
      category: "Healthcare",
      description: "Work alongside dentists during procedures, prepare treatment rooms, sterilize instruments, take X-rays, and educate patients on oral care. Training takes 9-11 months.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $46,000",
      requiredSkills: ["Dental Procedures", "Infection Control", "Patient Communication", "Manual Dexterity", "Organization"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Smile",
      sortOrder: 61,
    },
    {
      name: "CompTIA A+ Technician",
      category: "Technology",
      description: "Entry-level IT certification covering hardware, software, networking, and troubleshooting. Opens doors to help desk, desktop support, and field technician roles. Study time: 3-6 months. One of the most recognized IT certifications worldwide.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $55,000",
      requiredSkills: ["Hardware Troubleshooting", "Operating Systems", "Networking Basics", "Customer Service", "Problem Solving"],
      relatedSubjects: ["Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Monitor",
      sortOrder: 62,
    },
    {
      name: "CompTIA Security+ Analyst",
      category: "Technology",
      description: "Cybersecurity certification validating skills in threat detection, risk management, and security operations. Required for many government and defense IT positions. Study time: 4-6 months. Strong demand in Austin's tech sector.",
      educationPath: "technical-certification",
      salaryRange: "$50,000 - $80,000",
      requiredSkills: ["Network Security", "Threat Analysis", "Risk Management", "Compliance", "Incident Response"],
      relatedSubjects: ["Technology", "Math", "Science"],
      gradeLevel: "9-12",
      iconName: "Shield",
      sortOrder: 63,
    },
    {
      name: "Google Career Certificate -- IT Support",
      category: "Technology",
      description: "Google-designed program teaching IT fundamentals including troubleshooting, networking, operating systems, system administration, and security. Completed in 3-6 months online. No prior experience needed. Recognized by 150+ employers.",
      educationPath: "technical-certification",
      salaryRange: "$38,000 - $58,000",
      requiredSkills: ["Customer Service", "Troubleshooting", "Networking", "Linux", "Cloud Computing"],
      relatedSubjects: ["Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Award",
      sortOrder: 64,
    },
    {
      name: "Google Career Certificate -- Data Analytics",
      category: "Technology",
      description: "Learn data cleaning, analysis, and visualization using spreadsheets, SQL, R, and Tableau. Completed in 3-6 months online. No degree required. High demand across every industry in the Austin area.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $70,000",
      requiredSkills: ["SQL", "Spreadsheets", "Data Visualization", "R Programming", "Critical Thinking"],
      relatedSubjects: ["Math", "Technology", "Science"],
      gradeLevel: "9-12",
      iconName: "BarChart",
      sortOrder: 65,
    },
    {
      name: "Google Career Certificate -- Cybersecurity",
      category: "Technology",
      description: "Learn to identify threats, protect networks, and respond to security incidents. Covers Python, Linux, SIEM tools, and IDS. Completed in 3-6 months online. No degree or experience required.",
      educationPath: "technical-certification",
      salaryRange: "$48,000 - $75,000",
      requiredSkills: ["Security Tools", "Python", "Linux", "Network Monitoring", "Incident Response"],
      relatedSubjects: ["Technology", "Math", "Science"],
      gradeLevel: "9-12",
      iconName: "Lock",
      sortOrder: 66,
    },
    {
      name: "Google Career Certificate -- UX Design",
      category: "Technology",
      description: "Learn user research, wireframing, prototyping, and usability testing. Build a professional portfolio. Completed in 3-6 months online. Combines creativity with technology -- no coding required.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $75,000",
      requiredSkills: ["User Research", "Wireframing", "Prototyping", "Visual Design", "Empathy"],
      relatedSubjects: ["Art", "Technology", "English"],
      gradeLevel: "9-12",
      iconName: "Layout",
      sortOrder: 67,
    },
    {
      name: "Google Career Certificate -- Project Management",
      category: "Technology",
      description: "Learn project planning, risk management, stakeholder communication, and agile methodology. Applicable across every industry. Completed in 3-6 months online. No degree required.",
      educationPath: "technical-certification",
      salaryRange: "$48,000 - $75,000",
      requiredSkills: ["Planning", "Communication", "Risk Management", "Agile/Scrum", "Leadership"],
      relatedSubjects: ["Math", "English", "Technology"],
      gradeLevel: "9-12",
      iconName: "ClipboardList",
      sortOrder: 68,
    },
    {
      name: "AWS Cloud Practitioner",
      category: "Technology",
      description: "Entry-level Amazon Web Services cloud certification. Learn cloud concepts, AWS services, security, and pricing. Study time: 2-4 months. Austin is a major cloud computing hub with strong demand for certified professionals.",
      educationPath: "technical-certification",
      salaryRange: "$50,000 - $80,000",
      requiredSkills: ["Cloud Computing", "AWS Services", "Security Basics", "Networking", "Problem Solving"],
      relatedSubjects: ["Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Cloud",
      sortOrder: 69,
    },
    {
      name: "CDL Truck Driver (Class A)",
      category: "Skilled Trades",
      description: "Operate tractor-trailers and large commercial vehicles to transport goods across Texas and the nation. CDL training takes 3-7 weeks. Immediate job placement with signing bonuses common. One of the fastest paths to $50K+ income.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $75,000",
      requiredSkills: ["Vehicle Operation", "Route Planning", "Safety Compliance", "Time Management", "Physical Stamina"],
      relatedSubjects: ["Math", "Technology"],
      gradeLevel: "11-12",
      iconName: "Truck",
      sortOrder: 70,
    },
    {
      name: "Forklift/Warehouse Operator",
      category: "Skilled Trades",
      description: "Operate forklifts and manage warehouse inventory, shipping, and receiving. Certification takes 1-2 days. Austin's booming e-commerce and logistics sector creates constant demand for certified operators.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $48,000",
      requiredSkills: ["Equipment Operation", "Inventory Management", "Safety Protocols", "Physical Fitness", "Organization"],
      relatedSubjects: ["Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Package",
      sortOrder: 71,
    },
    {
      name: "Cosmetologist",
      category: "Arts & Creative",
      description: "Cut, color, and style hair. Provide skin care, nail services, and makeup application. Texas requires 1,000 hours of cosmetology school (about 7-10 months). Build a clientele, work in salons, or open your own business.",
      educationPath: "trade-school",
      salaryRange: "$25,000 - $60,000+",
      requiredSkills: ["Hair Styling", "Color Theory", "Customer Service", "Creativity", "Business Skills"],
      relatedSubjects: ["Art", "Science", "English"],
      gradeLevel: "9-12",
      iconName: "Scissors",
      sortOrder: 72,
    },
    {
      name: "Barber",
      category: "Arts & Creative",
      description: "Specialize in men's hair cutting, beard trimming, and grooming. Texas requires 1,500 hours of barber school (about 10-12 months). Strong earning potential through tips, own-chair rental, or shop ownership.",
      educationPath: "trade-school",
      salaryRange: "$28,000 - $65,000+",
      requiredSkills: ["Cutting Techniques", "Customer Relations", "Sanitation", "Business Management", "Communication"],
      relatedSubjects: ["Art", "English"],
      gradeLevel: "9-12",
      iconName: "Scissors",
      sortOrder: 73,
    },
    {
      name: "Real Estate Agent",
      category: "Business & Finance",
      description: "Help people buy, sell, and rent properties. Texas requires 180 hours of pre-licensing coursework (about 2-6 months) plus passing the state exam. Commission-based income with unlimited earning potential.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $100,000+",
      requiredSkills: ["Sales", "Negotiation", "Market Analysis", "Communication", "Self-Motivation"],
      relatedSubjects: ["Math", "English", "Social Studies"],
      gradeLevel: "11-12",
      iconName: "Home",
      sortOrder: 74,
    },
    {
      name: "Insurance Agent",
      category: "Business & Finance",
      description: "Sell insurance policies for life, health, auto, home, and business coverage. Texas requires pre-licensing coursework and passing the state exam. Combination of base salary plus commission.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $80,000+",
      requiredSkills: ["Sales", "Customer Service", "Risk Assessment", "Communication", "Financial Literacy"],
      relatedSubjects: ["Math", "English", "Social Studies"],
      gradeLevel: "11-12",
      iconName: "Shield",
      sortOrder: 75,
    },
    {
      name: "Corrections Officer",
      category: "Military & Public Service",
      description: "Maintain security and order in jails and prisons. Monitor inmates, conduct searches, and respond to emergencies. Training takes 6-8 weeks at the TDCJ academy. Stable government career with benefits.",
      educationPath: "technical-certification",
      salaryRange: "$36,000 - $55,000",
      requiredSkills: ["Conflict Resolution", "Communication", "Physical Fitness", "Observation", "Report Writing"],
      relatedSubjects: ["English", "Social Studies"],
      gradeLevel: "11-12",
      iconName: "Lock",
      sortOrder: 77,
    },
    {
      name: "911 Dispatcher",
      category: "Military & Public Service",
      description: "Answer emergency calls, dispatch police, fire, and EMS units, and provide critical instructions to callers in crisis. Training takes 6-12 weeks on the job. No degree required.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $52,000",
      requiredSkills: ["Communication", "Multitasking", "Composure Under Pressure", "Typing Speed", "Decision Making"],
      relatedSubjects: ["English", "Technology"],
      gradeLevel: "11-12",
      iconName: "Phone",
      sortOrder: 78,
    },
    {
      name: "Solar Panel Installer",
      category: "Skilled Trades",
      description: "Install, maintain, and repair solar photovoltaic systems on rooftops and ground mounts. Training takes 1-4 months. Texas is one of the fastest-growing solar markets in the nation. Green energy career with strong job growth.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $55,000",
      requiredSkills: ["Electrical Basics", "Safety Protocols", "Physical Fitness", "Blueprint Reading", "Teamwork"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Sun",
      sortOrder: 79,
    },
    {
      name: "Wind Turbine Technician",
      category: "Skilled Trades",
      description: "Install, inspect, maintain, and repair wind turbines. Work at heights servicing mechanical and electrical components. Certificate programs take 6-12 months. Texas leads the nation in wind energy production.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $70,000",
      requiredSkills: ["Mechanical Skills", "Electrical Knowledge", "Heights Comfort", "Safety Protocols", "Problem Solving"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Wind",
      sortOrder: 80,
    },
    {
      name: "Electrical Lineworker",
      category: "Skilled Trades",
      description: "Install and repair electrical power lines and cables. Work for utility companies maintaining the power grid. Lineworker programs take 7-15 weeks. One of the highest-paying skilled trades with overtime opportunities.",
      educationPath: "trade-school",
      salaryRange: "$55,000 - $95,000",
      requiredSkills: ["Electrical Systems", "Heights Comfort", "Physical Fitness", "Safety Protocols", "Teamwork"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "11-12",
      iconName: "Zap",
      sortOrder: 81,
    },
    {
      name: "Semiconductor Process Technician",
      category: "Skilled Trades",
      description: "Operate and maintain equipment in semiconductor fabrication facilities. Monitor chip production processes and perform quality checks. Certificate programs take 6-12 months. Samsung, NXP, and other fabs have an established presence in the Austin area — check current job postings for hiring status, since demand fluctuates with the semiconductor market.",
      educationPath: "technical-certification",
      salaryRange: "$40,000 - $65,000",
      requiredSkills: ["Cleanroom Procedures", "Equipment Operation", "Quality Control", "Attention to Detail", "Technical Reading"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Cpu",
      sortOrder: 82,
    },
    {
      name: "Industrial Maintenance Technician",
      category: "Skilled Trades",
      description: "Maintain and repair industrial machinery and equipment in manufacturing facilities. Troubleshoot mechanical, electrical, and hydraulic systems. Certificate programs take 6-12 months. Critical role in every manufacturing plant.",
      educationPath: "technical-certification",
      salaryRange: "$42,000 - $68,000",
      requiredSkills: ["Mechanical Systems", "Electrical Troubleshooting", "Hydraulics", "Preventive Maintenance", "Safety"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Settings",
      sortOrder: 83,
    },
    {
      name: "Robotics Technician",
      category: "Skilled Trades",
      description: "Program, operate, and maintain industrial robots used in manufacturing and automation. Troubleshoot robotic systems and optimize production processes. Certificate programs take 6-18 months. Growing field as automation expands.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $72,000",
      requiredSkills: ["Robotics Programming", "Mechanical Skills", "Electrical Systems", "Problem Solving", "Computer Skills"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Cog",
      sortOrder: 84,
    },
    {
      name: "Pipefitter/Steamfitter",
      category: "Skilled Trades",
      description: "Install and maintain piping systems that carry chemicals, acids, and gases in manufacturing, power plants, and industrial facilities. Apprenticeship takes 4-5 years with paid on-the-job training from day one.",
      educationPath: "trade-school",
      salaryRange: "$48,000 - $85,000",
      requiredSkills: ["Pipe Fitting", "Blueprint Reading", "Welding", "Mathematics", "Safety Protocols"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Wrench",
      sortOrder: 85,
    },
    {
      name: "Ironworker",
      category: "Skilled Trades",
      description: "Install structural and reinforcing iron and steel for buildings, bridges, and highways. Work at heights assembling steel frameworks. Apprenticeship-based with paid training. Essential for Austin's construction boom.",
      educationPath: "trade-school",
      salaryRange: "$42,000 - $78,000",
      requiredSkills: ["Structural Assembly", "Blueprint Reading", "Welding", "Physical Fitness", "Heights Comfort"],
      relatedSubjects: ["Math", "Science"],
      gradeLevel: "9-12",
      iconName: "Hammer",
      sortOrder: 86,
    },
    {
      name: "Mason/Bricklayer",
      category: "Skilled Trades",
      description: "Build and repair walls, walkways, and other structures using brick, concrete block, and stone. Apprenticeships take 3-4 years with paid on-the-job training. Essential for residential and commercial construction.",
      educationPath: "trade-school",
      salaryRange: "$38,000 - $68,000",
      requiredSkills: ["Masonry Techniques", "Blueprint Reading", "Physical Fitness", "Precision", "Mathematics"],
      relatedSubjects: ["Math", "Art"],
      gradeLevel: "9-12",
      iconName: "Building2",
      sortOrder: 87,
    },
    {
      name: "Freelance Content Creator",
      category: "Media & Communications",
      description: "Create content for social media, YouTube, podcasts, and blogs. Build an audience and monetize through sponsorships, ads, and merchandise. No degree needed -- learn by doing. Austin is a top creator economy hub.",
      educationPath: "entrepreneurship",
      salaryRange: "$20,000 - $100,000+",
      requiredSkills: ["Content Creation", "Video Editing", "Social Media", "Marketing", "Consistency"],
      relatedSubjects: ["English", "Art", "Technology"],
      gradeLevel: "9-12",
      iconName: "Video",
      sortOrder: 88,
    },
    {
      name: "Personal Trainer / Fitness Coach",
      category: "Healthcare",
      description: "Design and lead fitness programs for individuals and groups. Earn certification through NASM, ACE, or ISSA in 3-6 months. Work in gyms, private studios, or build an online coaching business. No degree required.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $65,000+",
      requiredSkills: ["Exercise Science", "Motivation", "Communication", "Program Design", "Nutrition Basics"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Activity",
      sortOrder: 89,
    },
    {
      name: "Community Health Worker (CHW)",
      category: "Healthcare",
      description: "Serve as a bridge between communities and healthcare systems. Help people navigate resources, access care, and manage chronic conditions. Texas CHW certification takes 160 hours. TCAF and LifeBridge train and deploy CHWs across Central Texas.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $48,000",
      requiredSkills: ["Community Outreach", "Cultural Competency", "Communication", "Resource Navigation", "Empathy"],
      relatedSubjects: ["English", "Social Studies", "Science"],
      gradeLevel: "9-12",
      iconName: "Users",
      sortOrder: 90,
    },
  ];

  // Idempotent: career_fields has no unique constraint on name, so an unconditional insert on every boot
  // multiplied these rows (observed 1,564 copies each; /api/careers returned 53k rows and crashed the page).
  const existing = new Set<string>((await db.select({ name: careerFields.name }).from(careerFields)).map((r: { name: string }) => r.name));
  for (const career of newCareers) {
    if (existing.has(career.name)) continue;
    try {
      await db.insert(careerFields).values(career);
      existing.add(career.name);
    } catch (e: any) {
      if (e?.message?.includes("duplicate") || e?.code === "23505") {
        continue;
      }
      throw e;
    }
  }
}
