import { careerFields, careerMilestones } from "@shared/schema";

export async function seedCareerFields(db: any): Promise<void> {
  await db.insert(careerFields).values([
    // Technology (8)
    {
      name: "Software Developer",
      category: "Technology",
      description: "Design, build, and maintain software applications and systems that solve real-world problems. Work with programming languages, frameworks, and tools to create everything from mobile apps to enterprise platforms.",
      educationPath: "4-year-university",
      salaryRange: "$75,000 - $130,000",
      requiredSkills: ["Programming", "Problem Solving", "Software Design", "Debugging", "Teamwork"],
      relatedSubjects: ["Math", "Technology", "Science"],
      gradeLevel: "9-12",
      iconName: "Code",
      sortOrder: 1,
    },
    {
      name: "Cybersecurity Analyst",
      category: "Technology",
      description: "Protect organizations from cyber threats by monitoring networks, investigating breaches, and implementing security measures to keep data safe.",
      educationPath: "4-year-university",
      salaryRange: "$70,000 - $120,000",
      requiredSkills: ["Network Security", "Threat Analysis", "Risk Assessment", "Critical Thinking", "Attention to Detail"],
      relatedSubjects: ["Math", "Technology", "Science"],
      gradeLevel: "9-12",
      iconName: "Shield",
      sortOrder: 2,
    },
    {
      name: "Data Scientist",
      category: "Technology",
      description: "Analyze large datasets to uncover patterns, build predictive models, and help organizations make data-driven decisions using statistics and machine learning.",
      educationPath: "4-year-university",
      salaryRange: "$85,000 - $140,000",
      requiredSkills: ["Statistics", "Machine Learning", "Python/R Programming", "Data Visualization", "Critical Thinking"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "BarChart",
      sortOrder: 3,
    },
    {
      name: "Web Developer",
      category: "Technology",
      description: "Build and maintain websites and web applications, creating user-friendly interfaces and reliable back-end systems that power the internet.",
      educationPath: "community-college",
      salaryRange: "$55,000 - $100,000",
      requiredSkills: ["HTML/CSS", "JavaScript", "Responsive Design", "Problem Solving", "Creativity"],
      relatedSubjects: ["Math", "Technology", "Art"],
      gradeLevel: "9-12",
      iconName: "Globe",
      sortOrder: 4,
    },
    {
      name: "IT Support Specialist",
      category: "Technology",
      description: "Help individuals and organizations solve technology problems, set up computer systems, and ensure smooth day-to-day tech operations.",
      educationPath: "technical-certification",
      salaryRange: "$40,000 - $65,000",
      requiredSkills: ["Troubleshooting", "Customer Service", "Networking", "Hardware Knowledge", "Communication"],
      relatedSubjects: ["Technology", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Monitor",
      sortOrder: 5,
    },
    {
      name: "Cloud Engineer",
      category: "Technology",
      description: "Design and manage cloud-based infrastructure and services, helping organizations scale their technology and store data securely in the cloud.",
      educationPath: "4-year-university",
      salaryRange: "$90,000 - $150,000",
      requiredSkills: ["Cloud Platforms", "Networking", "Automation", "Security", "Problem Solving"],
      relatedSubjects: ["Math", "Technology", "Science"],
      gradeLevel: "9-12",
      iconName: "Cloud",
      sortOrder: 6,
    },
    {
      name: "Game Developer",
      category: "Technology",
      description: "Create interactive video games by designing gameplay mechanics, writing code, and collaborating with artists and designers to bring virtual worlds to life.",
      educationPath: "4-year-university",
      salaryRange: "$60,000 - $110,000",
      requiredSkills: ["Game Engines", "Programming", "3D Math", "Creativity", "Collaboration"],
      relatedSubjects: ["Math", "Technology", "Art"],
      gradeLevel: "9-12",
      iconName: "Gamepad2",
      sortOrder: 7,
    },
    {
      name: "AI/Machine Learning Engineer",
      category: "Technology",
      description: "Build intelligent systems that can learn from data, recognize patterns, and make decisions. Work on cutting-edge technology like natural language processing and computer vision.",
      educationPath: "4-year-university",
      salaryRange: "$100,000 - $170,000",
      requiredSkills: ["Machine Learning", "Python", "Mathematics", "Data Engineering", "Research"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Brain",
      sortOrder: 8,
    },
    // Healthcare (6)
    {
      name: "Registered Nurse",
      category: "Healthcare",
      description: "Provide direct patient care in hospitals, clinics, and communities. Assess patient health, administer medications, and educate patients about managing their conditions.",
      educationPath: "4-year-university",
      salaryRange: "$60,000 - $95,000",
      requiredSkills: ["Patient Care", "Critical Thinking", "Communication", "Empathy", "Medical Knowledge"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Heart",
      sortOrder: 9,
    },
    {
      name: "Medical Technologist",
      category: "Healthcare",
      description: "Perform laboratory tests on blood, tissue, and body fluids to help doctors diagnose and treat diseases. Operate sophisticated lab equipment and analyze results.",
      educationPath: "4-year-university",
      salaryRange: "$50,000 - $80,000",
      requiredSkills: ["Laboratory Skills", "Attention to Detail", "Analytical Thinking", "Biology", "Quality Control"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Microscope",
      sortOrder: 10,
    },
    {
      name: "Physical Therapist",
      category: "Healthcare",
      description: "Help patients recover from injuries and manage chronic conditions through exercise programs, manual therapy, and rehabilitation plans.",
      educationPath: "4-year-university",
      salaryRange: "$70,000 - $100,000",
      requiredSkills: ["Anatomy Knowledge", "Patient Motivation", "Exercise Science", "Communication", "Problem Solving"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Activity",
      sortOrder: 11,
    },
    {
      name: "Dental Hygienist",
      category: "Healthcare",
      description: "Clean teeth, examine patients for signs of oral diseases, and educate patients on proper oral hygiene practices to maintain dental health.",
      educationPath: "community-college",
      salaryRange: "$55,000 - $85,000",
      requiredSkills: ["Dental Procedures", "Patient Communication", "Attention to Detail", "Manual Dexterity", "Health Education"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Smile",
      sortOrder: 12,
    },
    {
      name: "EMT/Paramedic",
      category: "Healthcare",
      description: "Respond to emergency calls, provide life-saving medical care in the field, and transport patients to hospitals. Work in high-pressure situations to save lives.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $60,000",
      requiredSkills: ["Emergency Medicine", "Quick Decision Making", "Physical Fitness", "Composure Under Pressure", "Teamwork"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Siren",
      sortOrder: 13,
    },
    {
      name: "Pharmacist",
      category: "Healthcare",
      description: "Dispense prescription medications, advise patients on proper drug use and potential side effects, and collaborate with healthcare providers on treatment plans.",
      educationPath: "4-year-university",
      salaryRange: "$100,000 - $140,000",
      requiredSkills: ["Pharmacology", "Chemistry", "Patient Counseling", "Attention to Detail", "Communication"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Pill",
      sortOrder: 14,
    },
    // Business & Finance (5)
    {
      name: "Accountant",
      category: "Business & Finance",
      description: "Prepare and examine financial records, ensure taxes are paid properly, and help organizations manage their finances and budgets effectively.",
      educationPath: "4-year-university",
      salaryRange: "$55,000 - $90,000",
      requiredSkills: ["Financial Analysis", "Attention to Detail", "Mathematics", "Organization", "Software Proficiency"],
      relatedSubjects: ["Math", "English", "Technology"],
      gradeLevel: "9-12",
      iconName: "Calculator",
      sortOrder: 15,
    },
    {
      name: "Financial Advisor",
      category: "Business & Finance",
      description: "Help individuals and families plan for their financial futures by providing advice on investments, retirement planning, insurance, and wealth management.",
      educationPath: "4-year-university",
      salaryRange: "$60,000 - $120,000",
      requiredSkills: ["Financial Planning", "Communication", "Analytical Thinking", "Client Relations", "Market Knowledge"],
      relatedSubjects: ["Math", "English", "Social Studies"],
      gradeLevel: "9-12",
      iconName: "TrendingUp",
      sortOrder: 16,
    },
    {
      name: "Marketing Manager",
      category: "Business & Finance",
      description: "Develop strategies to promote products and services, manage advertising campaigns, analyze market trends, and build brand awareness.",
      educationPath: "4-year-university",
      salaryRange: "$65,000 - $110,000",
      requiredSkills: ["Strategic Thinking", "Communication", "Data Analysis", "Creativity", "Leadership"],
      relatedSubjects: ["English", "Math", "Art", "Social Studies"],
      gradeLevel: "9-12",
      iconName: "Megaphone",
      sortOrder: 17,
    },
    {
      name: "Human Resources Manager",
      category: "Business & Finance",
      description: "Manage employee relations, oversee hiring and training, ensure workplace compliance, and help create a positive and productive work environment.",
      educationPath: "4-year-university",
      salaryRange: "$60,000 - $100,000",
      requiredSkills: ["Communication", "Conflict Resolution", "Organization", "Employment Law", "Empathy"],
      relatedSubjects: ["English", "Social Studies", "Math"],
      gradeLevel: "9-12",
      iconName: "Users",
      sortOrder: 18,
    },
    {
      name: "Small Business Owner",
      category: "Business & Finance",
      description: "Start and run your own business, managing everything from product development and marketing to finances and customer service to build something from the ground up.",
      educationPath: "entrepreneurship",
      salaryRange: "$30,000 - $150,000+",
      requiredSkills: ["Leadership", "Financial Management", "Marketing", "Problem Solving", "Resilience"],
      relatedSubjects: ["Math", "English", "Social Studies", "Technology"],
      gradeLevel: "9-12",
      iconName: "Store",
      sortOrder: 19,
    },
    // Engineering (5)
    {
      name: "Mechanical Engineer",
      category: "Engineering",
      description: "Design, develop, and test mechanical devices and systems such as engines, machines, and manufacturing equipment using principles of physics and materials science.",
      educationPath: "4-year-university",
      salaryRange: "$70,000 - $110,000",
      requiredSkills: ["CAD Software", "Physics", "Problem Solving", "Mathematics", "Project Management"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Wrench",
      sortOrder: 20,
    },
    {
      name: "Civil Engineer",
      category: "Engineering",
      description: "Plan, design, and oversee the construction of infrastructure projects like roads, bridges, buildings, and water systems that communities depend on.",
      educationPath: "4-year-university",
      salaryRange: "$65,000 - $105,000",
      requiredSkills: ["Structural Analysis", "Project Management", "CAD Software", "Mathematics", "Communication"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Building2",
      sortOrder: 21,
    },
    {
      name: "Electrical Engineer",
      category: "Engineering",
      description: "Design and develop electrical systems, electronics, and power generation equipment. Work on everything from circuit boards to large-scale power grids.",
      educationPath: "4-year-university",
      salaryRange: "$70,000 - $115,000",
      requiredSkills: ["Circuit Design", "Electronics", "Mathematics", "Problem Solving", "Technical Writing"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Zap",
      sortOrder: 22,
    },
    {
      name: "Aerospace Engineer",
      category: "Engineering",
      description: "Design aircraft, spacecraft, satellites, and missiles. Test prototypes and develop new technologies for aviation and space exploration.",
      educationPath: "4-year-university",
      salaryRange: "$80,000 - $130,000",
      requiredSkills: ["Aerodynamics", "Mathematics", "Computer Modeling", "Physics", "Attention to Detail"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Rocket",
      sortOrder: 23,
    },
    {
      name: "Environmental Engineer",
      category: "Engineering",
      description: "Develop solutions to environmental problems such as pollution, waste management, and water quality. Design systems that protect both people and the planet.",
      educationPath: "4-year-university",
      salaryRange: "$65,000 - $105,000",
      requiredSkills: ["Environmental Science", "Data Analysis", "Project Management", "Regulatory Knowledge", "Problem Solving"],
      relatedSubjects: ["Science", "Math", "Technology", "Social Studies"],
      gradeLevel: "9-12",
      iconName: "Leaf",
      sortOrder: 24,
    },
    // Skilled Trades (8)
    {
      name: "Electrician",
      category: "Skilled Trades",
      description: "Install, maintain, and repair electrical wiring, equipment, and fixtures in homes, businesses, and industrial settings. Ensure all work meets safety codes.",
      educationPath: "trade-school",
      salaryRange: "$45,000 - $80,000",
      requiredSkills: ["Electrical Systems", "Blueprint Reading", "Safety Protocols", "Problem Solving", "Physical Fitness"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Plug",
      sortOrder: 25,
    },
    {
      name: "Plumber",
      category: "Skilled Trades",
      description: "Install and repair piping systems for water, gas, and drainage in residential and commercial buildings. Read blueprints and ensure compliance with building codes.",
      educationPath: "trade-school",
      salaryRange: "$45,000 - $80,000",
      requiredSkills: ["Pipe Fitting", "Blueprint Reading", "Problem Solving", "Physical Stamina", "Customer Service"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Droplets",
      sortOrder: 26,
    },
    {
      name: "HVAC Technician",
      category: "Skilled Trades",
      description: "Install, maintain, and repair heating, ventilation, air conditioning, and refrigeration systems in homes and commercial buildings.",
      educationPath: "trade-school",
      salaryRange: "$42,000 - $75,000",
      requiredSkills: ["HVAC Systems", "Electrical Knowledge", "Troubleshooting", "Customer Service", "Physical Fitness"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Thermometer",
      sortOrder: 27,
    },
    {
      name: "Welder",
      category: "Skilled Trades",
      description: "Join metal parts together using various welding techniques. Work in manufacturing, construction, and repair industries on projects from pipelines to skyscrapers.",
      educationPath: "technical-certification",
      salaryRange: "$40,000 - $70,000",
      requiredSkills: ["Welding Techniques", "Blueprint Reading", "Metal Working", "Safety Awareness", "Precision"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Flame",
      sortOrder: 28,
    },
    {
      name: "Automotive Technician",
      category: "Skilled Trades",
      description: "Diagnose, repair, and maintain vehicles including cars, trucks, and specialty vehicles. Use diagnostic equipment and technical knowledge to keep vehicles running safely.",
      educationPath: "technical-certification",
      salaryRange: "$38,000 - $65,000",
      requiredSkills: ["Diagnostics", "Mechanical Systems", "Electrical Systems", "Problem Solving", "Customer Service"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Car",
      sortOrder: 29,
    },
    {
      name: "Carpenter",
      category: "Skilled Trades",
      description: "Build, install, and repair structures and fixtures made of wood and other materials. Work on everything from framing houses to crafting custom furniture.",
      educationPath: "trade-school",
      salaryRange: "$40,000 - $70,000",
      requiredSkills: ["Woodworking", "Blueprint Reading", "Measurement", "Physical Fitness", "Attention to Detail"],
      relatedSubjects: ["Math", "Technology", "Art"],
      gradeLevel: "9-12",
      iconName: "Hammer",
      sortOrder: 30,
    },
    {
      name: "Heavy Equipment Operator",
      category: "Skilled Trades",
      description: "Operate large machinery such as bulldozers, cranes, excavators, and loaders for construction, mining, and infrastructure projects.",
      educationPath: "technical-certification",
      salaryRange: "$42,000 - $72,000",
      requiredSkills: ["Equipment Operation", "Safety Protocols", "Spatial Awareness", "Mechanical Knowledge", "Communication"],
      relatedSubjects: ["Math", "Technology", "Science"],
      gradeLevel: "9-12",
      iconName: "Truck",
      sortOrder: 31,
    },
    {
      name: "CNC Machinist",
      category: "Skilled Trades",
      description: "Program and operate computer-controlled machines to cut, shape, and finish metal and plastic parts with extreme precision for manufacturing and aerospace industries.",
      educationPath: "technical-certification",
      salaryRange: "$42,000 - $70,000",
      requiredSkills: ["CNC Programming", "Blueprint Reading", "Precision Measurement", "Mathematics", "Quality Control"],
      relatedSubjects: ["Math", "Technology", "Science"],
      gradeLevel: "9-12",
      iconName: "Settings",
      sortOrder: 32,
    },
    // Military & Public Service (5)
    {
      name: "Military Officer",
      category: "Military & Public Service",
      description: "Lead and manage military personnel, plan operations, and ensure the defense and security of the nation. Serve in branches such as Army, Navy, Air Force, or Marines.",
      educationPath: "military",
      salaryRange: "$45,000 - $120,000",
      requiredSkills: ["Leadership", "Strategic Planning", "Physical Fitness", "Decision Making", "Discipline"],
      relatedSubjects: ["Social Studies", "Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Shield",
      sortOrder: 33,
    },
    {
      name: "Firefighter",
      category: "Military & Public Service",
      description: "Respond to fires and other emergencies, rescue people from dangerous situations, and educate communities about fire safety and prevention.",
      educationPath: "technical-certification",
      salaryRange: "$40,000 - $75,000",
      requiredSkills: ["Emergency Response", "Physical Fitness", "Teamwork", "Problem Solving", "First Aid"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Flame",
      sortOrder: 34,
    },
    {
      name: "Police Officer",
      category: "Military & Public Service",
      description: "Protect communities by enforcing laws, responding to emergencies, investigating crimes, and building relationships with the people they serve.",
      educationPath: "community-college",
      salaryRange: "$45,000 - $80,000",
      requiredSkills: ["Communication", "Conflict Resolution", "Physical Fitness", "Critical Thinking", "Community Relations"],
      relatedSubjects: ["Social Studies", "English", "Science"],
      gradeLevel: "9-12",
      iconName: "BadgeCheck",
      sortOrder: 35,
    },
    {
      name: "Intelligence Analyst",
      category: "Military & Public Service",
      description: "Collect and analyze information to identify threats to national security. Work for government agencies to help leaders make informed decisions.",
      educationPath: "4-year-university",
      salaryRange: "$55,000 - $100,000",
      requiredSkills: ["Analytical Thinking", "Research", "Attention to Detail", "Communication", "Foreign Languages"],
      relatedSubjects: ["Social Studies", "English", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Search",
      sortOrder: 36,
    },
    {
      name: "Air Traffic Controller",
      category: "Military & Public Service",
      description: "Direct aircraft movements on the ground and in the air, ensuring safe distances between planes and managing the flow of air traffic at airports.",
      educationPath: "technical-certification",
      salaryRange: "$70,000 - $130,000",
      requiredSkills: ["Spatial Awareness", "Quick Decision Making", "Communication", "Concentration", "Stress Management"],
      relatedSubjects: ["Math", "Science", "Technology", "English"],
      gradeLevel: "9-12",
      iconName: "Plane",
      sortOrder: 37,
    },
    // Arts & Creative (4)
    {
      name: "Graphic Designer",
      category: "Arts & Creative",
      description: "Create visual concepts using computer software or by hand to communicate ideas that inspire, inform, or captivate consumers through logos, layouts, and digital media.",
      educationPath: "community-college",
      salaryRange: "$45,000 - $75,000",
      requiredSkills: ["Adobe Creative Suite", "Typography", "Color Theory", "Creativity", "Communication"],
      relatedSubjects: ["Art", "Technology", "English"],
      gradeLevel: "9-12",
      iconName: "Palette",
      sortOrder: 38,
    },
    {
      name: "Animator/3D Artist",
      category: "Arts & Creative",
      description: "Create moving images and three-dimensional models for films, video games, television, and digital media using specialized software and artistic skills.",
      educationPath: "4-year-university",
      salaryRange: "$50,000 - $90,000",
      requiredSkills: ["3D Modeling", "Animation Software", "Storytelling", "Artistic Ability", "Attention to Detail"],
      relatedSubjects: ["Art", "Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Film",
      sortOrder: 39,
    },
    {
      name: "Interior Designer",
      category: "Arts & Creative",
      description: "Plan and design interior spaces that are functional, safe, and aesthetically pleasing. Select materials, colors, and furniture to transform rooms and buildings.",
      educationPath: "4-year-university",
      salaryRange: "$45,000 - $80,000",
      requiredSkills: ["Space Planning", "Color Theory", "CAD Software", "Client Communication", "Creativity"],
      relatedSubjects: ["Art", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Home",
      sortOrder: 40,
    },
    {
      name: "Musician/Music Producer",
      category: "Arts & Creative",
      description: "Create, perform, and produce music across genres. Work in studios, live venues, and digital platforms to compose, record, mix, and distribute original music.",
      educationPath: "community-college",
      salaryRange: "$30,000 - $80,000",
      requiredSkills: ["Musical Ability", "Audio Engineering", "Creativity", "Collaboration", "Technology Skills"],
      relatedSubjects: ["Art", "Technology", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Music",
      sortOrder: 41,
    },
    // Education (3)
    {
      name: "Teacher",
      category: "Education",
      description: "Educate and inspire students by developing lesson plans, delivering instruction, assessing student progress, and creating supportive learning environments.",
      educationPath: "4-year-university",
      salaryRange: "$45,000 - $75,000",
      requiredSkills: ["Communication", "Patience", "Curriculum Development", "Classroom Management", "Creativity"],
      relatedSubjects: ["English", "Math", "Science", "Social Studies"],
      gradeLevel: "9-12",
      iconName: "GraduationCap",
      sortOrder: 42,
    },
    {
      name: "School Counselor",
      category: "Education",
      description: "Support students' academic, career, and social-emotional development. Help students navigate challenges, plan for college, and build coping skills.",
      educationPath: "4-year-university",
      salaryRange: "$50,000 - $80,000",
      requiredSkills: ["Counseling", "Empathy", "Communication", "Problem Solving", "Cultural Awareness"],
      relatedSubjects: ["English", "Social Studies", "Science"],
      gradeLevel: "9-12",
      iconName: "HeartHandshake",
      sortOrder: 43,
    },
    {
      name: "Instructional Designer",
      category: "Education",
      description: "Create educational materials and training programs using learning theory and technology. Design engaging courses for schools, corporations, and online platforms.",
      educationPath: "4-year-university",
      salaryRange: "$55,000 - $90,000",
      requiredSkills: ["Curriculum Design", "E-Learning Tools", "Communication", "Project Management", "Creativity"],
      relatedSubjects: ["English", "Technology", "Art"],
      gradeLevel: "9-12",
      iconName: "BookOpen",
      sortOrder: 44,
    },
    // Law & Justice (3)
    {
      name: "Lawyer",
      category: "Law & Justice",
      description: "Represent and advise clients on legal matters, prepare legal documents, argue cases in court, and advocate for justice in criminal, civil, and corporate law.",
      educationPath: "4-year-university",
      salaryRange: "$70,000 - $160,000",
      requiredSkills: ["Legal Research", "Public Speaking", "Critical Thinking", "Writing", "Negotiation"],
      relatedSubjects: ["English", "Social Studies", "Math"],
      gradeLevel: "9-12",
      iconName: "Scale",
      sortOrder: 45,
    },
    {
      name: "Paralegal",
      category: "Law & Justice",
      description: "Assist lawyers by conducting legal research, organizing case files, drafting documents, and helping prepare for trials and hearings.",
      educationPath: "community-college",
      salaryRange: "$40,000 - $65,000",
      requiredSkills: ["Legal Research", "Writing", "Organization", "Attention to Detail", "Communication"],
      relatedSubjects: ["English", "Social Studies", "Technology"],
      gradeLevel: "9-12",
      iconName: "FileText",
      sortOrder: 46,
    },
    {
      name: "Forensic Scientist",
      category: "Law & Justice",
      description: "Collect and analyze physical evidence from crime scenes using scientific methods. Help solve crimes by examining DNA, fingerprints, and other trace evidence.",
      educationPath: "4-year-university",
      salaryRange: "$50,000 - $85,000",
      requiredSkills: ["Laboratory Skills", "Analytical Thinking", "Attention to Detail", "Scientific Method", "Report Writing"],
      relatedSubjects: ["Science", "Math", "English", "Technology"],
      gradeLevel: "9-12",
      iconName: "Fingerprint",
      sortOrder: 47,
    },
    // Science & Research (3)
    {
      name: "Research Scientist",
      category: "Science & Research",
      description: "Conduct experiments and investigations to advance scientific knowledge. Work in laboratories, universities, or research institutions to make discoveries that benefit society.",
      educationPath: "4-year-university",
      salaryRange: "$65,000 - $110,000",
      requiredSkills: ["Research Methods", "Data Analysis", "Scientific Writing", "Critical Thinking", "Laboratory Skills"],
      relatedSubjects: ["Science", "Math", "English", "Technology"],
      gradeLevel: "9-12",
      iconName: "FlaskConical",
      sortOrder: 48,
    },
    {
      name: "Environmental Scientist",
      category: "Science & Research",
      description: "Study the environment and develop solutions to environmental problems. Conduct field research, analyze samples, and advise on land use and conservation policies.",
      educationPath: "4-year-university",
      salaryRange: "$55,000 - $90,000",
      requiredSkills: ["Environmental Analysis", "Field Research", "Data Collection", "Report Writing", "GIS Software"],
      relatedSubjects: ["Science", "Math", "Social Studies", "Technology"],
      gradeLevel: "9-12",
      iconName: "TreePine",
      sortOrder: 49,
    },
    {
      name: "Biotechnologist",
      category: "Science & Research",
      description: "Apply biological systems and organisms to develop new products, technologies, and medicines. Work in pharmaceuticals, agriculture, and medical research.",
      educationPath: "4-year-university",
      salaryRange: "$60,000 - $100,000",
      requiredSkills: ["Molecular Biology", "Lab Techniques", "Data Analysis", "Problem Solving", "Research"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Dna",
      sortOrder: 50,
    },
    // Media & Communications (3)
    {
      name: "Journalist",
      category: "Media & Communications",
      description: "Research, investigate, and report news stories for newspapers, magazines, websites, television, and radio. Interview sources and present information to the public.",
      educationPath: "4-year-university",
      salaryRange: "$40,000 - $70,000",
      requiredSkills: ["Writing", "Interviewing", "Research", "Critical Thinking", "Deadline Management"],
      relatedSubjects: ["English", "Social Studies", "Technology"],
      gradeLevel: "9-12",
      iconName: "Newspaper",
      sortOrder: 51,
    },
    {
      name: "Video Producer",
      category: "Media & Communications",
      description: "Plan, shoot, and edit video content for television, streaming platforms, social media, and corporate communications. Manage all aspects of video production.",
      educationPath: "4-year-university",
      salaryRange: "$45,000 - $85,000",
      requiredSkills: ["Video Editing", "Storytelling", "Camera Operation", "Project Management", "Creativity"],
      relatedSubjects: ["Art", "Technology", "English"],
      gradeLevel: "9-12",
      iconName: "Video",
      sortOrder: 52,
    },
    {
      name: "Social Media Manager",
      category: "Media & Communications",
      description: "Develop and execute social media strategies for brands and organizations. Create content, engage with audiences, and analyze performance metrics.",
      educationPath: "community-college",
      salaryRange: "$40,000 - $75,000",
      requiredSkills: ["Content Creation", "Analytics", "Communication", "Trend Awareness", "Strategy"],
      relatedSubjects: ["English", "Art", "Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Share2",
      sortOrder: 53,
    },
    // Agriculture & Environment (2)
    {
      name: "Agricultural Engineer",
      category: "Agriculture & Environment",
      description: "Design agricultural equipment, structures, and processes to improve farming efficiency. Develop solutions for food production, water management, and sustainable agriculture.",
      educationPath: "4-year-university",
      salaryRange: "$60,000 - $95,000",
      requiredSkills: ["Engineering Design", "Biology", "Problem Solving", "Mathematics", "Environmental Awareness"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Wheat",
      sortOrder: 54,
    },
    {
      name: "Veterinary Technician",
      category: "Agriculture & Environment",
      description: "Assist veterinarians in caring for animals by performing medical tests, administering medications, taking X-rays, and providing nursing care to animal patients.",
      educationPath: "community-college",
      salaryRange: "$30,000 - $50,000",
      requiredSkills: ["Animal Care", "Medical Procedures", "Communication", "Empathy", "Attention to Detail"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "PawPrint",
      sortOrder: 55,
    },
    // ==================== NON-COLLEGIATE PATHWAYS ====================
    // Healthcare — No Degree Required
    {
      name: "Certified Nursing Assistant (CNA)",
      category: "Healthcare",
      description: "Provide basic patient care in hospitals, nursing homes, and assisted living facilities. Help patients with daily activities like bathing, dressing, and eating. Training takes 4-12 weeks. High demand in the Austin area with immediate job placement.",
      educationPath: "technical-certification",
      salaryRange: "$28,000 - $38,000",
      requiredSkills: ["Patient Care", "Compassion", "Communication", "Physical Stamina", "Attention to Detail"],
      relatedSubjects: ["Science", "English"],
      gradeLevel: "9-12",
      iconName: "Heart",
      sortOrder: 56,
    },
    {
      name: "Phlebotomist",
      category: "Healthcare",
      description: "Draw blood from patients for medical testing, transfusions, and donations. Work in hospitals, clinics, and blood donation centers. Certification takes 4-8 weeks. One of the fastest healthcare credentials to earn.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $42,000",
      requiredSkills: ["Venipuncture", "Patient Communication", "Attention to Detail", "Infection Control", "Steady Hands"],
      relatedSubjects: ["Science", "Math"],
      gradeLevel: "9-12",
      iconName: "Droplets",
      sortOrder: 57,
    },
    {
      name: "Medical Assistant",
      category: "Healthcare",
      description: "Perform administrative and clinical tasks in physician offices, hospitals, and clinics. Take vital signs, prepare patients for exams, schedule appointments, and manage records. Training takes 9-12 months.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $45,000",
      requiredSkills: ["Clinical Skills", "Medical Terminology", "Organization", "Patient Communication", "EHR Systems"],
      relatedSubjects: ["Science", "Math", "English", "Technology"],
      gradeLevel: "9-12",
      iconName: "Stethoscope",
      sortOrder: 58,
    },
    {
      name: "Home Health Aide",
      category: "Healthcare",
      description: "Provide in-home care for elderly, disabled, or chronically ill patients. Assist with daily living activities, monitor health conditions, and provide companionship. Training takes 2-4 weeks. Growing demand as population ages.",
      educationPath: "technical-certification",
      salaryRange: "$25,000 - $35,000",
      requiredSkills: ["Caregiving", "Patience", "Communication", "Basic Medical Knowledge", "Reliability"],
      relatedSubjects: ["Science", "English"],
      gradeLevel: "9-12",
      iconName: "Home",
      sortOrder: 59,
    },
    {
      name: "Pharmacy Technician",
      category: "Healthcare",
      description: "Assist pharmacists in dispensing medications to patients. Measure, mix, count, and label medications. Work in retail pharmacies, hospitals, and mail-order pharmacies. Certification takes 6-12 months.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $42,000",
      requiredSkills: ["Accuracy", "Pharmacy Software", "Customer Service", "Math", "Organization"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Pill",
      sortOrder: 60,
    },
    {
      name: "Dental Assistant",
      category: "Healthcare",
      description: "Work alongside dentists during procedures, prepare treatment rooms, sterilize instruments, take X-rays, and educate patients on oral care. Training takes 9-11 months.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $46,000",
      requiredSkills: ["Dental Procedures", "Infection Control", "Patient Communication", "Manual Dexterity", "Organization"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Smile",
      sortOrder: 61,
    },
    // Technology — Certification-Based (No Degree)
    {
      name: "CompTIA A+ Technician",
      category: "Technology",
      description: "Entry-level IT certification covering hardware, software, networking, and troubleshooting. Opens doors to help desk, desktop support, and field technician roles. Study time: 3-6 months. One of the most recognized IT certifications worldwide.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $55,000",
      requiredSkills: ["Hardware Troubleshooting", "Operating Systems", "Networking Basics", "Customer Service", "Problem Solving"],
      relatedSubjects: ["Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Monitor",
      sortOrder: 62,
    },
    {
      name: "CompTIA Security+ Analyst",
      category: "Technology",
      description: "Cybersecurity certification validating skills in threat detection, risk management, and security operations. Required for many government and defense IT positions. Study time: 4-6 months. Strong demand in Austin's tech sector.",
      educationPath: "technical-certification",
      salaryRange: "$50,000 - $80,000",
      requiredSkills: ["Network Security", "Threat Analysis", "Risk Management", "Compliance", "Incident Response"],
      relatedSubjects: ["Technology", "Math", "Science"],
      gradeLevel: "9-12",
      iconName: "Shield",
      sortOrder: 63,
    },
    {
      name: "Google Career Certificate — IT Support",
      category: "Technology",
      description: "Google-designed program teaching IT fundamentals including troubleshooting, networking, operating systems, system administration, and security. Completed in 3-6 months online. No prior experience needed. Recognized by 150+ employers.",
      educationPath: "technical-certification",
      salaryRange: "$38,000 - $58,000",
      requiredSkills: ["Customer Service", "Troubleshooting", "Networking", "Linux", "Cloud Computing"],
      relatedSubjects: ["Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Award",
      sortOrder: 64,
    },
    {
      name: "Google Career Certificate — Data Analytics",
      category: "Technology",
      description: "Learn data cleaning, analysis, and visualization using spreadsheets, SQL, R, and Tableau. Completed in 3-6 months online. No degree required. High demand across every industry in the Austin area.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $70,000",
      requiredSkills: ["SQL", "Spreadsheets", "Data Visualization", "R Programming", "Critical Thinking"],
      relatedSubjects: ["Math", "Technology", "Science"],
      gradeLevel: "9-12",
      iconName: "BarChart",
      sortOrder: 65,
    },
    {
      name: "Google Career Certificate — Cybersecurity",
      category: "Technology",
      description: "Learn to identify threats, protect networks, and respond to security incidents. Covers Python, Linux, SIEM tools, and IDS. Completed in 3-6 months online. No degree or experience required.",
      educationPath: "technical-certification",
      salaryRange: "$48,000 - $75,000",
      requiredSkills: ["Security Tools", "Python", "Linux", "Network Monitoring", "Incident Response"],
      relatedSubjects: ["Technology", "Math", "Science"],
      gradeLevel: "9-12",
      iconName: "Lock",
      sortOrder: 66,
    },
    {
      name: "Google Career Certificate — UX Design",
      category: "Technology",
      description: "Learn user research, wireframing, prototyping, and usability testing. Build a professional portfolio. Completed in 3-6 months online. Combines creativity with technology — no coding required.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $75,000",
      requiredSkills: ["User Research", "Wireframing", "Prototyping", "Visual Design", "Empathy"],
      relatedSubjects: ["Art", "Technology", "English"],
      gradeLevel: "9-12",
      iconName: "Layout",
      sortOrder: 67,
    },
    {
      name: "Google Career Certificate — Project Management",
      category: "Technology",
      description: "Learn project planning, risk management, stakeholder communication, and agile methodology. Applicable across every industry. Completed in 3-6 months online. No degree required.",
      educationPath: "technical-certification",
      salaryRange: "$48,000 - $75,000",
      requiredSkills: ["Planning", "Communication", "Risk Management", "Agile/Scrum", "Leadership"],
      relatedSubjects: ["Math", "English", "Technology"],
      gradeLevel: "9-12",
      iconName: "ClipboardList",
      sortOrder: 68,
    },
    {
      name: "AWS Cloud Practitioner",
      category: "Technology",
      description: "Entry-level Amazon Web Services cloud certification. Learn cloud concepts, AWS services, security, and pricing. Study time: 2-4 months. Austin is a major cloud computing hub with strong demand for certified professionals.",
      educationPath: "technical-certification",
      salaryRange: "$50,000 - $80,000",
      requiredSkills: ["Cloud Computing", "AWS Services", "Security Basics", "Networking", "Problem Solving"],
      relatedSubjects: ["Technology", "Math"],
      gradeLevel: "9-12",
      iconName: "Cloud",
      sortOrder: 69,
    },
    // CDL & Transportation
    {
      name: "CDL Truck Driver (Class A)",
      category: "Skilled Trades",
      description: "Operate tractor-trailers and large commercial vehicles to transport goods across Texas and the nation. CDL training takes 3-7 weeks. Immediate job placement with signing bonuses common. One of the fastest paths to $50K+ income.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $75,000",
      requiredSkills: ["Vehicle Operation", "Route Planning", "Safety Compliance", "Time Management", "Physical Stamina"],
      relatedSubjects: ["Math", "Technology"],
      gradeLevel: "11-12",
      iconName: "Truck",
      sortOrder: 70,
    },
    {
      name: "Forklift/Warehouse Operator",
      category: "Skilled Trades",
      description: "Operate forklifts and manage warehouse inventory, shipping, and receiving. Certification takes 1-2 days. Austin's booming e-commerce and logistics sector creates constant demand for certified operators.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $48,000",
      requiredSkills: ["Equipment Operation", "Inventory Management", "Safety Protocols", "Physical Fitness", "Organization"],
      relatedSubjects: ["Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Package",
      sortOrder: 71,
    },
    // Licensed Professions (No Degree)
    {
      name: "Cosmetologist",
      category: "Arts & Creative",
      description: "Cut, color, and style hair. Provide skin care, nail services, and makeup application. Texas requires 1,000 hours of cosmetology school (about 7-10 months). Build a clientele, work in salons, or open your own business.",
      educationPath: "trade-school",
      salaryRange: "$25,000 - $60,000+",
      requiredSkills: ["Hair Styling", "Color Theory", "Customer Service", "Creativity", "Business Skills"],
      relatedSubjects: ["Art", "Science", "English"],
      gradeLevel: "9-12",
      iconName: "Scissors",
      sortOrder: 72,
    },
    {
      name: "Barber",
      category: "Arts & Creative",
      description: "Specialize in men's hair cutting, beard trimming, and grooming. Texas requires 1,500 hours of barber school (about 10-12 months). Strong earning potential through tips, own-chair rental, or shop ownership.",
      educationPath: "trade-school",
      salaryRange: "$28,000 - $65,000+",
      requiredSkills: ["Cutting Techniques", "Customer Relations", "Sanitation", "Business Management", "Communication"],
      relatedSubjects: ["Art", "English"],
      gradeLevel: "9-12",
      iconName: "Scissors",
      sortOrder: 73,
    },
    {
      name: "Real Estate Agent",
      category: "Business & Finance",
      description: "Help people buy, sell, and rent properties. Texas requires 180 hours of pre-licensing coursework (about 2-6 months) plus passing the state exam. Commission-based income with unlimited earning potential.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $100,000+",
      requiredSkills: ["Sales", "Negotiation", "Market Analysis", "Communication", "Self-Motivation"],
      relatedSubjects: ["Math", "English", "Social Studies"],
      gradeLevel: "11-12",
      iconName: "Home",
      sortOrder: 74,
    },
    {
      name: "Insurance Agent",
      category: "Business & Finance",
      description: "Sell insurance policies for life, health, auto, home, and business coverage. Texas requires pre-licensing coursework and passing the state exam. Combination of base salary plus commission.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $80,000+",
      requiredSkills: ["Sales", "Customer Service", "Risk Assessment", "Communication", "Financial Literacy"],
      relatedSubjects: ["Math", "English", "Social Studies"],
      gradeLevel: "11-12",
      iconName: "Shield",
      sortOrder: 75,
    },
    // Public Safety (No Degree)
    {
      name: "Fire Academy Firefighter",
      category: "Military & Public Service",
      description: "Complete fire academy training (12-16 weeks) to respond to fires, medical emergencies, and hazardous situations. Austin and surrounding departments offer competitive pay, benefits, and retirement. No degree required.",
      educationPath: "technical-certification",
      salaryRange: "$42,000 - $78,000",
      requiredSkills: ["Physical Fitness", "Emergency Response", "Teamwork", "Problem Solving", "First Aid"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "11-12",
      iconName: "Flame",
      sortOrder: 76,
    },
    {
      name: "Corrections Officer",
      category: "Military & Public Service",
      description: "Maintain security and order in jails and prisons. Monitor inmates, conduct searches, and respond to emergencies. Training takes 6-8 weeks at the TDCJ academy. Stable government career with benefits.",
      educationPath: "technical-certification",
      salaryRange: "$36,000 - $55,000",
      requiredSkills: ["Conflict Resolution", "Communication", "Physical Fitness", "Observation", "Report Writing"],
      relatedSubjects: ["English", "Social Studies"],
      gradeLevel: "11-12",
      iconName: "Lock",
      sortOrder: 77,
    },
    {
      name: "911 Dispatcher",
      category: "Military & Public Service",
      description: "Answer emergency calls, dispatch police, fire, and EMS units, and provide critical instructions to callers in crisis. Training takes 6-12 weeks on the job. No degree required.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $52,000",
      requiredSkills: ["Communication", "Multitasking", "Composure Under Pressure", "Typing Speed", "Decision Making"],
      relatedSubjects: ["English", "Technology"],
      gradeLevel: "11-12",
      iconName: "Phone",
      sortOrder: 78,
    },
    // Energy Sector
    {
      name: "Solar Panel Installer",
      category: "Skilled Trades",
      description: "Install, maintain, and repair solar photovoltaic systems on rooftops and ground mounts. Training takes 1-4 months. Texas is one of the fastest-growing solar markets in the nation. Green energy career with strong job growth.",
      educationPath: "technical-certification",
      salaryRange: "$35,000 - $55,000",
      requiredSkills: ["Electrical Basics", "Safety Protocols", "Physical Fitness", "Blueprint Reading", "Teamwork"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Sun",
      sortOrder: 79,
    },
    {
      name: "Wind Turbine Technician",
      category: "Skilled Trades",
      description: "Install, inspect, maintain, and repair wind turbines. Work at heights servicing mechanical and electrical components. Certificate programs take 6-12 months. Texas leads the nation in wind energy production.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $70,000",
      requiredSkills: ["Mechanical Skills", "Electrical Knowledge", "Heights Comfort", "Safety Protocols", "Problem Solving"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Wind",
      sortOrder: 80,
    },
    {
      name: "Electrical Lineworker",
      category: "Skilled Trades",
      description: "Install and repair electrical power lines and cables. Work for utility companies maintaining the power grid. Lineworker programs take 7-15 weeks. One of the highest-paying skilled trades with overtime opportunities.",
      educationPath: "trade-school",
      salaryRange: "$55,000 - $95,000",
      requiredSkills: ["Electrical Systems", "Heights Comfort", "Physical Fitness", "Safety Protocols", "Teamwork"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "11-12",
      iconName: "Zap",
      sortOrder: 81,
    },
    // Manufacturing & Industrial
    {
      name: "Semiconductor Process Technician",
      category: "Skilled Trades",
      description: "Operate and maintain equipment in semiconductor fabrication facilities. Monitor chip production processes and perform quality checks. Certificate programs take 6-12 months. Samsung, NXP, and other fabs in the Austin area are hiring heavily.",
      educationPath: "technical-certification",
      salaryRange: "$40,000 - $65,000",
      requiredSkills: ["Cleanroom Procedures", "Equipment Operation", "Quality Control", "Attention to Detail", "Technical Reading"],
      relatedSubjects: ["Science", "Math", "Technology"],
      gradeLevel: "9-12",
      iconName: "Cpu",
      sortOrder: 82,
    },
    {
      name: "Industrial Maintenance Technician",
      category: "Skilled Trades",
      description: "Maintain and repair industrial machinery and equipment in manufacturing facilities. Troubleshoot mechanical, electrical, and hydraulic systems. Certificate programs take 6-12 months. Critical role in every manufacturing plant.",
      educationPath: "technical-certification",
      salaryRange: "$42,000 - $68,000",
      requiredSkills: ["Mechanical Systems", "Electrical Troubleshooting", "Hydraulics", "Preventive Maintenance", "Safety"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Settings",
      sortOrder: 83,
    },
    {
      name: "Robotics Technician",
      category: "Skilled Trades",
      description: "Program, operate, and maintain industrial robots used in manufacturing and automation. Troubleshoot robotic systems and optimize production processes. Certificate programs take 6-18 months. Growing field as automation expands.",
      educationPath: "technical-certification",
      salaryRange: "$45,000 - $72,000",
      requiredSkills: ["Robotics Programming", "Mechanical Skills", "Electrical Systems", "Problem Solving", "Computer Skills"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Cog",
      sortOrder: 84,
    },
    // Additional Skilled Trades
    {
      name: "Pipefitter/Steamfitter",
      category: "Skilled Trades",
      description: "Install and maintain piping systems that carry chemicals, acids, and gases in manufacturing, power plants, and industrial facilities. Apprenticeship takes 4-5 years with paid on-the-job training from day one.",
      educationPath: "trade-school",
      salaryRange: "$48,000 - $85,000",
      requiredSkills: ["Pipe Fitting", "Blueprint Reading", "Welding", "Mathematics", "Safety Protocols"],
      relatedSubjects: ["Math", "Science", "Technology"],
      gradeLevel: "9-12",
      iconName: "Wrench",
      sortOrder: 85,
    },
    {
      name: "Ironworker",
      category: "Skilled Trades",
      description: "Install structural and reinforcing iron and steel for buildings, bridges, and highways. Work at heights assembling steel frameworks. Apprenticeship-based with paid training. Essential for Austin's construction boom.",
      educationPath: "trade-school",
      salaryRange: "$42,000 - $78,000",
      requiredSkills: ["Structural Assembly", "Blueprint Reading", "Welding", "Physical Fitness", "Heights Comfort"],
      relatedSubjects: ["Math", "Science"],
      gradeLevel: "9-12",
      iconName: "Hammer",
      sortOrder: 86,
    },
    {
      name: "Mason/Bricklayer",
      category: "Skilled Trades",
      description: "Build and repair walls, walkways, and other structures using brick, concrete block, and stone. Apprenticeships take 3-4 years with paid on-the-job training. Essential for residential and commercial construction.",
      educationPath: "trade-school",
      salaryRange: "$38,000 - $68,000",
      requiredSkills: ["Masonry Techniques", "Blueprint Reading", "Physical Fitness", "Precision", "Mathematics"],
      relatedSubjects: ["Math", "Art"],
      gradeLevel: "9-12",
      iconName: "Building2",
      sortOrder: 87,
    },
    // Entrepreneurship & Freelance (No Degree)
    {
      name: "Freelance Content Creator",
      category: "Media & Communications",
      description: "Create content for social media, YouTube, podcasts, and blogs. Build an audience and monetize through sponsorships, ads, and merchandise. No degree needed — learn by doing. Austin is a top creator economy hub.",
      educationPath: "entrepreneurship",
      salaryRange: "$20,000 - $100,000+",
      requiredSkills: ["Content Creation", "Video Editing", "Social Media", "Marketing", "Consistency"],
      relatedSubjects: ["English", "Art", "Technology"],
      gradeLevel: "9-12",
      iconName: "Video",
      sortOrder: 88,
    },
    {
      name: "Personal Trainer / Fitness Coach",
      category: "Healthcare",
      description: "Design and lead fitness programs for individuals and groups. Earn certification through NASM, ACE, or ISSA in 3-6 months. Work in gyms, private studios, or build an online coaching business. No degree required.",
      educationPath: "technical-certification",
      salaryRange: "$30,000 - $65,000+",
      requiredSkills: ["Exercise Science", "Motivation", "Communication", "Program Design", "Nutrition Basics"],
      relatedSubjects: ["Science", "Math", "English"],
      gradeLevel: "9-12",
      iconName: "Activity",
      sortOrder: 89,
    },
    {
      name: "Community Health Worker (CHW)",
      category: "Healthcare",
      description: "Serve as a bridge between communities and healthcare systems. Help people navigate resources, access care, and manage chronic conditions. Texas CHW certification takes 160 hours. TCAF and LifeBridge train and deploy CHWs across Central Texas.",
      educationPath: "technical-certification",
      salaryRange: "$32,000 - $48,000",
      requiredSkills: ["Community Outreach", "Cultural Competency", "Communication", "Resource Navigation", "Empathy"],
      relatedSubjects: ["English", "Social Studies", "Science"],
      gradeLevel: "9-12",
      iconName: "Users",
      sortOrder: 90,
    },
  ]);
}

export async function seedCareerMilestones(db: any): Promise<void> {
  await db.insert(careerMilestones).values([
    // Grade 6
    {
      gradeLevel: 6,
      title: "Identity Explorer",
      description: "Discover who you are by exploring your interests, strengths, and values through self-assessment activities and reflective journaling.",
      category: "identity",
      awardName: "Self-Discovery Badge",
      awardDescription: "Awarded for completing your personal interests and strengths inventory.",
      requirements: "Complete the personal interests survey, identify three personal strengths, and write a short reflection on what makes you unique.",
      sortOrder: 1,
    },
    {
      gradeLevel: 6,
      title: "First Investment",
      description: "Learn the basics of saving and investing by making your first simulated investment and tracking its performance over time.",
      category: "financial",
      awardName: "Young Investor Badge",
      awardDescription: "Awarded for completing your first simulated investment and learning about financial growth.",
      requirements: "Complete the financial literacy introduction, make your first simulated stock investment, and track it for two weeks.",
      sortOrder: 2,
    },
    {
      gradeLevel: 6,
      title: "Community Builder",
      description: "Take your first steps in community involvement by participating in a group project and contributing to your school community.",
      category: "community",
      awardName: "Community Spark Badge",
      awardDescription: "Awarded for your first meaningful contribution to the school community.",
      requirements: "Participate in one community activity, contribute to a group project, and reflect on the experience.",
      sortOrder: 3,
    },
    // Grade 7
    {
      gradeLevel: 7,
      title: "Industry Scout",
      description: "Research different career industries and interview a professional to learn about real-world jobs and what it takes to succeed in various fields.",
      category: "career",
      awardName: "Industry Explorer Badge",
      awardDescription: "Awarded for researching career industries and conducting a professional interview.",
      requirements: "Research three different industries, interview one working professional, and present findings to your class.",
      sortOrder: 4,
    },
    {
      gradeLevel: 7,
      title: "Financial Planner",
      description: "Create your first personal budget and learn to distinguish between needs, wants, and savings goals for short-term and long-term planning.",
      category: "financial",
      awardName: "Budget Master Badge",
      awardDescription: "Awarded for creating and maintaining a personal budget plan.",
      requirements: "Create a monthly budget, track expenses for one month, and set one savings goal with a timeline.",
      sortOrder: 5,
    },
    {
      gradeLevel: 7,
      title: "Pathway Pioneer",
      description: "Begin mapping your educational pathway by exploring different high school course options and extracurricular activities that align with your interests.",
      category: "career",
      awardName: "Pathfinder Badge",
      awardDescription: "Awarded for creating your first educational pathway map.",
      requirements: "Explore available high school pathways, identify courses of interest, and create a preliminary four-year course plan.",
      sortOrder: 6,
    },
    // Grade 8
    {
      gradeLevel: 8,
      title: "Pathfinder",
      description: "Narrow your career interests by completing a career aptitude assessment and creating a vision board for your future goals.",
      category: "career",
      awardName: "Career Vision Badge",
      awardDescription: "Awarded for completing career assessments and defining your career vision.",
      requirements: "Complete a career aptitude assessment, create a career vision board, and identify your top three career interests.",
      sortOrder: 7,
    },
    {
      gradeLevel: 8,
      title: "Mentor Connected",
      description: "Connect with a mentor who can guide your personal and academic growth. Learn how mentorship helps you reach your goals faster.",
      category: "mentorship",
      awardName: "Mentorship Bond Badge",
      awardDescription: "Awarded for establishing your first mentor relationship.",
      requirements: "Identify a potential mentor, have at least two mentoring conversations, and document three key lessons learned.",
      sortOrder: 8,
    },
    {
      gradeLevel: 8,
      title: "Plan Architect",
      description: "Design a comprehensive plan for your high school years, including academic goals, extracurricular interests, and career exploration activities.",
      category: "portfolio",
      awardName: "Master Planner Badge",
      awardDescription: "Awarded for creating a detailed high school success plan.",
      requirements: "Create a four-year high school plan with academic, extracurricular, and career goals for each year.",
      sortOrder: 9,
    },
    // Grade 9
    {
      gradeLevel: 9,
      title: "Skill Builder",
      description: "Develop a marketable skill by completing a hands-on project or workshop in your area of interest, from coding to cooking to construction.",
      category: "career",
      awardName: "Skill Acquisition Badge",
      awardDescription: "Awarded for developing a new practical skill through hands-on learning.",
      requirements: "Choose a skill area, complete at least 20 hours of practice or training, and demonstrate your skill through a project.",
      sortOrder: 10,
    },
    {
      gradeLevel: 9,
      title: "Leadership Rising",
      description: "Take on your first leadership role by organizing a school event, leading a club meeting, or mentoring a younger student.",
      category: "leadership",
      awardName: "Rising Leader Badge",
      awardDescription: "Awarded for demonstrating leadership initiative in your school community.",
      requirements: "Take on a leadership role in a club or project, lead at least one group activity, and reflect on your leadership style.",
      sortOrder: 11,
    },
    {
      gradeLevel: 9,
      title: "Portfolio Starter",
      description: "Begin building your professional portfolio by collecting your best work samples, achievements, and reflections from your academic journey.",
      category: "portfolio",
      awardName: "Portfolio Foundation Badge",
      awardDescription: "Awarded for creating the foundation of your professional portfolio.",
      requirements: "Collect five quality work samples, write descriptions for each, and organize them in a digital portfolio.",
      sortOrder: 12,
    },
    // Grade 10
    {
      gradeLevel: 10,
      title: "Industry Apprentice",
      description: "Gain real-world experience through job shadowing, an internship, or a community service project related to your career interests.",
      category: "career",
      awardName: "Real World Experience Badge",
      awardDescription: "Awarded for completing hands-on career experience outside the classroom.",
      requirements: "Complete at least one job shadow day or 20 hours of career-related volunteer work, and write a reflection report.",
      sortOrder: 13,
    },
    {
      gradeLevel: 10,
      title: "Campus Explorer",
      description: "Research and visit colleges, trade schools, or training programs that align with your career pathway. Compare options and begin planning your next steps.",
      category: "career",
      awardName: "Campus Scout Badge",
      awardDescription: "Awarded for actively researching post-secondary education options.",
      requirements: "Research five post-secondary institutions, attend at least one campus tour or virtual info session, and compare programs.",
      sortOrder: 14,
    },
    {
      gradeLevel: 10,
      title: "Credential Seeker",
      description: "Identify and begin working toward an industry certification, credential, or specialized training that will set you apart in your chosen field.",
      category: "credential",
      awardName: "Credential Pursuit Badge",
      awardDescription: "Awarded for identifying and beginning work toward a professional credential.",
      requirements: "Research relevant certifications for your career interest, create a study plan, and complete at least one preparatory course or module.",
      sortOrder: 15,
    },
    // Grade 11
    {
      gradeLevel: 11,
      title: "Credential Earned",
      description: "Earn your first industry-recognized certification, credential, or complete a specialized training program that validates your professional skills.",
      category: "credential",
      awardName: "Certified Professional Badge",
      awardDescription: "Awarded for earning your first industry credential or certification.",
      requirements: "Pass an industry certification exam or complete an accredited training program with a certificate of completion.",
      sortOrder: 16,
    },
    {
      gradeLevel: 11,
      title: "Application Champion",
      description: "Master the college and career application process by completing applications, writing personal statements, and preparing for interviews.",
      category: "career",
      awardName: "Application Pro Badge",
      awardDescription: "Awarded for demonstrating mastery of the application and interview process.",
      requirements: "Complete at least two college or job applications, write a personal statement, and participate in a mock interview.",
      sortOrder: 17,
    },
    {
      gradeLevel: 11,
      title: "Peer Mentor",
      description: "Give back by mentoring younger students, sharing your experiences, and helping them navigate their own academic and career journeys.",
      category: "mentorship",
      awardName: "Mentor Heart Badge",
      awardDescription: "Awarded for serving as a peer mentor and positively impacting younger students.",
      requirements: "Mentor at least one younger student for a semester, hold regular check-in meetings, and document the mentoring experience.",
      sortOrder: 18,
    },
    // Grade 12
    {
      gradeLevel: 12,
      title: "Graduate Panther",
      description: "Complete all graduation requirements and celebrate your academic journey. Reflect on your growth and prepare for the next chapter of your life.",
      category: "credential",
      awardName: "Graduate Panther Award",
      awardDescription: "The highest academic honor, awarded upon successful completion of all graduation requirements.",
      requirements: "Complete all required coursework, maintain satisfactory academic standing, and fulfill all graduation criteria.",
      sortOrder: 19,
    },
    {
      gradeLevel: 12,
      title: "Future Leader",
      description: "Demonstrate exceptional leadership by leading a significant project, initiative, or organization that creates lasting positive impact in your community.",
      category: "leadership",
      awardName: "Future Leader Award",
      awardDescription: "Awarded to graduating seniors who have shown outstanding leadership and community impact.",
      requirements: "Lead a major school or community project, document measurable impact, and present your leadership journey at a school event.",
      sortOrder: 20,
    },
    {
      gradeLevel: 12,
      title: "Ambassador Nominee",
      description: "Be nominated by peers and faculty as a school ambassador who exemplifies the values of excellence, character, and service to others.",
      category: "community",
      awardName: "Ambassador Nominee Award",
      awardDescription: "Awarded to students nominated as representatives of school values and community spirit.",
      requirements: "Receive nominations from peers and faculty, maintain a record of community service, and deliver a speech on your vision for future students.",
      sortOrder: 21,
    },
    // Post-Grad (13)
    {
      gradeLevel: 13,
      title: "Rising Professional",
      description: "Successfully transition into your post-secondary path, whether college, trade school, military service, or the workforce, and begin building your professional network.",
      category: "alumni",
      awardName: "Rising Professional Award",
      awardDescription: "Awarded to alumni who have successfully launched their post-secondary careers.",
      requirements: "Enroll in a post-secondary program or begin employment, join a professional network, and share your transition story with current students.",
      sortOrder: 22,
    },
    {
      gradeLevel: 13,
      title: "Community Champion",
      description: "Continue giving back to your community and school by volunteering, speaking at events, or creating opportunities for current students.",
      category: "alumni",
      awardName: "Community Champion Award",
      awardDescription: "Awarded to alumni who continue to make a positive impact in their communities.",
      requirements: "Complete at least 20 hours of community service post-graduation, participate in one school event as a guest, and mentor a current student.",
      sortOrder: 23,
    },
    {
      gradeLevel: 13,
      title: "Legacy Ambassador",
      description: "Become an official school ambassador by representing your alma mater, sharing your success story, and inspiring the next generation of students.",
      category: "alumni",
      awardName: "Legacy Ambassador Award",
      awardDescription: "The most prestigious alumni honor, recognizing those who embody the school's mission and inspire future generations.",
      requirements: "Maintain active alumni status for one year, participate in recruitment or mentoring programs, and contribute to school improvement initiatives.",
      sortOrder: 24,
    },
  ]);
}
