import { academyScenarios, academyScenarioNodes } from "@shared/schema";

export async function seedScenarios(db: any) {
  // Scenario 1: The Lemonade Stand Empire
  const [scenario1] = await db.insert(academyScenarios).values({
    title: "The Lemonade Stand Empire",
    theme: "finance",
    summary: "Start your own lemonade business and learn about pricing, location strategy, handling setbacks, and reinvesting profits.",
    difficulty: "easy",
    empathyPrompt: "Every great business started with a single idea. What would YOU create?",
    featureArea: "wallet",
    totalNodes: 8,
    rewardCategory: "entrepreneurship",
    isActive: true,
  }).onConflictDoNothing().returning();

  if (scenario1) {
    await db.insert(academyScenarioNodes).values([
      {
        scenarioId: scenario1.id,
        nodeKey: "start",
        narrative: "You have $100 saved up and a dream: to start your own lemonade business! You've practiced your recipe with your family, and everyone says it's delicious. Now it's time to decide where to set up shop. This is your first big business decision!",
        isStart: true,
        isEnd: false,
        choices: [
          { key: "a", label: "Set up at the busy park on weekends", nextNodeKey: "park_location", consequence: { description: "The park has lots of foot traffic but also more competition." } },
          { key: "b", label: "Set up outside your school after classes", nextNodeKey: "school_location", consequence: { description: "Students are thirsty after school and you know the crowd well." } },
        ],
        walletImpact: "0.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "neutral",
        sortOrder: 0,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "park_location",
        narrative: "Great choice! The park is packed on sunny weekends. You spend $30 on supplies and set up a colorful stand. Families are walking by and kids are pointing at your sign. Now you need to decide on pricing.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Price low at $1 per cup to attract lots of customers", nextNodeKey: "low_price", consequence: { description: "More customers but lower profit per sale." } },
          { key: "b", label: "Price at $2.50 per cup for quality lemonade", nextNodeKey: "fair_price", consequence: { description: "Fewer customers but better margins and a premium feel." } },
        ],
        consequenceSummary: "You chose the park - great foot traffic!",
        walletImpact: "-30.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "school_location",
        narrative: "Smart thinking! You know your classmates love cold drinks after school. You spend $25 on supplies and make a deal with the school to set up near the entrance. Your friends are excited to support you. Time to set your prices!",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Price low at $1 per cup to attract lots of customers", nextNodeKey: "low_price", consequence: { description: "More customers but lower profit per sale." } },
          { key: "b", label: "Price at $2.50 per cup for quality lemonade", nextNodeKey: "fair_price", consequence: { description: "Fewer customers but better margins and a premium feel." } },
        ],
        consequenceSummary: "You chose school - loyal customers who know you!",
        walletImpact: "-25.00",
        powerImpact: 5,
        meritImpact: 5,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "low_price",
        narrative: "Your $1 lemonade is flying off the table! You sell 40 cups on your first day. But then you realize - after costs, you only made $15 profit. And now a bigger problem: another kid has set up a stand nearby selling juice boxes for 75 cents!",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Lower your price to compete", nextNodeKey: "price_war_setback", consequence: { description: "A price war begins and profits drop even more." } },
          { key: "b", label: "Improve your product with fresh fruit toppings", nextNodeKey: "quality_upgrade", consequence: { description: "You differentiate yourself with a premium product." } },
        ],
        consequenceSummary: "Low prices brought crowds but thin margins.",
        walletImpact: "15.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "learning",
        sortOrder: 2,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "fair_price",
        narrative: "At $2.50, some people walk by, but those who buy love your lemonade! You sell 20 cups and make $35 profit. A customer suggests you add flavors. Then it starts to rain - your worst nightmare!",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Pack up and try again next week", nextNodeKey: "rain_setback", consequence: { description: "You lose the rest of the day but save your supplies." } },
          { key: "b", label: "Move under a shelter and offer warm lemon tea instead", nextNodeKey: "adapt_success", consequence: { description: "You adapt quickly and turn a setback into an opportunity." } },
        ],
        consequenceSummary: "Fair pricing brought quality customers and solid profit.",
        walletImpact: "35.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "price_war_setback",
        narrative: "You dropped your price to 50 cents, but the other stand dropped to 25 cents! You sold a lot but barely covered your costs. You lost $10 today. It feels discouraging, but every entrepreneur faces competition.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Rethink your strategy and focus on what makes you unique", nextNodeKey: "quality_upgrade", consequence: { description: "You learn that competing on price alone rarely works." } },
        ],
        consequenceSummary: "The price war taught you that the cheapest option isn't always the best strategy.",
        walletImpact: "-10.00",
        powerImpact: 0,
        meritImpact: 0,
        emotionalTone: "setback",
        pathForward: "Every successful business owner has lost money learning what NOT to do. The fact that you're reflecting on this means you're already growing. The best businesses don't compete on price - they compete on value!",
        sortOrder: 3,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "rain_setback",
        narrative: "The rain ruined your afternoon and you lost potential sales. You're sitting at home feeling disappointed. But then you start planning - what if you had a backup plan for bad weather?",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "The rain was a setback, but you learned the importance of planning for the unexpected. Next time, you'll have a backup plan ready!",
        walletImpact: "-25.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "setback",
        pathForward: "Rain doesn't mean failure - it means you need an umbrella plan! The best entrepreneurs always have a Plan B. You walked away with experience that money can't buy, and next weekend you'll be unstoppable.",
        sortOrder: 4,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "quality_upgrade",
        narrative: "You added fresh strawberries and mint to your lemonade and raised the price to $3. Customers are raving about it! Word spreads and you sell 30 cups, making $50 profit. You reinvest $20 into better supplies and pocket $30. Your lemonade empire is growing!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "By focusing on quality over price, you built a brand people love. You learned that investing in your product is investing in your future!",
        walletImpact: "50.00",
        powerImpact: 15,
        meritImpact: 10,
        emotionalTone: "triumph",
        sortOrder: 4,
      },
      {
        scenarioId: scenario1.id,
        nodeKey: "adapt_success",
        narrative: "Genius move! You found shelter, heated water with a thermos, and started selling warm lemon-honey tea for $3. People loved it! You sold 25 cups and made $45. Other vendors packed up, but you adapted and thrived. You're a true entrepreneur!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "You turned a rainy setback into your biggest success! Adaptability is the superpower of every great entrepreneur.",
        walletImpact: "45.00",
        powerImpact: 20,
        meritImpact: 10,
        emotionalTone: "triumph",
        sortOrder: 4,
      },
    ]).onConflictDoNothing();
  }

  // Scenario 2: The Team Project Challenge
  const [scenario2] = await db.insert(academyScenarios).values({
    title: "The Team Project Challenge",
    theme: "leadership",
    summary: "Lead a group project where teammates disagree, one member is struggling, and the deadline is approaching fast.",
    difficulty: "medium",
    empathyPrompt: "The best leaders don't just lead - they listen, support, and lift others up.",
    featureArea: "competitions",
    totalNodes: 8,
    rewardCategory: "leadership",
    isActive: true,
  }).onConflictDoNothing().returning();

  if (scenario2) {
    await db.insert(academyScenarioNodes).values([
      {
        scenarioId: scenario2.id,
        nodeKey: "start",
        narrative: "Your teacher just assigned a big group project worth 30% of your grade. You've been chosen as team leader! Your team has four members: Alex (creative but disorganized), Maya (hardworking but shy), Jordan (smart but wants to do everything their way), and you. The project is due in two weeks.",
        isStart: true,
        isEnd: false,
        choices: [
          { key: "a", label: "Call a team meeting and assign roles based on everyone's strengths", nextNodeKey: "collaborate_start", consequence: { description: "You take a collaborative approach to leadership." } },
          { key: "b", label: "Create a detailed plan yourself and tell everyone what to do", nextNodeKey: "dictate_start", consequence: { description: "You take charge and make all the decisions." } },
        ],
        walletImpact: "0.00",
        powerImpact: 5,
        meritImpact: 5,
        emotionalTone: "neutral",
        sortOrder: 0,
      },
      {
        scenarioId: scenario2.id,
        nodeKey: "collaborate_start",
        narrative: "Great call! At the meeting, everyone shares their ideas. Alex suggests an amazing creative concept, Maya quietly offers to handle research, and Jordan... wants to take over the whole project. Jordan says, 'I can do this faster alone.' Maya looks uncomfortable.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Talk to Jordan privately and explain why teamwork matters", nextNodeKey: "jordan_talk", consequence: { description: "You address the conflict with empathy and directness." } },
          { key: "b", label: "Let Jordan take over to avoid conflict", nextNodeKey: "avoid_conflict_setback", consequence: { description: "You avoid the hard conversation but the team suffers." } },
        ],
        consequenceSummary: "Your collaborative approach surfaced both great ideas and hidden tensions.",
        walletImpact: "0.00",
        powerImpact: 10,
        meritImpact: 5,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario2.id,
        nodeKey: "dictate_start",
        narrative: "You created a perfect plan and handed out assignments. But Alex is frustrated - they had creative ideas you didn't ask about. Maya is struggling with her part but is too shy to ask for help. Jordan is ignoring your plan entirely and doing their own thing. The team is falling apart.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Pause, apologize, and ask everyone for their input", nextNodeKey: "jordan_talk", consequence: { description: "You course-correct and show humility." } },
          { key: "b", label: "Push harder and insist everyone follows your plan", nextNodeKey: "team_collapse_setback", consequence: { description: "The team fractures under pressure." } },
        ],
        consequenceSummary: "Your top-down approach created resentment and disconnection.",
        walletImpact: "0.00",
        powerImpact: 0,
        meritImpact: -5,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario2.id,
        nodeKey: "jordan_talk",
        narrative: "You talk to Jordan honestly: 'I get that you're talented, but we need everyone's voice in this.' Jordan admits they're used to working alone because past teams let them down. You promise this team will be different. Jordan agrees to collaborate. Now you notice Maya is falling behind on her research.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Sit down with Maya and help her catch up", nextNodeKey: "help_maya", consequence: { description: "You invest time in a struggling teammate." } },
          { key: "b", label: "Reassign Maya's work to finish faster", nextNodeKey: "skip_maya_setback", consequence: { description: "You prioritize the deadline over your teammate." } },
        ],
        consequenceSummary: "You resolved the conflict with Jordan through honest conversation.",
        walletImpact: "0.00",
        powerImpact: 15,
        meritImpact: 10,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario2.id,
        nodeKey: "avoid_conflict_setback",
        narrative: "Jordan took over and did great work - but Alex and Maya feel invisible. Alex stops contributing, and Maya almost drops the class. The project might get an A, but you lost your team's trust. Leadership isn't just about results.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "Avoiding conflict cost you your team's trust. A leader's job is to make sure every voice matters.",
        walletImpact: "0.00",
        powerImpact: -5,
        meritImpact: -10,
        emotionalTone: "setback",
        pathForward: "It takes courage to have hard conversations, and it's okay that you chose peace this time. The important thing is recognizing that real leadership means standing up for everyone on your team - even when it's uncomfortable. Next time, you'll have the courage to speak up.",
        sortOrder: 3,
      },
      {
        scenarioId: scenario2.id,
        nodeKey: "team_collapse_setback",
        narrative: "Alex quit the group, Maya had a breakdown, and Jordan submitted their own version. The teacher is disappointed. You meant well, but pushing too hard without listening broke the team apart.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "The team fell apart because leadership became about control instead of connection.",
        walletImpact: "0.00",
        powerImpact: -10,
        meritImpact: -15,
        emotionalTone: "setback",
        pathForward: "This is a tough moment, but it's also a turning point. The greatest leaders in history all had failures that taught them to listen more and control less. You now understand something most people take years to learn: a team is only as strong as the trust between its members. Your next team will be different.",
        sortOrder: 3,
      },
      {
        scenarioId: scenario2.id,
        nodeKey: "help_maya",
        narrative: "You spend a lunch period helping Maya. Turns out she understood the material but was overwhelmed by the format. With your guidance, she produces the best research section anyone's ever seen. Maya beams with pride. On presentation day, the team crushes it! The teacher gives you the highest group grade in class.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "By investing in Maya, you unlocked hidden potential. The team earned top marks and genuine friendships. True leadership is lifting others up!",
        walletImpact: "0.00",
        powerImpact: 25,
        meritImpact: 20,
        emotionalTone: "triumph",
        sortOrder: 3,
      },
      {
        scenarioId: scenario2.id,
        nodeKey: "skip_maya_setback",
        narrative: "You reassigned Maya's work. The project finished on time with a good grade, but Maya felt pushed aside. She stopped participating in class and you can tell she's hurt. A week later, the teacher pulls you aside and says leadership means no one gets left behind.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "The project succeeded, but a teammate was left behind. You learned that deadlines matter, but people matter more.",
        walletImpact: "0.00",
        powerImpact: 5,
        meritImpact: -5,
        emotionalTone: "setback",
        pathForward: "Getting the project done was important, and you showed responsibility. But great leaders find a way to meet deadlines AND support their team. It's not easy - but now you know to look for that balance. Maya might need a kind word from you, and that conversation could change everything.",
        sortOrder: 3,
      },
    ]).onConflictDoNothing();
  }

  // Scenario 3: The Investment Rollercoaster
  const [scenario3] = await db.insert(academyScenarios).values({
    title: "The Investment Rollercoaster",
    theme: "finance",
    summary: "Navigate the stock market with virtual money. Make investment decisions, survive market crashes, and learn about diversification.",
    difficulty: "hard",
    empathyPrompt: "Smart investors know that setbacks are stepping stones. Every loss teaches a lesson.",
    featureArea: "stocks",
    totalNodes: 8,
    rewardCategory: "entrepreneurship",
    isActive: true,
  }).onConflictDoNothing().returning();

  if (scenario3) {
    await db.insert(academyScenarioNodes).values([
      {
        scenarioId: scenario3.id,
        nodeKey: "start",
        narrative: "Congratulations! You've earned $500 in virtual Academy Dollars and it's time to invest. The stock market is open and you can see three promising companies: TechStar (a hot tech company, $50/share), GreenGrow (a steady farming company, $25/share), and EduLearn (an education startup, $30/share). How do you invest?",
        isStart: true,
        isEnd: false,
        choices: [
          { key: "a", label: "Put all $500 into TechStar - it's the hottest stock!", nextNodeKey: "all_in_tech", consequence: { description: "You go all-in on one stock - high risk, high potential reward." } },
          { key: "b", label: "Split evenly: $166 in each of the three companies", nextNodeKey: "diversified", consequence: { description: "You spread your risk across multiple investments." } },
          { key: "c", label: "Put $300 in GreenGrow and $200 in EduLearn - skip the hype", nextNodeKey: "conservative", consequence: { description: "You choose stable investments and avoid the trendy pick." } },
        ],
        walletImpact: "0.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "neutral",
        sortOrder: 0,
      },
      {
        scenarioId: scenario3.id,
        nodeKey: "all_in_tech",
        narrative: "TechStar shoots up 40% in the first week! Your $500 is now worth $700! You feel like a genius. But then breaking news: TechStar's CEO is under investigation for fraud. The stock is crashing - down 60% in one day!",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "SELL EVERYTHING before it drops more!", nextNodeKey: "panic_sell_setback", consequence: { description: "You sell in a panic and lock in your losses." } },
          { key: "b", label: "Hold steady - the investigation might clear up", nextNodeKey: "hold_through_crash", consequence: { description: "You stay calm and wait for more information." } },
        ],
        consequenceSummary: "Your all-in bet paid off at first, but now you face a crisis with no safety net.",
        walletImpact: "100.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario3.id,
        nodeKey: "diversified",
        narrative: "Smart move! In the first week, TechStar goes up 40%, GreenGrow stays flat, and EduLearn rises 10%. Your portfolio is up overall. Then bad news hits: TechStar crashes 60% due to a scandal! But your other stocks cushion the blow.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Sell TechStar and buy more GreenGrow and EduLearn", nextNodeKey: "rebalance_success", consequence: { description: "You cut your losses and strengthen your winners." } },
          { key: "b", label: "Buy MORE TechStar while it's cheap - it might recover!", nextNodeKey: "buy_the_dip", consequence: { description: "You bet on a risky recovery." } },
        ],
        consequenceSummary: "Diversification protected you from the worst of the crash!",
        walletImpact: "25.00",
        powerImpact: 10,
        meritImpact: 0,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario3.id,
        nodeKey: "conservative",
        narrative: "While everyone was bragging about TechStar gains, your steady investments quietly grew. GreenGrow is up 8% and EduLearn is up 15%. Then TechStar crashes and everyone is panicking - but your portfolio is safe and growing!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "Your patience and research paid off! While others chased hype, you built real wealth through steady, smart investing. You end with $575 - a solid 15% gain!",
        walletImpact: "75.00",
        powerImpact: 20,
        meritImpact: 10,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario3.id,
        nodeKey: "panic_sell_setback",
        narrative: "You sold everything at a 60% loss. Your $700 became $280. You lost $220 from your original investment. Watching from the sidelines, you see TechStar slowly recover over the next month back to $40/share. If you had held, you would have recovered most of your money.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "Panic selling locked in your losses. Fear made the decision instead of logic. You lost $220 but gained wisdom worth much more.",
        walletImpact: "-75.00",
        powerImpact: 5,
        meritImpact: 0,
        emotionalTone: "setback",
        pathForward: "This is the lesson every great investor learns at some point: emotions are your biggest enemy in investing. Warren Buffett once said, 'Be fearful when others are greedy, and greedy when others are fearful.' You now understand what that means firsthand. Next time the market drops, you'll remember this moment and make a calmer decision.",
        sortOrder: 2,
      },
      {
        scenarioId: scenario3.id,
        nodeKey: "hold_through_crash",
        narrative: "It was agonizing to watch your investment drop, but you held firm. Three weeks later, TechStar was cleared of wrongdoing. The stock recovered to $45/share. You didn't make as much as the peak, but you didn't lose everything either. Your patience saved you!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "Your courage to hold through the storm paid off. You ended with $450 - a small loss but a massive lesson in patience and emotional control.",
        walletImpact: "-50.00",
        powerImpact: 20,
        meritImpact: 5,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario3.id,
        nodeKey: "rebalance_success",
        narrative: "You sold TechStar at a loss but reinvested in your winners. Over the next month, GreenGrow grew 12% and EduLearn grew 20%. Your total portfolio is now worth $590. You turned a crisis into an opportunity through smart rebalancing!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "By staying calm and rebalancing, you turned a market crash into a learning opportunity. You ended with $590 - an 18% gain through smart decision-making!",
        walletImpact: "100.00",
        powerImpact: 25,
        meritImpact: 10,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario3.id,
        nodeKey: "buy_the_dip",
        narrative: "You bought more TechStar at rock bottom prices. It was risky - but the investigation cleared and TechStar recovered to $45. Your bold move paid off and your portfolio jumped to $620! However, you realize you got lucky. Next time, the crash might be real.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "Your bold bet paid off this time, bringing your total to $620. But remember - buying into a crash is one of the riskiest moves in investing. Sometimes it works, sometimes you lose everything. The key lesson: never risk more than you can afford to lose.",
        walletImpact: "75.00",
        powerImpact: 15,
        meritImpact: 5,
        emotionalTone: "learning",
        sortOrder: 2,
      },
    ]).onConflictDoNothing();
  }

  // Scenario 4: Building Community
  const [scenario4] = await db.insert(academyScenarios).values({
    title: "Building Community",
    theme: "community",
    summary: "Plan and execute a community event on campus. Navigate fundraising, disagreements, and inclusive decision-making.",
    difficulty: "medium",
    empathyPrompt: "A community is only as strong as the connections between its members.",
    featureArea: "campus",
    totalNodes: 8,
    rewardCategory: "community",
    isActive: true,
  }).onConflictDoNothing().returning();

  if (scenario4) {
    await db.insert(academyScenarioNodes).values([
      {
        scenarioId: scenario4.id,
        nodeKey: "start",
        narrative: "The student council has given you the chance to plan a big community event on campus! You have a budget of $200 and three weeks to make it happen. Your goal: bring students together and make everyone feel included. First, you need to decide what kind of event to plan.",
        isStart: true,
        isEnd: false,
        choices: [
          { key: "a", label: "Plan a Cultural Festival celebrating different backgrounds", nextNodeKey: "cultural_festival", consequence: { description: "An event that highlights diversity and shared experiences." } },
          { key: "b", label: "Organize a Community Service Day to help the neighborhood", nextNodeKey: "service_day", consequence: { description: "An event focused on giving back and working together." } },
          { key: "c", label: "Host a Talent Show & Open Mic for student creativity", nextNodeKey: "talent_show", consequence: { description: "An event that gives every student a stage to shine." } },
        ],
        walletImpact: "0.00",
        powerImpact: 5,
        meritImpact: 5,
        emotionalTone: "neutral",
        sortOrder: 0,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "cultural_festival",
        narrative: "Amazing idea! Students are excited to share their cultures. But a problem arises: some students feel their culture isn't 'interesting enough' to showcase, and a few students are making fun of unfamiliar traditions. You need to address this before it ruins the event.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Hold a class discussion about respect and what makes every culture special", nextNodeKey: "respect_discussion", consequence: { description: "You address the issue head-on with education and empathy." } },
          { key: "b", label: "Just ignore it and hope it goes away by event day", nextNodeKey: "ignore_tension_setback", consequence: { description: "The tension builds and threatens the event." } },
        ],
        consequenceSummary: "The Cultural Festival idea is inspiring but brings up real challenges about inclusion.",
        walletImpact: "0.00",
        powerImpact: 10,
        meritImpact: 10,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "service_day",
        narrative: "The community service idea gets great support from teachers! You partner with a local park that needs cleaning and a food bank that needs volunteers. But you realize $200 isn't enough for supplies, transportation, and food for volunteers. You need to fundraise!",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Organize a bake sale and ask local businesses for donations", nextNodeKey: "fundraise_success", consequence: { description: "You rally the community to support the cause." } },
          { key: "b", label: "Scale down the event to fit your budget", nextNodeKey: "scale_down", consequence: { description: "You work within your means but reach fewer people." } },
        ],
        consequenceSummary: "Your service day needs more resources - time to get creative with fundraising!",
        walletImpact: "0.00",
        powerImpact: 10,
        meritImpact: 15,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "talent_show",
        narrative: "The talent show has tons of sign-ups! But you notice something: it's mostly the same popular kids who always perform. The quieter students feel too nervous to sign up. A shy student named Priya tells you she writes beautiful poetry but is terrified of performing alone.",
        isStart: false,
        isEnd: false,
        choices: [
          { key: "a", label: "Create a 'group performance' category so shy students can perform with friends", nextNodeKey: "inclusive_show", consequence: { description: "You redesign the event to include every type of performer." } },
          { key: "b", label: "Tell Priya she should just be brave and sign up solo", nextNodeKey: "exclude_shy_setback", consequence: { description: "You dismiss the concern without solving the problem." } },
        ],
        consequenceSummary: "The talent show is popular but risks excluding quieter voices.",
        walletImpact: "0.00",
        powerImpact: 10,
        meritImpact: 5,
        emotionalTone: "learning",
        sortOrder: 1,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "respect_discussion",
        narrative: "The class discussion was powerful. Students shared stories about their families, traditions, and what makes their culture meaningful. The students who were making fun apologized after hearing personal stories. On festival day, every booth is packed and students are trying foods, learning dances, and making connections across cultures. The principal calls it the best school event ever!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "Your courage to address tension created a transformative event. Students learned that every culture has beauty worth celebrating, and you built bridges that will last beyond one event.",
        walletImpact: "0.00",
        powerImpact: 25,
        meritImpact: 25,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "ignore_tension_setback",
        narrative: "On event day, the tension explodes. Some students boycott the festival, others argue loudly, and a few cultural displays are vandalized. The event is cut short and the principal is disappointed. You wish you had addressed the problem when it was small.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "Ignoring tension didn't make it disappear - it made it worse. The event was damaged, but the lesson is clear: leaders must address problems early.",
        walletImpact: "0.00",
        powerImpact: -5,
        meritImpact: -10,
        emotionalTone: "setback",
        pathForward: "This was a hard lesson, but an important one. Conflict doesn't go away when you ignore it - it grows. The good news? You now know that having one honest conversation early can prevent a disaster later. Your community needs leaders who face uncomfortable truths with courage and compassion. That can be you.",
        sortOrder: 2,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "fundraise_success",
        narrative: "Your bake sale raised $150 and three local businesses donated supplies! The community service day is a huge success: 60 students clean up the park, sort 200 boxes at the food bank, and paint a mural on the community center wall. The local newspaper covers the story and your school gets recognized for community impact!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "By reaching out to the community, you multiplied your impact far beyond what $200 could have done alone. You learned that asking for help isn't weakness - it's leadership!",
        walletImpact: "0.00",
        powerImpact: 25,
        meritImpact: 30,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "scale_down",
        narrative: "You scaled down to just the park cleanup with your $200 budget. It was a nice event - 20 students showed up and the park looks great. But you can't help wondering what could have been if you'd been bolder with fundraising. Still, you made a real difference in your neighborhood!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "You made a positive impact within your means. Sometimes starting small is the smartest move - and now you have experience to plan bigger next time!",
        walletImpact: "0.00",
        powerImpact: 10,
        meritImpact: 15,
        emotionalTone: "learning",
        sortOrder: 2,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "inclusive_show",
        narrative: "The group performance category is a hit! Priya performs her poetry with two friends backing her with music, and it brings the audience to tears. Shy students who never would have signed up are performing in duets, trios, and groups. The show runs long because so many people want to participate. It becomes the most-attended event in school history!",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "By reimagining the event to include everyone, you created something magical. Priya became a school celebrity for her poetry, and students who felt invisible finally felt seen. That's the power of inclusive leadership!",
        walletImpact: "0.00",
        powerImpact: 25,
        meritImpact: 25,
        emotionalTone: "triumph",
        sortOrder: 2,
      },
      {
        scenarioId: scenario4.id,
        nodeKey: "exclude_shy_setback",
        narrative: "Priya didn't sign up. Neither did a dozen other students who felt the same way. The talent show went fine, but it felt like the same old thing. After the show, Priya tells you she cried at home because she really wanted to share her poems but couldn't face the stage alone.",
        isStart: false,
        isEnd: true,
        choices: [],
        consequenceSummary: "The event happened but missed its purpose. A community event should make everyone feel welcome, not just the confident few.",
        walletImpact: "0.00",
        powerImpact: 0,
        meritImpact: -5,
        emotionalTone: "setback",
        pathForward: "Hearing Priya's story is heartbreaking, but it's teaching you something powerful: true community means creating space for EVERYONE to shine, not just those who are already comfortable. The bravest thing you can do is go back to Priya, apologize, and ask her to help you plan the next event so no one feels left out again.",
        sortOrder: 2,
      },
    ]).onConflictDoNothing();
  }
}
