/**
 * Major US cities mapped to their primary county (3-digit FIPS).
 * Used for city-aware search in the region picker.
 * Format: USPS state code → array of {city, countyFips, countyName}
 */
export interface CityEntry {
  city: string;
  countyFips: string;
  countyName: string;
}

export const CITIES_BY_STATE: Record<string, CityEntry[]> = {
  TX: [
    { city: "Austin", countyFips: "453", countyName: "Travis" },
    { city: "Houston", countyFips: "201", countyName: "Harris" },
    { city: "San Antonio", countyFips: "029", countyName: "Bexar" },
    { city: "Dallas", countyFips: "113", countyName: "Dallas" },
    { city: "Fort Worth", countyFips: "439", countyName: "Tarrant" },
    { city: "El Paso", countyFips: "141", countyName: "El Paso" },
    { city: "Arlington", countyFips: "439", countyName: "Tarrant" },
    { city: "Corpus Christi", countyFips: "355", countyName: "Nueces" },
    { city: "Plano", countyFips: "085", countyName: "Collin" },
    { city: "Laredo", countyFips: "479", countyName: "Webb" },
    { city: "Lubbock", countyFips: "303", countyName: "Lubbock" },
    { city: "Garland", countyFips: "113", countyName: "Dallas" },
    { city: "Irving", countyFips: "113", countyName: "Dallas" },
    { city: "Amarillo", countyFips: "381", countyName: "Potter" },
    { city: "Grand Prairie", countyFips: "113", countyName: "Dallas" },
    { city: "Brownsville", countyFips: "061", countyName: "Cameron" },
    { city: "McKinney", countyFips: "085", countyName: "Collin" },
    { city: "Frisco", countyFips: "085", countyName: "Collin" },
    { city: "Killeen", countyFips: "027", countyName: "Bell" },
    { city: "Pasadena", countyFips: "201", countyName: "Harris" },
    { city: "Mesquite", countyFips: "113", countyName: "Dallas" },
    { city: "McAllen", countyFips: "215", countyName: "Hidalgo" },
    { city: "Waco", countyFips: "309", countyName: "McLennan" },
    { city: "Denton", countyFips: "121", countyName: "Denton" },
    { city: "Carrollton", countyFips: "113", countyName: "Dallas" },
    { city: "Midland", countyFips: "329", countyName: "Midland" },
    { city: "Abilene", countyFips: "441", countyName: "Taylor" },
    { city: "Beaumont", countyFips: "245", countyName: "Jefferson" },
    { city: "Round Rock", countyFips: "491", countyName: "Williamson" },
    { city: "Pearland", countyFips: "039", countyName: "Brazoria" },
    { city: "Richardson", countyFips: "113", countyName: "Dallas" },
    { city: "Odessa", countyFips: "135", countyName: "Ector" },
    { city: "Lewisville", countyFips: "121", countyName: "Denton" },
    { city: "Wichita Falls", countyFips: "485", countyName: "Wichita" },
    { city: "Tyler", countyFips: "423", countyName: "Smith" },
    { city: "Edinburg", countyFips: "215", countyName: "Hidalgo" },
    { city: "College Station", countyFips: "041", countyName: "Brazos" },
    { city: "San Angelo", countyFips: "451", countyName: "Tom Green" },
    { city: "Allen", countyFips: "085", countyName: "Collin" },
    { city: "League City", countyFips: "167", countyName: "Galveston" },
    { city: "Sugar Land", countyFips: "157", countyName: "Fort Bend" },
    { city: "Longview", countyFips: "183", countyName: "Gregg" },
    { city: "Pflugerville", countyFips: "453", countyName: "Travis" },
    { city: "Kyle", countyFips: "209", countyName: "Hays" },
    { city: "Buda", countyFips: "209", countyName: "Hays" },
    { city: "Georgetown", countyFips: "491", countyName: "Williamson" },
    { city: "Cedar Park", countyFips: "491", countyName: "Williamson" },
    { city: "Manor", countyFips: "453", countyName: "Travis" },
    { city: "Bastrop", countyFips: "021", countyName: "Bastrop" },
    { city: "Lockhart", countyFips: "055", countyName: "Caldwell" },
    { city: "Luling", countyFips: "055", countyName: "Caldwell" },
    { city: "Harlingen", countyFips: "061", countyName: "Cameron" },
    { city: "San Marcos", countyFips: "209", countyName: "Hays" },
    { city: "Conroe", countyFips: "339", countyName: "Montgomery" },
    { city: "Spring", countyFips: "201", countyName: "Harris" },
    { city: "Humble", countyFips: "201", countyName: "Harris" },
    { city: "Baytown", countyFips: "201", countyName: "Harris" },
    { city: "Galveston", countyFips: "167", countyName: "Galveston" },
    { city: "Pharr", countyFips: "215", countyName: "Hidalgo" },
    { city: "Flower Mound", countyFips: "121", countyName: "Denton" },
    { city: "Rowlett", countyFips: "113", countyName: "Dallas" },
    { city: "Wylie", countyFips: "085", countyName: "Collin" },
    { city: "New Braunfels", countyFips: "091", countyName: "Comal" },
    { city: "Mission", countyFips: "215", countyName: "Hidalgo" },
    { city: "Bryan", countyFips: "041", countyName: "Brazos" },
    { city: "Weslaco", countyFips: "215", countyName: "Hidalgo" },
    { city: "Missouri City", countyFips: "157", countyName: "Fort Bend" },
    { city: "Temple", countyFips: "027", countyName: "Bell" },
    { city: "Euless", countyFips: "439", countyName: "Tarrant" },
    { city: "Cedar Hill", countyFips: "113", countyName: "Dallas" },
    { city: "Hurst", countyFips: "439", countyName: "Tarrant" },
    { city: "Katy", countyFips: "201", countyName: "Harris" },
    { city: "Mansfield", countyFips: "439", countyName: "Tarrant" },
    { city: "Nacogdoches", countyFips: "347", countyName: "Nacogdoches" },
    { city: "Texarkana", countyFips: "037", countyName: "Bowie" },
    { city: "Atascocita", countyFips: "201", countyName: "Harris" },
  ],
  IL: [
    { city: "Chicago", countyFips: "031", countyName: "Cook" },
    { city: "Aurora", countyFips: "089", countyName: "Kane" },
    { city: "Rockford", countyFips: "201", countyName: "Winnebago" },
    { city: "Joliet", countyFips: "197", countyName: "Will" },
    { city: "Naperville", countyFips: "043", countyName: "DuPage" },
    { city: "Springfield", countyFips: "167", countyName: "Sangamon" },
    { city: "Peoria", countyFips: "143", countyName: "Peoria" },
    { city: "Elgin", countyFips: "089", countyName: "Kane" },
    { city: "Waukegan", countyFips: "097", countyName: "Lake" },
    { city: "Cicero", countyFips: "031", countyName: "Cook" },
    { city: "Champaign", countyFips: "019", countyName: "Champaign" },
    { city: "Decatur", countyFips: "115", countyName: "Macon" },
    { city: "Evanston", countyFips: "031", countyName: "Cook" },
    { city: "Berwyn", countyFips: "031", countyName: "Cook" },
    { city: "Bolingbrook", countyFips: "197", countyName: "Will" },
    { city: "Schaumburg", countyFips: "031", countyName: "Cook" },
    { city: "Palatine", countyFips: "031", countyName: "Cook" },
    { city: "Skokie", countyFips: "031", countyName: "Cook" },
    { city: "Des Plaines", countyFips: "031", countyName: "Cook" },
    { city: "Arlington Heights", countyFips: "031", countyName: "Cook" },
    { city: "Orland Park", countyFips: "031", countyName: "Cook" },
    { city: "Oak Park", countyFips: "031", countyName: "Cook" },
    { city: "Harvey", countyFips: "031", countyName: "Cook" },
    { city: "Maywood", countyFips: "031", countyName: "Cook" },
    { city: "Calumet City", countyFips: "031", countyName: "Cook" },
    { city: "Urbana", countyFips: "019", countyName: "Champaign" },
  ],
  MI: [
    { city: "Detroit", countyFips: "163", countyName: "Wayne" },
    { city: "Grand Rapids", countyFips: "081", countyName: "Kent" },
    { city: "Warren", countyFips: "099", countyName: "Macomb" },
    { city: "Sterling Heights", countyFips: "099", countyName: "Macomb" },
    { city: "Lansing", countyFips: "065", countyName: "Ingham" },
    { city: "Ann Arbor", countyFips: "161", countyName: "Washtenaw" },
    { city: "Flint", countyFips: "049", countyName: "Genesee" },
    { city: "Dearborn", countyFips: "163", countyName: "Wayne" },
    { city: "Livonia", countyFips: "163", countyName: "Wayne" },
    { city: "Westland", countyFips: "163", countyName: "Wayne" },
    { city: "Troy", countyFips: "125", countyName: "Oakland" },
    { city: "Southfield", countyFips: "125", countyName: "Oakland" },
    { city: "Pontiac", countyFips: "125", countyName: "Oakland" },
    { city: "Kalamazoo", countyFips: "077", countyName: "Kalamazoo" },
    { city: "Saginaw", countyFips: "145", countyName: "Saginaw" },
    { city: "Hamtramck", countyFips: "163", countyName: "Wayne" },
    { city: "Inkster", countyFips: "163", countyName: "Wayne" },
    { city: "Lansing", countyFips: "065", countyName: "Ingham" },
    { city: "Taylor", countyFips: "163", countyName: "Wayne" },
    { city: "Royal Oak", countyFips: "125", countyName: "Oakland" },
    { city: "Farmington Hills", countyFips: "125", countyName: "Oakland" },
    { city: "Muskegon", countyFips: "121", countyName: "Muskegon" },
    { city: "Battle Creek", countyFips: "025", countyName: "Calhoun" },
  ],
  GA: [
    { city: "Atlanta", countyFips: "121", countyName: "Fulton" },
    { city: "Columbus", countyFips: "215", countyName: "Muscogee" },
    { city: "Augusta", countyFips: "245", countyName: "Richmond" },
    { city: "Macon", countyFips: "021", countyName: "Bibb" },
    { city: "Savannah", countyFips: "051", countyName: "Chatham" },
    { city: "Athens", countyFips: "059", countyName: "Clarke" },
    { city: "Sandy Springs", countyFips: "121", countyName: "Fulton" },
    { city: "Roswell", countyFips: "121", countyName: "Fulton" },
    { city: "Albany", countyFips: "095", countyName: "Dougherty" },
    { city: "Marietta", countyFips: "067", countyName: "Cobb" },
    { city: "Decatur", countyFips: "089", countyName: "DeKalb" },
    { city: "East Point", countyFips: "121", countyName: "Fulton" },
    { city: "Smyrna", countyFips: "067", countyName: "Cobb" },
    { city: "Warner Robins", countyFips: "153", countyName: "Houston" },
    { city: "Valdosta", countyFips: "185", countyName: "Lowndes" },
    { city: "Johns Creek", countyFips: "121", countyName: "Fulton" },
    { city: "Alpharetta", countyFips: "121", countyName: "Fulton" },
  ],
  MS: [
    { city: "Jackson", countyFips: "049", countyName: "Hinds" },
    { city: "Gulfport", countyFips: "047", countyName: "Harrison" },
    { city: "Southaven", countyFips: "033", countyName: "DeSoto" },
    { city: "Hattiesburg", countyFips: "035", countyName: "Forrest" },
    { city: "Biloxi", countyFips: "047", countyName: "Harrison" },
    { city: "Meridian", countyFips: "103", countyName: "Lauderdale" },
    { city: "Clarksdale", countyFips: "027", countyName: "Coahoma" },
    { city: "Greenville", countyFips: "151", countyName: "Washington" },
    { city: "Greenwood", countyFips: "083", countyName: "Leflore" },
    { city: "Cleveland", countyFips: "011", countyName: "Bolivar" },
    { city: "Tupelo", countyFips: "081", countyName: "Lee" },
    { city: "Vicksburg", countyFips: "047", countyName: "Warren" },
    { city: "Columbus", countyFips: "087", countyName: "Lowndes" },
    { city: "Pascagoula", countyFips: "059", countyName: "Jackson" },
    { city: "Natchez", countyFips: "001", countyName: "Adams" },
    { city: "Indianola", countyFips: "133", countyName: "Sunflower" },
  ],
  KY: [
    { city: "Louisville", countyFips: "111", countyName: "Jefferson" },
    { city: "Lexington", countyFips: "067", countyName: "Fayette" },
    { city: "Bowling Green", countyFips: "227", countyName: "Warren" },
    { city: "Owensboro", countyFips: "059", countyName: "Daviess" },
    { city: "Covington", countyFips: "037", countyName: "Kenton" },
    { city: "Pikeville", countyFips: "195", countyName: "Pike" },
    { city: "Prestonsburg", countyFips: "071", countyName: "Floyd" },
    { city: "Hazard", countyFips: "133", countyName: "Perry" },
    { city: "Frankfort", countyFips: "073", countyName: "Franklin" },
    { city: "Paducah", countyFips: "145", countyName: "McCracken" },
    { city: "Henderson", countyFips: "101", countyName: "Henderson" },
    { city: "Richmond", countyFips: "151", countyName: "Madison" },
    { city: "Florence", countyFips: "015", countyName: "Boone" },
  ],
  CA: [
    { city: "Los Angeles", countyFips: "037", countyName: "Los Angeles" },
    { city: "San Diego", countyFips: "073", countyName: "San Diego" },
    { city: "San Jose", countyFips: "085", countyName: "Santa Clara" },
    { city: "San Francisco", countyFips: "075", countyName: "San Francisco" },
    { city: "Fresno", countyFips: "019", countyName: "Fresno" },
    { city: "Sacramento", countyFips: "067", countyName: "Sacramento" },
    { city: "Long Beach", countyFips: "037", countyName: "Los Angeles" },
    { city: "Oakland", countyFips: "001", countyName: "Alameda" },
    { city: "Bakersfield", countyFips: "029", countyName: "Kern" },
    { city: "Anaheim", countyFips: "059", countyName: "Orange" },
    { city: "Santa Ana", countyFips: "059", countyName: "Orange" },
    { city: "Riverside", countyFips: "065", countyName: "Riverside" },
    { city: "Stockton", countyFips: "077", countyName: "San Joaquin" },
    { city: "Irvine", countyFips: "059", countyName: "Orange" },
    { city: "Chula Vista", countyFips: "073", countyName: "San Diego" },
    { city: "Fremont", countyFips: "001", countyName: "Alameda" },
    { city: "San Bernardino", countyFips: "071", countyName: "San Bernardino" },
    { city: "Modesto", countyFips: "099", countyName: "Stanislaus" },
    { city: "Fontana", countyFips: "071", countyName: "San Bernardino" },
    { city: "Moreno Valley", countyFips: "065", countyName: "Riverside" },
    { city: "Glendale", countyFips: "037", countyName: "Los Angeles" },
    { city: "Huntington Beach", countyFips: "059", countyName: "Orange" },
    { city: "Santa Clarita", countyFips: "037", countyName: "Los Angeles" },
    { city: "Garden Grove", countyFips: "059", countyName: "Orange" },
    { city: "Oceanside", countyFips: "073", countyName: "San Diego" },
    { city: "Rancho Cucamonga", countyFips: "071", countyName: "San Bernardino" },
    { city: "Santa Rosa", countyFips: "097", countyName: "Sonoma" },
    { city: "Ontario", countyFips: "071", countyName: "San Bernardino" },
    { city: "Elk Grove", countyFips: "067", countyName: "Sacramento" },
    { city: "Salinas", countyFips: "053", countyName: "Monterey" },
    { city: "Pomona", countyFips: "037", countyName: "Los Angeles" },
    { city: "Torrance", countyFips: "037", countyName: "Los Angeles" },
    { city: "Pasadena", countyFips: "037", countyName: "Los Angeles" },
    { city: "Escondido", countyFips: "073", countyName: "San Diego" },
    { city: "Sunnyvale", countyFips: "085", countyName: "Santa Clara" },
    { city: "Hayward", countyFips: "001", countyName: "Alameda" },
    { city: "Lancaster", countyFips: "037", countyName: "Los Angeles" },
    { city: "Palmdale", countyFips: "037", countyName: "Los Angeles" },
    { city: "Compton", countyFips: "037", countyName: "Los Angeles" },
    { city: "Inglewood", countyFips: "037", countyName: "Los Angeles" },
    { city: "Berkeley", countyFips: "001", countyName: "Alameda" },
    { city: "Richmond", countyFips: "013", countyName: "Contra Costa" },
    { city: "Concord", countyFips: "013", countyName: "Contra Costa" },
    { city: "Vallejo", countyFips: "095", countyName: "Solano" },
    { city: "Roseville", countyFips: "061", countyName: "Placer" },
    { city: "Visalia", countyFips: "107", countyName: "Tulare" },
    { city: "Oxnard", countyFips: "111", countyName: "Ventura" },
    { city: "Victorville", countyFips: "071", countyName: "San Bernardino" },
    { city: "Santa Clarita", countyFips: "037", countyName: "Los Angeles" },
    { city: "San Buenaventura", countyFips: "111", countyName: "Ventura" },
    { city: "Antioch", countyFips: "013", countyName: "Contra Costa" },
    { city: "Santa Clara", countyFips: "085", countyName: "Santa Clara" },
    { city: "El Monte", countyFips: "037", countyName: "Los Angeles" },
    { city: "Downey", countyFips: "037", countyName: "Los Angeles" },
    { city: "Murrieta", countyFips: "065", countyName: "Riverside" },
    { city: "Temecula", countyFips: "065", countyName: "Riverside" },
    { city: "Costa Mesa", countyFips: "059", countyName: "Orange" },
    { city: "San Mateo", countyFips: "081", countyName: "San Mateo" },
    { city: "Daly City", countyFips: "081", countyName: "San Mateo" },
    { city: "San Leandro", countyFips: "001", countyName: "Alameda" },
  ],
  NY: [
    { city: "New York City", countyFips: "061", countyName: "New York (Manhattan)" },
    { city: "Manhattan", countyFips: "061", countyName: "New York" },
    { city: "Brooklyn", countyFips: "047", countyName: "Kings" },
    { city: "Queens", countyFips: "081", countyName: "Queens" },
    { city: "Bronx", countyFips: "005", countyName: "Bronx" },
    { city: "Staten Island", countyFips: "085", countyName: "Richmond" },
    { city: "Buffalo", countyFips: "029", countyName: "Erie" },
    { city: "Rochester", countyFips: "055", countyName: "Monroe" },
    { city: "Yonkers", countyFips: "119", countyName: "Westchester" },
    { city: "Syracuse", countyFips: "067", countyName: "Onondaga" },
    { city: "Albany", countyFips: "001", countyName: "Albany" },
    { city: "New Rochelle", countyFips: "119", countyName: "Westchester" },
    { city: "Mount Vernon", countyFips: "119", countyName: "Westchester" },
    { city: "Schenectady", countyFips: "093", countyName: "Schenectady" },
    { city: "Utica", countyFips: "065", countyName: "Oneida" },
    { city: "Binghamton", countyFips: "007", countyName: "Broome" },
  ],
  FL: [
    { city: "Jacksonville", countyFips: "031", countyName: "Duval" },
    { city: "Miami", countyFips: "086", countyName: "Miami-Dade" },
    { city: "Tampa", countyFips: "057", countyName: "Hillsborough" },
    { city: "Orlando", countyFips: "095", countyName: "Orange" },
    { city: "St. Petersburg", countyFips: "103", countyName: "Pinellas" },
    { city: "Hialeah", countyFips: "086", countyName: "Miami-Dade" },
    { city: "Tallahassee", countyFips: "073", countyName: "Leon" },
    { city: "Fort Lauderdale", countyFips: "011", countyName: "Broward" },
    { city: "Port St. Lucie", countyFips: "111", countyName: "St. Lucie" },
    { city: "Cape Coral", countyFips: "071", countyName: "Lee" },
    { city: "Pembroke Pines", countyFips: "011", countyName: "Broward" },
    { city: "Hollywood", countyFips: "011", countyName: "Broward" },
    { city: "Gainesville", countyFips: "001", countyName: "Alachua" },
    { city: "Coral Springs", countyFips: "011", countyName: "Broward" },
    { city: "Clearwater", countyFips: "103", countyName: "Pinellas" },
    { city: "Miami Gardens", countyFips: "086", countyName: "Miami-Dade" },
    { city: "Lakeland", countyFips: "105", countyName: "Polk" },
    { city: "Pompano Beach", countyFips: "011", countyName: "Broward" },
    { city: "West Palm Beach", countyFips: "099", countyName: "Palm Beach" },
    { city: "Davie", countyFips: "011", countyName: "Broward" },
    { city: "Sunrise", countyFips: "011", countyName: "Broward" },
    { city: "Miramar", countyFips: "011", countyName: "Broward" },
    { city: "Daytona Beach", countyFips: "127", countyName: "Volusia" },
    { city: "Palm Bay", countyFips: "009", countyName: "Brevard" },
    { city: "Miami Beach", countyFips: "086", countyName: "Miami-Dade" },
    { city: "Deltona", countyFips: "127", countyName: "Volusia" },
    { city: "Plantation", countyFips: "011", countyName: "Broward" },
    { city: "Tallahassee", countyFips: "073", countyName: "Leon" },
    { city: "Fort Myers", countyFips: "071", countyName: "Lee" },
    { city: "Boca Raton", countyFips: "099", countyName: "Palm Beach" },
    { city: "Ocala", countyFips: "083", countyName: "Marion" },
  ],
  OH: [
    { city: "Columbus", countyFips: "049", countyName: "Franklin" },
    { city: "Cleveland", countyFips: "035", countyName: "Cuyahoga" },
    { city: "Cincinnati", countyFips: "061", countyName: "Hamilton" },
    { city: "Toledo", countyFips: "095", countyName: "Lucas" },
    { city: "Akron", countyFips: "153", countyName: "Summit" },
    { city: "Dayton", countyFips: "113", countyName: "Montgomery" },
    { city: "Parma", countyFips: "035", countyName: "Cuyahoga" },
    { city: "Canton", countyFips: "151", countyName: "Stark" },
    { city: "Lorain", countyFips: "093", countyName: "Lorain" },
    { city: "Hamilton", countyFips: "061", countyName: "Butler" },
    { city: "Youngstown", countyFips: "155", countyName: "Mahoning" },
    { city: "Springfield", countyFips: "023", countyName: "Clark" },
    { city: "Lakewood", countyFips: "035", countyName: "Cuyahoga" },
    { city: "Elyria", countyFips: "093", countyName: "Lorain" },
    { city: "Mentor", countyFips: "085", countyName: "Lake" },
    { city: "Cleveland Heights", countyFips: "035", countyName: "Cuyahoga" },
    { city: "Euclid", countyFips: "035", countyName: "Cuyahoga" },
  ],
  PA: [
    { city: "Philadelphia", countyFips: "101", countyName: "Philadelphia" },
    { city: "Pittsburgh", countyFips: "003", countyName: "Allegheny" },
    { city: "Allentown", countyFips: "077", countyName: "Lehigh" },
    { city: "Erie", countyFips: "049", countyName: "Erie" },
    { city: "Reading", countyFips: "011", countyName: "Berks" },
    { city: "Scranton", countyFips: "069", countyName: "Lackawanna" },
    { city: "Bethlehem", countyFips: "095", countyName: "Northampton" },
    { city: "Lancaster", countyFips: "071", countyName: "Lancaster" },
    { city: "Harrisburg", countyFips: "043", countyName: "Dauphin" },
    { city: "York", countyFips: "133", countyName: "York" },
    { city: "Altoona", countyFips: "013", countyName: "Blair" },
    { city: "Chester", countyFips: "029", countyName: "Delaware" },
    { city: "Wilkes-Barre", countyFips: "079", countyName: "Luzerne" },
  ],
  AZ: [
    { city: "Phoenix", countyFips: "013", countyName: "Maricopa" },
    { city: "Tucson", countyFips: "019", countyName: "Pima" },
    { city: "Mesa", countyFips: "013", countyName: "Maricopa" },
    { city: "Chandler", countyFips: "013", countyName: "Maricopa" },
    { city: "Scottsdale", countyFips: "013", countyName: "Maricopa" },
    { city: "Gilbert", countyFips: "013", countyName: "Maricopa" },
    { city: "Glendale", countyFips: "013", countyName: "Maricopa" },
    { city: "Tempe", countyFips: "013", countyName: "Maricopa" },
    { city: "Peoria", countyFips: "013", countyName: "Maricopa" },
    { city: "Surprise", countyFips: "013", countyName: "Maricopa" },
    { city: "Yuma", countyFips: "027", countyName: "Yuma" },
    { city: "Flagstaff", countyFips: "005", countyName: "Coconino" },
    { city: "Avondale", countyFips: "013", countyName: "Maricopa" },
    { city: "Goodyear", countyFips: "013", countyName: "Maricopa" },
    { city: "Buckeye", countyFips: "013", countyName: "Maricopa" },
    { city: "Sierra Vista", countyFips: "003", countyName: "Cochise" },
    { city: "Queen Creek", countyFips: "013", countyName: "Maricopa" },
    { city: "El Mirage", countyFips: "013", countyName: "Maricopa" },
    { city: "Apache Junction", countyFips: "021", countyName: "Pinal" },
    { city: "Casa Grande", countyFips: "021", countyName: "Pinal" },
  ],
  NC: [
    { city: "Charlotte", countyFips: "119", countyName: "Mecklenburg" },
    { city: "Raleigh", countyFips: "183", countyName: "Wake" },
    { city: "Greensboro", countyFips: "081", countyName: "Guilford" },
    { city: "Durham", countyFips: "063", countyName: "Durham" },
    { city: "Winston-Salem", countyFips: "067", countyName: "Forsyth" },
    { city: "Fayetteville", countyFips: "051", countyName: "Cumberland" },
    { city: "Cary", countyFips: "183", countyName: "Wake" },
    { city: "Wilmington", countyFips: "129", countyName: "New Hanover" },
    { city: "High Point", countyFips: "081", countyName: "Guilford" },
    { city: "Asheville", countyFips: "021", countyName: "Buncombe" },
    { city: "Concord", countyFips: "025", countyName: "Cabarrus" },
    { city: "Gastonia", countyFips: "071", countyName: "Gaston" },
    { city: "Chapel Hill", countyFips: "135", countyName: "Orange" },
    { city: "Rocky Mount", countyFips: "127", countyName: "Nash" },
    { city: "Jacksonville", countyFips: "133", countyName: "Onslow" },
    { city: "Burlington", countyFips: "001", countyName: "Alamance" },
    { city: "Greenville", countyFips: "065", countyName: "Pitt" },
  ],
  TN: [
    { city: "Nashville", countyFips: "037", countyName: "Davidson" },
    { city: "Memphis", countyFips: "157", countyName: "Shelby" },
    { city: "Knoxville", countyFips: "093", countyName: "Knox" },
    { city: "Chattanooga", countyFips: "065", countyName: "Hamilton" },
    { city: "Clarksville", countyFips: "125", countyName: "Montgomery" },
    { city: "Murfreesboro", countyFips: "149", countyName: "Rutherford" },
    { city: "Jackson", countyFips: "113", countyName: "Madison" },
    { city: "Franklin", countyFips: "187", countyName: "Williamson" },
    { city: "Hendersonville", countyFips: "165", countyName: "Sumner" },
    { city: "Johnson City", countyFips: "019", countyName: "Carter" },
    { city: "Kingsport", countyFips: "163", countyName: "Sullivan" },
    { city: "Bartlett", countyFips: "157", countyName: "Shelby" },
    { city: "Smyrna", countyFips: "149", countyName: "Rutherford" },
    { city: "Collierville", countyFips: "157", countyName: "Shelby" },
  ],
  LA: [
    { city: "New Orleans", countyFips: "071", countyName: "Orleans" },
    { city: "Baton Rouge", countyFips: "033", countyName: "East Baton Rouge" },
    { city: "Shreveport", countyFips: "017", countyName: "Caddo" },
    { city: "Metairie", countyFips: "051", countyName: "Jefferson" },
    { city: "Lafayette", countyFips: "055", countyName: "Lafayette" },
    { city: "Lake Charles", countyFips: "019", countyName: "Calcasieu" },
    { city: "Monroe", countyFips: "073", countyName: "Ouachita" },
    { city: "Alexandria", countyFips: "079", countyName: "Rapides" },
    { city: "New Iberia", countyFips: "045", countyName: "Iberia" },
    { city: "Houma", countyFips: "109", countyName: "Terrebonne" },
    { city: "Kenner", countyFips: "051", countyName: "Jefferson" },
    { city: "Bossier City", countyFips: "015", countyName: "Bossier" },
  ],
  AL: [
    { city: "Birmingham", countyFips: "073", countyName: "Jefferson" },
    { city: "Montgomery", countyFips: "101", countyName: "Montgomery" },
    { city: "Huntsville", countyFips: "089", countyName: "Madison" },
    { city: "Mobile", countyFips: "097", countyName: "Mobile" },
    { city: "Tuscaloosa", countyFips: "125", countyName: "Tuscaloosa" },
    { city: "Dothan", countyFips: "069", countyName: "Houston" },
    { city: "Selma", countyFips: "047", countyName: "Dallas" },
    { city: "Decatur", countyFips: "083", countyName: "Morgan" },
    { city: "Gadsden", countyFips: "055", countyName: "Etowah" },
    { city: "Anniston", countyFips: "015", countyName: "Calhoun" },
    { city: "Florence", countyFips: "077", countyName: "Lauderdale" },
    { city: "Auburn", countyFips: "081", countyName: "Lee" },
    { city: "Hoover", countyFips: "073", countyName: "Jefferson" },
  ],
  NJ: [
    { city: "Newark", countyFips: "013", countyName: "Essex" },
    { city: "Jersey City", countyFips: "017", countyName: "Hudson" },
    { city: "Paterson", countyFips: "031", countyName: "Passaic" },
    { city: "Elizabeth", countyFips: "039", countyName: "Union" },
    { city: "Trenton", countyFips: "021", countyName: "Mercer" },
    { city: "Camden", countyFips: "007", countyName: "Camden" },
    { city: "Clifton", countyFips: "031", countyName: "Passaic" },
    { city: "Passaic", countyFips: "031", countyName: "Passaic" },
    { city: "East Orange", countyFips: "013", countyName: "Essex" },
    { city: "Irvington", countyFips: "013", countyName: "Essex" },
    { city: "Union City", countyFips: "017", countyName: "Hudson" },
  ],
  WA: [
    { city: "Seattle", countyFips: "033", countyName: "King" },
    { city: "Spokane", countyFips: "063", countyName: "Spokane" },
    { city: "Tacoma", countyFips: "053", countyName: "Pierce" },
    { city: "Vancouver", countyFips: "011", countyName: "Clark" },
    { city: "Bellevue", countyFips: "033", countyName: "King" },
    { city: "Kirkland", countyFips: "033", countyName: "King" },
    { city: "Renton", countyFips: "033", countyName: "King" },
    { city: "Redmond", countyFips: "033", countyName: "King" },
    { city: "Everett", countyFips: "061", countyName: "Snohomish" },
    { city: "Kent", countyFips: "033", countyName: "King" },
    { city: "Bellingham", countyFips: "073", countyName: "Whatcom" },
    { city: "Kennewick", countyFips: "005", countyName: "Benton" },
    { city: "Yakima", countyFips: "077", countyName: "Yakima" },
    { city: "Federal Way", countyFips: "033", countyName: "King" },
    { city: "Marysville", countyFips: "061", countyName: "Snohomish" },
    { city: "Auburn", countyFips: "033", countyName: "King" },
  ],
  CO: [
    { city: "Denver", countyFips: "031", countyName: "Denver" },
    { city: "Colorado Springs", countyFips: "041", countyName: "El Paso" },
    { city: "Aurora", countyFips: "035", countyName: "Arapahoe" },
    { city: "Fort Collins", countyFips: "069", countyName: "Larimer" },
    { city: "Lakewood", countyFips: "059", countyName: "Jefferson" },
    { city: "Thornton", countyFips: "001", countyName: "Adams" },
    { city: "Pueblo", countyFips: "101", countyName: "Pueblo" },
    { city: "Westminster", countyFips: "001", countyName: "Adams" },
    { city: "Boulder", countyFips: "013", countyName: "Boulder" },
    { city: "Centennial", countyFips: "035", countyName: "Arapahoe" },
    { city: "Highlands Ranch", countyFips: "035", countyName: "Douglas" },
    { city: "Arvada", countyFips: "059", countyName: "Jefferson" },
    { city: "Greeley", countyFips: "123", countyName: "Weld" },
    { city: "Longmont", countyFips: "013", countyName: "Boulder" },
    { city: "Loveland", countyFips: "069", countyName: "Larimer" },
    { city: "Broomfield", countyFips: "014", countyName: "Broomfield" },
  ],
  MN: [
    { city: "Minneapolis", countyFips: "053", countyName: "Hennepin" },
    { city: "St. Paul", countyFips: "123", countyName: "Ramsey" },
    { city: "Rochester", countyFips: "055", countyName: "Olmsted" },
    { city: "Duluth", countyFips: "137", countyName: "St. Louis" },
    { city: "Bloomington", countyFips: "053", countyName: "Hennepin" },
    { city: "Brooklyn Park", countyFips: "053", countyName: "Hennepin" },
    { city: "Plymouth", countyFips: "053", countyName: "Hennepin" },
    { city: "Maple Grove", countyFips: "053", countyName: "Hennepin" },
    { city: "Woodbury", countyFips: "163", countyName: "Washington" },
    { city: "St. Cloud", countyFips: "145", countyName: "Stearns" },
    { city: "Coon Rapids", countyFips: "003", countyName: "Anoka" },
    { city: "Eagan", countyFips: "037", countyName: "Dakota" },
    { city: "Apple Valley", countyFips: "037", countyName: "Dakota" },
    { city: "Edina", countyFips: "053", countyName: "Hennepin" },
    { city: "Burnsville", countyFips: "037", countyName: "Dakota" },
    { city: "Lakeville", countyFips: "037", countyName: "Dakota" },
    { city: "Mankato", countyFips: "013", countyName: "Blue Earth" },
  ],
  MO: [
    { city: "Kansas City", countyFips: "095", countyName: "Jackson" },
    { city: "St. Louis", countyFips: "510", countyName: "St. Louis City" },
    { city: "Springfield", countyFips: "043", countyName: "Greene" },
    { city: "Columbia", countyFips: "019", countyName: "Boone" },
    { city: "Independence", countyFips: "095", countyName: "Jackson" },
    { city: "Joplin", countyFips: "145", countyName: "Jasper" },
    { city: "St. Joseph", countyFips: "021", countyName: "Buchanan" },
    { city: "Lee's Summit", countyFips: "095", countyName: "Jackson" },
    { city: "O'Fallon", countyFips: "183", countyName: "St. Charles" },
    { city: "St. Charles", countyFips: "183", countyName: "St. Charles" },
    { city: "St. Peters", countyFips: "183", countyName: "St. Charles" },
  ],
  IN: [
    { city: "Indianapolis", countyFips: "097", countyName: "Marion" },
    { city: "Fort Wayne", countyFips: "003", countyName: "Allen" },
    { city: "Evansville", countyFips: "163", countyName: "Vanderburgh" },
    { city: "South Bend", countyFips: "141", countyName: "St. Joseph" },
    { city: "Carmel", countyFips: "057", countyName: "Hamilton" },
    { city: "Fishers", countyFips: "057", countyName: "Hamilton" },
    { city: "Bloomington", countyFips: "105", countyName: "Monroe" },
    { city: "Hammond", countyFips: "089", countyName: "Lake" },
    { city: "Gary", countyFips: "089", countyName: "Lake" },
    { city: "Muncie", countyFips: "035", countyName: "Delaware" },
    { city: "Terre Haute", countyFips: "167", countyName: "Vigo" },
    { city: "Anderson", countyFips: "095", countyName: "Madison" },
    { city: "Noblesville", countyFips: "057", countyName: "Hamilton" },
  ],
  WI: [
    { city: "Milwaukee", countyFips: "079", countyName: "Milwaukee" },
    { city: "Madison", countyFips: "025", countyName: "Dane" },
    { city: "Green Bay", countyFips: "009", countyName: "Brown" },
    { city: "Kenosha", countyFips: "059", countyName: "Kenosha" },
    { city: "Racine", countyFips: "101", countyName: "Racine" },
    { city: "Appleton", countyFips: "139", countyName: "Outagamie" },
    { city: "Waukesha", countyFips: "133", countyName: "Waukesha" },
    { city: "Oshkosh", countyFips: "139", countyName: "Winnebago" },
    { city: "Eau Claire", countyFips: "035", countyName: "Eau Claire" },
    { city: "Janesville", countyFips: "105", countyName: "Rock" },
    { city: "West Allis", countyFips: "079", countyName: "Milwaukee" },
    { city: "La Crosse", countyFips: "063", countyName: "La Crosse" },
    { city: "Sheboygan", countyFips: "117", countyName: "Sheboygan" },
  ],
  OR: [
    { city: "Portland", countyFips: "051", countyName: "Multnomah" },
    { city: "Salem", countyFips: "047", countyName: "Marion" },
    { city: "Eugene", countyFips: "039", countyName: "Lane" },
    { city: "Gresham", countyFips: "051", countyName: "Multnomah" },
    { city: "Hillsboro", countyFips: "067", countyName: "Washington" },
    { city: "Beaverton", countyFips: "067", countyName: "Washington" },
    { city: "Bend", countyFips: "017", countyName: "Deschutes" },
    { city: "Medford", countyFips: "029", countyName: "Jackson" },
    { city: "Springfield", countyFips: "039", countyName: "Lane" },
    { city: "Corvallis", countyFips: "043", countyName: "Benton" },
    { city: "Albany", countyFips: "043", countyName: "Linn" },
    { city: "Tigard", countyFips: "067", countyName: "Washington" },
  ],
  NV: [
    { city: "Las Vegas", countyFips: "003", countyName: "Clark" },
    { city: "Henderson", countyFips: "003", countyName: "Clark" },
    { city: "Reno", countyFips: "031", countyName: "Washoe" },
    { city: "North Las Vegas", countyFips: "003", countyName: "Clark" },
    { city: "Sparks", countyFips: "031", countyName: "Washoe" },
    { city: "Enterprise", countyFips: "003", countyName: "Clark" },
    { city: "Paradise", countyFips: "003", countyName: "Clark" },
    { city: "Spring Valley", countyFips: "003", countyName: "Clark" },
    { city: "Sunrise Manor", countyFips: "003", countyName: "Clark" },
  ],
  SC: [
    { city: "Columbia", countyFips: "079", countyName: "Richland" },
    { city: "Charleston", countyFips: "019", countyName: "Charleston" },
    { city: "North Charleston", countyFips: "019", countyName: "Charleston" },
    { city: "Greenville", countyFips: "045", countyName: "Greenville" },
    { city: "Rock Hill", countyFips: "091", countyName: "York" },
    { city: "Spartanburg", countyFips: "083", countyName: "Spartanburg" },
    { city: "Myrtle Beach", countyFips: "051", countyName: "Horry" },
    { city: "Hilton Head Island", countyFips: "013", countyName: "Beaufort" },
    { city: "Summerville", countyFips: "019", countyName: "Dorchester" },
    { city: "Florence", countyFips: "041", countyName: "Florence" },
    { city: "Anderson", countyFips: "007", countyName: "Anderson" },
  ],
  VA: [
    { city: "Virginia Beach", countyFips: "810", countyName: "Virginia Beach City" },
    { city: "Norfolk", countyFips: "710", countyName: "Norfolk City" },
    { city: "Richmond", countyFips: "760", countyName: "Richmond City" },
    { city: "Alexandria", countyFips: "510", countyName: "Alexandria City" },
    { city: "Roanoke", countyFips: "770", countyName: "Roanoke City" },
    { city: "Chesapeake", countyFips: "550", countyName: "Chesapeake City" },
    { city: "Portsmouth", countyFips: "740", countyName: "Portsmouth City" },
    { city: "Newport News", countyFips: "700", countyName: "Newport News City" },
    { city: "Hampton", countyFips: "650", countyName: "Hampton City" },
    { city: "Charlottesville", countyFips: "540", countyName: "Charlottesville City" },
    { city: "Lynchburg", countyFips: "680", countyName: "Lynchburg City" },
    { city: "Harrisonburg", countyFips: "660", countyName: "Harrisonburg City" },
    { city: "Arlington", countyFips: "013", countyName: "Arlington" },
    { city: "Fairfax", countyFips: "059", countyName: "Fairfax" },
  ],
  MD: [
    { city: "Baltimore", countyFips: "510", countyName: "Baltimore City" },
    { city: "Columbia", countyFips: "027", countyName: "Howard" },
    { city: "Germantown", countyFips: "031", countyName: "Montgomery" },
    { city: "Silver Spring", countyFips: "031", countyName: "Montgomery" },
    { city: "Frederick", countyFips: "021", countyName: "Frederick" },
    { city: "Rockville", countyFips: "031", countyName: "Montgomery" },
    { city: "Bethesda", countyFips: "031", countyName: "Montgomery" },
    { city: "Towson", countyFips: "005", countyName: "Baltimore" },
    { city: "Ellicott City", countyFips: "027", countyName: "Howard" },
    { city: "Annapolis", countyFips: "003", countyName: "Anne Arundel" },
    { city: "Waldorf", countyFips: "017", countyName: "Charles" },
    { city: "Bowie", countyFips: "033", countyName: "Prince George's" },
    { city: "Gaithersburg", countyFips: "031", countyName: "Montgomery" },
  ],
  MA: [
    { city: "Boston", countyFips: "025", countyName: "Suffolk" },
    { city: "Worcester", countyFips: "027", countyName: "Worcester" },
    { city: "Springfield", countyFips: "013", countyName: "Hampden" },
    { city: "Cambridge", countyFips: "017", countyName: "Middlesex" },
    { city: "Lowell", countyFips: "017", countyName: "Middlesex" },
    { city: "Brockton", countyFips: "023", countyName: "Plymouth" },
    { city: "New Bedford", countyFips: "005", countyName: "Bristol" },
    { city: "Quincy", countyFips: "021", countyName: "Norfolk" },
    { city: "Lynn", countyFips: "009", countyName: "Essex" },
    { city: "Fall River", countyFips: "005", countyName: "Bristol" },
    { city: "Newton", countyFips: "017", countyName: "Middlesex" },
    { city: "Lawrence", countyFips: "009", countyName: "Essex" },
    { city: "Somerville", countyFips: "017", countyName: "Middlesex" },
    { city: "Framingham", countyFips: "017", countyName: "Middlesex" },
  ],
  OK: [
    { city: "Oklahoma City", countyFips: "109", countyName: "Oklahoma" },
    { city: "Tulsa", countyFips: "143", countyName: "Tulsa" },
    { city: "Norman", countyFips: "109", countyName: "Oklahoma" },
    { city: "Broken Arrow", countyFips: "143", countyName: "Tulsa" },
    { city: "Lawton", countyFips: "031", countyName: "Comanche" },
    { city: "Edmond", countyFips: "109", countyName: "Oklahoma" },
    { city: "Moore", countyFips: "109", countyName: "Oklahoma" },
    { city: "Midwest City", countyFips: "109", countyName: "Oklahoma" },
    { city: "Stillwater", countyFips: "119", countyName: "Payne" },
    { city: "Muskogee", countyFips: "101", countyName: "Muskogee" },
  ],
  AR: [
    { city: "Little Rock", countyFips: "119", countyName: "Pulaski" },
    { city: "Fort Smith", countyFips: "033", countyName: "Sebastian" },
    { city: "Fayetteville", countyFips: "143", countyName: "Washington" },
    { city: "Jonesboro", countyFips: "031", countyName: "Craighead" },
    { city: "North Little Rock", countyFips: "119", countyName: "Pulaski" },
    { city: "Conway", countyFips: "045", countyName: "Faulkner" },
    { city: "Rogers", countyFips: "007", countyName: "Benton" },
    { city: "Springdale", countyFips: "143", countyName: "Washington" },
    { city: "Pine Bluff", countyFips: "069", countyName: "Jefferson" },
  ],
  NM: [
    { city: "Albuquerque", countyFips: "001", countyName: "Bernalillo" },
    { city: "Las Cruces", countyFips: "013", countyName: "Doña Ana" },
    { city: "Rio Rancho", countyFips: "043", countyName: "Sandoval" },
    { city: "Santa Fe", countyFips: "049", countyName: "Santa Fe" },
    { city: "Roswell", countyFips: "005", countyName: "Chaves" },
    { city: "Farmington", countyFips: "045", countyName: "San Juan" },
    { city: "Clovis", countyFips: "009", countyName: "Curry" },
    { city: "Hobbs", countyFips: "025", countyName: "Lea" },
  ],
  UT: [
    { city: "Salt Lake City", countyFips: "035", countyName: "Salt Lake" },
    { city: "West Valley City", countyFips: "035", countyName: "Salt Lake" },
    { city: "Provo", countyFips: "049", countyName: "Utah" },
    { city: "West Jordan", countyFips: "035", countyName: "Salt Lake" },
    { city: "Orem", countyFips: "049", countyName: "Utah" },
    { city: "Sandy", countyFips: "035", countyName: "Salt Lake" },
    { city: "Ogden", countyFips: "057", countyName: "Weber" },
    { city: "St. George", countyFips: "053", countyName: "Washington" },
    { city: "Layton", countyFips: "011", countyName: "Davis" },
    { city: "Taylorsville", countyFips: "035", countyName: "Salt Lake" },
    { city: "South Jordan", countyFips: "035", countyName: "Salt Lake" },
    { city: "Lehi", countyFips: "049", countyName: "Utah" },
  ],
  KS: [
    { city: "Wichita", countyFips: "173", countyName: "Sedgwick" },
    { city: "Overland Park", countyFips: "091", countyName: "Johnson" },
    { city: "Kansas City", countyFips: "209", countyName: "Wyandotte" },
    { city: "Topeka", countyFips: "177", countyName: "Shawnee" },
    { city: "Olathe", countyFips: "091", countyName: "Johnson" },
    { city: "Lawrence", countyFips: "045", countyName: "Douglas" },
    { city: "Shawnee", countyFips: "091", countyName: "Johnson" },
    { city: "Manhattan", countyFips: "061", countyName: "Riley" },
    { city: "Lenexa", countyFips: "091", countyName: "Johnson" },
    { city: "Salina", countyFips: "169", countyName: "Saline" },
  ],
  NE: [
    { city: "Omaha", countyFips: "055", countyName: "Douglas" },
    { city: "Lincoln", countyFips: "109", countyName: "Lancaster" },
    { city: "Bellevue", countyFips: "055", countyName: "Sarpy" },
    { city: "Grand Island", countyFips: "081", countyName: "Hall" },
    { city: "Kearney", countyFips: "099", countyName: "Buffalo" },
    { city: "Fremont", countyFips: "053", countyName: "Dodge" },
    { city: "Norfolk", countyFips: "119", countyName: "Madison" },
  ],
  IA: [
    { city: "Des Moines", countyFips: "153", countyName: "Polk" },
    { city: "Cedar Rapids", countyFips: "113", countyName: "Linn" },
    { city: "Davenport", countyFips: "061", countyName: "Scott" },
    { city: "Sioux City", countyFips: "193", countyName: "Woodbury" },
    { city: "Iowa City", countyFips: "103", countyName: "Johnson" },
    { city: "Waterloo", countyFips: "013", countyName: "Black Hawk" },
    { city: "Council Bluffs", countyFips: "155", countyName: "Pottawattamie" },
    { city: "Ames", countyFips: "169", countyName: "Story" },
    { city: "Dubuque", countyFips: "061", countyName: "Dubuque" },
  ],
  WV: [
    { city: "Charleston", countyFips: "039", countyName: "Kanawha" },
    { city: "Huntington", countyFips: "011", countyName: "Cabell" },
    { city: "Morgantown", countyFips: "061", countyName: "Monongalia" },
    { city: "Beckley", countyFips: "081", countyName: "Raleigh" },
    { city: "Wheeling", countyFips: "069", countyName: "Ohio" },
    { city: "Parkersburg", countyFips: "107", countyName: "Wood" },
    { city: "Clarksburg", countyFips: "017", countyName: "Harrison" },
  ],
  CT: [
    { city: "Bridgeport", countyFips: "001", countyName: "Fairfield" },
    { city: "New Haven", countyFips: "009", countyName: "New Haven" },
    { city: "Stamford", countyFips: "001", countyName: "Fairfield" },
    { city: "Hartford", countyFips: "003", countyName: "Hartford" },
    { city: "Waterbury", countyFips: "009", countyName: "New Haven" },
    { city: "Norwalk", countyFips: "001", countyName: "Fairfield" },
    { city: "Danbury", countyFips: "001", countyName: "Fairfield" },
    { city: "New Britain", countyFips: "003", countyName: "Hartford" },
    { city: "Meriden", countyFips: "009", countyName: "New Haven" },
    { city: "West Haven", countyFips: "009", countyName: "New Haven" },
  ],
  MT: [
    { city: "Billings", countyFips: "111", countyName: "Yellowstone" },
    { city: "Missoula", countyFips: "063", countyName: "Missoula" },
    { city: "Great Falls", countyFips: "013", countyName: "Cascade" },
    { city: "Bozeman", countyFips: "031", countyName: "Gallatin" },
    { city: "Butte", countyFips: "093", countyName: "Silver Bow" },
    { city: "Helena", countyFips: "049", countyName: "Lewis and Clark" },
    { city: "Kalispell", countyFips: "029", countyName: "Flathead" },
  ],
  ID: [
    { city: "Boise", countyFips: "001", countyName: "Ada" },
    { city: "Meridian", countyFips: "001", countyName: "Ada" },
    { city: "Nampa", countyFips: "027", countyName: "Canyon" },
    { city: "Idaho Falls", countyFips: "019", countyName: "Bonneville" },
    { city: "Pocatello", countyFips: "005", countyName: "Bannock" },
    { city: "Caldwell", countyFips: "027", countyName: "Canyon" },
    { city: "Twin Falls", countyFips: "083", countyName: "Twin Falls" },
    { city: "Coeur d'Alene", countyFips: "055", countyName: "Kootenai" },
  ],
  SD: [
    { city: "Sioux Falls", countyFips: "099", countyName: "Minnehaha" },
    { city: "Rapid City", countyFips: "103", countyName: "Pennington" },
    { city: "Aberdeen", countyFips: "013", countyName: "Brown" },
    { city: "Brookings", countyFips: "011", countyName: "Brookings" },
    { city: "Watertown", countyFips: "029", countyName: "Codington" },
  ],
  ND: [
    { city: "Fargo", countyFips: "017", countyName: "Cass" },
    { city: "Bismarck", countyFips: "015", countyName: "Burleigh" },
    { city: "Grand Forks", countyFips: "035", countyName: "Grand Forks" },
    { city: "Minot", countyFips: "049", countyName: "Ward" },
    { city: "West Fargo", countyFips: "017", countyName: "Cass" },
  ],
  HI: [
    { city: "Honolulu", countyFips: "003", countyName: "Honolulu" },
    { city: "Hilo", countyFips: "001", countyName: "Hawaii" },
    { city: "Kailua", countyFips: "003", countyName: "Honolulu" },
    { city: "Pearl City", countyFips: "003", countyName: "Honolulu" },
    { city: "Waipahu", countyFips: "003", countyName: "Honolulu" },
    { city: "Kaneohe", countyFips: "003", countyName: "Honolulu" },
    { city: "Kihei", countyFips: "009", countyName: "Maui" },
  ],
  AK: [
    { city: "Anchorage", countyFips: "020", countyName: "Anchorage" },
    { city: "Fairbanks", countyFips: "090", countyName: "Fairbanks North Star" },
    { city: "Juneau", countyFips: "110", countyName: "Juneau" },
    { city: "Sitka", countyFips: "220", countyName: "Sitka" },
    { city: "Ketchikan", countyFips: "130", countyName: "Ketchikan Gateway" },
  ],
  ME: [
    { city: "Portland", countyFips: "005", countyName: "Cumberland" },
    { city: "Lewiston", countyFips: "001", countyName: "Androscoggin" },
    { city: "Bangor", countyFips: "019", countyName: "Penobscot" },
    { city: "South Portland", countyFips: "005", countyName: "Cumberland" },
    { city: "Auburn", countyFips: "001", countyName: "Androscoggin" },
  ],
  NH: [
    { city: "Manchester", countyFips: "011", countyName: "Hillsborough" },
    { city: "Nashua", countyFips: "011", countyName: "Hillsborough" },
    { city: "Concord", countyFips: "017", countyName: "Merrimack" },
    { city: "Dover", countyFips: "015", countyName: "Strafford" },
    { city: "Rochester", countyFips: "015", countyName: "Strafford" },
  ],
  RI: [
    { city: "Providence", countyFips: "007", countyName: "Providence" },
    { city: "Cranston", countyFips: "007", countyName: "Providence" },
    { city: "Warwick", countyFips: "003", countyName: "Kent" },
    { city: "Pawtucket", countyFips: "007", countyName: "Providence" },
    { city: "East Providence", countyFips: "007", countyName: "Providence" },
    { city: "Woonsocket", countyFips: "007", countyName: "Providence" },
  ],
  DE: [
    { city: "Wilmington", countyFips: "003", countyName: "New Castle" },
    { city: "Dover", countyFips: "001", countyName: "Kent" },
    { city: "Newark", countyFips: "003", countyName: "New Castle" },
    { city: "Middletown", countyFips: "003", countyName: "New Castle" },
  ],
  VT: [
    { city: "Burlington", countyFips: "007", countyName: "Chittenden" },
    { city: "South Burlington", countyFips: "007", countyName: "Chittenden" },
    { city: "Rutland", countyFips: "021", countyName: "Rutland" },
    { city: "Barre", countyFips: "023", countyName: "Washington" },
    { city: "Montpelier", countyFips: "023", countyName: "Washington" },
  ],
  WY: [
    { city: "Cheyenne", countyFips: "021", countyName: "Laramie" },
    { city: "Casper", countyFips: "025", countyName: "Natrona" },
    { city: "Laramie", countyFips: "021", countyName: "Albany" },
    { city: "Gillette", countyFips: "005", countyName: "Campbell" },
    { city: "Rock Springs", countyFips: "037", countyName: "Sweetwater" },
  ],
};
