// RPLICE v2 — Replicable Contract
// Federal layer: 24 programs that apply in every state.
// Byte-identical across peers. Slugs are canonical dedup keys.

import type { BenefitProgram } from "./types";

export const FEDERAL_PROGRAMS: BenefitProgram[] = [
  { slug: "federal:medicaid", scope: "federal", area: "healthcare-access", programName: "Medicaid (state-administered)",
    eligibility: { incomeFPLmax: 138, citizenshipRules: "US citizen or qualified non-citizen", docsRequired: ["ID","Income proof","Residency proof"] },
    portalUrl: "https://www.medicaid.gov/about-us/contact-us/contact-your-state-questions", phone: "1-800-318-2596",
    applicationChannels: ["online","phone","in-person","paper"], renewalCadence: "annual", annualDollarValueEstimate: 8400 },
  { slug: "federal:chip", scope: "federal", area: "healthy-children-families", programName: "CHIP (Children's Health Insurance Program)",
    eligibility: { ageMax: 18, incomeFPLmax: 250, docsRequired: ["Child ID","Income proof"] },
    portalUrl: "https://www.insurekidsnow.gov/", phone: "1-877-543-7669",
    applicationChannels: ["online","phone","in-person"], renewalCadence: "annual", annualDollarValueEstimate: 4200 },
  { slug: "federal:medicare", scope: "federal", area: "healthcare-access", programName: "Medicare",
    eligibility: { ageMin: 65, specialRules: "Or under 65 with qualifying disability / ESRD" },
    portalUrl: "https://www.medicare.gov", phone: "1-800-633-4227",
    applicationChannels: ["online","phone","in-person"], renewalCadence: "continuous", annualDollarValueEstimate: 7200 },
  { slug: "federal:medicare-savings", scope: "federal", area: "healthy-aging", programName: "Medicare Savings Programs (QMB/SLMB/QI)",
    eligibility: { ageMin: 65, incomeFPLmax: 135 },
    portalUrl: "https://www.medicare.gov/basics/costs/help/medicare-savings-programs", phone: "1-800-633-4227",
    applicationChannels: ["phone","in-person","paper"], renewalCadence: "annual", annualDollarValueEstimate: 1700 },
  { slug: "federal:aca-marketplace", scope: "federal", area: "healthcare-access", programName: "ACA Marketplace",
    eligibility: { incomeFPLmax: 400 },
    portalUrl: "https://www.healthcare.gov", phone: "1-800-318-2596",
    applicationChannels: ["online","phone","in-person"], renewalCadence: "annual", annualDollarValueEstimate: 4800 },
  { slug: "federal:snap", scope: "federal", area: "food-nutrition", programName: "SNAP (Food Stamps)",
    eligibility: { incomeFPLmax: 130 },
    portalUrl: "https://www.fns.usda.gov/snap/state-directory", phone: "1-800-221-5689",
    applicationChannels: ["online","in-person","paper"], renewalCadence: "6mo", annualDollarValueEstimate: 2400 },
  { slug: "federal:wic", scope: "federal", area: "healthy-children-families", programName: "WIC (Women, Infants & Children)",
    eligibility: { pregnancyOrParent: true, ageMax: 5, incomeFPLmax: 185 },
    portalUrl: "https://www.fns.usda.gov/wic", phone: "1-800-942-3678",
    applicationChannels: ["in-person","phone"], renewalCadence: "6mo", annualDollarValueEstimate: 1800 },
  { slug: "federal:ssi", scope: "federal", area: "income-employment", programName: "SSI (Supplemental Security Income)",
    eligibility: { disabilityRequired: true, specialRules: "Age 65+ OR blind OR disabled, with very limited income/resources" },
    portalUrl: "https://www.ssa.gov/ssi", phone: "1-800-772-1213",
    applicationChannels: ["phone","in-person","online"], renewalCadence: "annual", annualDollarValueEstimate: 11000 },
  { slug: "federal:ssdi", scope: "federal", area: "income-employment", programName: "SSDI (Social Security Disability Insurance)",
    eligibility: { disabilityRequired: true, specialRules: "Work credits required" },
    portalUrl: "https://www.ssa.gov/disability", phone: "1-800-772-1213",
    applicationChannels: ["phone","in-person","online"], renewalCadence: "continuous", annualDollarValueEstimate: 18000 },
  { slug: "federal:tanf", scope: "federal", area: "income-employment", programName: "TANF (Temporary Assistance for Needy Families)",
    eligibility: { pregnancyOrParent: true, incomeFPLmax: 50 },
    portalUrl: "https://www.acf.hhs.gov/ofa/programs/tanf", phone: "211",
    applicationChannels: ["in-person","online","paper"], renewalCadence: "6mo", annualDollarValueEstimate: 3600 },
  { slug: "federal:head-start", scope: "federal", area: "healthy-children-families", programName: "Head Start / Early Head Start",
    eligibility: { ageMax: 5, incomeFPLmax: 130 },
    portalUrl: "https://eclkc.ohs.acf.hhs.gov/center-locator", phone: "1-866-763-6481",
    applicationChannels: ["in-person","phone"], renewalCadence: "annual", annualDollarValueEstimate: 9500 },
  { slug: "federal:liheap", scope: "federal", area: "housing", programName: "LIHEAP (Low Income Home Energy Assistance)",
    eligibility: { incomeFPLmax: 150 },
    portalUrl: "https://www.acf.hhs.gov/ocs/low-income-home-energy-assistance-program-liheap", phone: "1-866-674-6327",
    applicationChannels: ["online","in-person","paper"], renewalCadence: "annual", annualDollarValueEstimate: 600 },
  { slug: "federal:section8", scope: "federal", area: "housing", programName: "Section 8 Housing Choice Voucher",
    eligibility: { incomeFPLmax: 80, specialRules: "Waiting lists vary by locality" },
    portalUrl: "https://www.hud.gov/program_offices/public_indian_housing/pha/contacts", phone: "1-800-955-2232",
    applicationChannels: ["in-person","paper"], renewalCadence: "annual", annualDollarValueEstimate: 14000 },
  { slug: "federal:hud-vash", scope: "federal", area: "veterans", programName: "HUD-VASH (Veterans Housing Voucher)",
    eligibility: { veteranRequired: true, specialRules: "Homeless or at-risk veterans" },
    portalUrl: "https://www.va.gov/homeless/hud-vash.asp", phone: "1-877-424-3838",
    applicationChannels: ["in-person","phone"], renewalCadence: "annual", annualDollarValueEstimate: 14000 },
  { slug: "federal:va-healthcare", scope: "federal", area: "veterans", programName: "VA Health Care",
    eligibility: { veteranRequired: true },
    portalUrl: "https://www.va.gov/health-care/how-to-apply/", phone: "1-877-222-8387",
    applicationChannels: ["online","phone","in-person","paper"], renewalCadence: "continuous", annualDollarValueEstimate: 12000 },
  { slug: "federal:eitc", scope: "federal", area: "income-employment", programName: "EITC (Earned Income Tax Credit)",
    eligibility: { incomeFPLmax: 250 },
    portalUrl: "https://www.irs.gov/credits-deductions/individuals/earned-income-tax-credit-eitc", phone: "211",
    applicationChannels: ["online","paper","in-person"], renewalCadence: "annual", annualDollarValueEstimate: 3200 },
  { slug: "federal:ctc", scope: "federal", area: "healthy-children-families", programName: "Child Tax Credit",
    eligibility: { pregnancyOrParent: true },
    portalUrl: "https://www.irs.gov/credits-deductions/individuals/child-tax-credit", phone: "211",
    applicationChannels: ["online","paper"], renewalCadence: "annual", annualDollarValueEstimate: 2000 },
  { slug: "federal:988", scope: "federal", area: "mental-health", programName: "988 Suicide & Crisis Lifeline",
    eligibility: {}, portalUrl: "https://988lifeline.org", phone: "988",
    applicationChannels: ["phone"], renewalCadence: "as-needed", annualDollarValueEstimate: 0 },
  { slug: "federal:samhsa-locator", scope: "federal", area: "mental-health", programName: "SAMHSA Treatment Locator",
    eligibility: {}, portalUrl: "https://findtreatment.gov", phone: "1-800-662-4357",
    applicationChannels: ["online","phone"], renewalCadence: "as-needed", annualDollarValueEstimate: 0 },
  { slug: "federal:acl-eldercare", scope: "federal", area: "healthy-aging", programName: "Eldercare Locator",
    eligibility: { ageMin: 60 }, portalUrl: "https://eldercare.acl.gov", phone: "1-800-677-1116",
    applicationChannels: ["online","phone"], renewalCadence: "as-needed", annualDollarValueEstimate: 0 },
  { slug: "federal:ihs", scope: "federal", area: "healthcare-access", programName: "Indian Health Service",
    eligibility: { specialRules: "Members of federally recognized tribes" },
    portalUrl: "https://www.ihs.gov", phone: "1-301-443-3593",
    applicationChannels: ["in-person","phone"], renewalCadence: "continuous", annualDollarValueEstimate: 4500 },
  { slug: "federal:ryan-white", scope: "federal", area: "healthcare-access", programName: "Ryan White HIV/AIDS Program",
    eligibility: { specialRules: "HIV-positive, low-income" },
    portalUrl: "https://ryanwhite.hrsa.gov/hiv-care/services", phone: "1-800-448-0440",
    applicationChannels: ["in-person","phone"], renewalCadence: "annual", annualDollarValueEstimate: 8000 },
  { slug: "federal:lifeline", scope: "federal", area: "income-employment", programName: "Lifeline (Phone/Internet Subsidy)",
    eligibility: { incomeFPLmax: 135 }, portalUrl: "https://www.lifelinesupport.org", phone: "1-800-234-9473",
    applicationChannels: ["online","paper"], renewalCadence: "annual", annualDollarValueEstimate: 115 },
  { slug: "federal:legal-aid", scope: "federal", area: "legal-rights", programName: "Legal Services Corporation (find local legal aid)",
    eligibility: { incomeFPLmax: 125 }, portalUrl: "https://www.lsc.gov/about-lsc/what-legal-aid/find-legal-aid", phone: "211",
    applicationChannels: ["phone","in-person","online"], renewalCadence: "as-needed" },
  { slug: "federal:211", scope: "federal", area: "income-employment", programName: "211 Community Resource Line",
    eligibility: {}, portalUrl: "https://www.211.org", phone: "211",
    applicationChannels: ["phone","online"], renewalCadence: "as-needed" },
];
