/**
 * Navigation view over the route registry (Phase 3). Every nav reader —
 * focused sidebar, bottom tabs, /tools directory — reads this, never its own list.
 * The manifest is generated by scripts/generate-route-registry.ts and stale-checked in CI.
 */
import manifest from "./route-nav.generated.json";
import { OUTCOMES, OUTCOME_LABELS, AUDIENCES, AUDIENCE_LABELS } from "./route-registry.types";
import type { Outcome, Audience, Access } from "./route-registry.types";

export interface NavRoute {
  path: string;
  title: string;
  outcome: Outcome;
  audiences: Audience[];
  access: Access;
  description: string;
  downstream: string[];
}

export const NAV_ROUTES: readonly NavRoute[] = manifest as NavRoute[];
const BY_PATH = new Map(NAV_ROUTES.map(r => [r.path, r]));
export const navRoute = (path: string): NavRoute | undefined => BY_PATH.get(path);

export interface NavViewer { authenticated: boolean; staff: boolean; admin: boolean }

/** Access floor from the registry; readers may AND this with their own legacy predicate but never OR. */
export function canSeeRoute(route: NavRoute, viewer: NavViewer): boolean {
  if (route.access === "admin") return viewer.admin;
  if (route.access === "staff") return viewer.staff;
  if (route.access === "authenticated") return viewer.authenticated;
  return true;
}

/** Public outcomes shown to everyone; "operate" is the Operator door, shown only to staff/admin. */
export const PUBLIC_OUTCOMES = OUTCOMES.filter(o => o !== "operate") as Outcome[];
export const isValidOutcome = (v: string | null | undefined): v is Outcome => !!v && (OUTCOMES as readonly string[]).includes(v);
export const isValidAudience = (v: string | null | undefined): v is Audience => !!v && (AUDIENCES as readonly string[]).includes(v);

export interface NavFilter { viewer: NavViewer; audience?: Audience | null; outcome?: Outcome | null; query?: string }

/** Deterministic: access floor → outcome → audience (routes with no audience tag are audience-neutral and always kept) → text match. */
export function filterNavRoutes({ viewer, audience, outcome, query }: NavFilter): NavRoute[] {
  const q = (query ?? "").trim().toLowerCase();
  return NAV_ROUTES.filter(r => canSeeRoute(r, viewer))
    .filter(r => !outcome || r.outcome === outcome)
    .filter(r => !audience || r.audiences.length === 0 || r.audiences.includes(audience))
    .filter(r => !q || `${r.title} ${r.description} ${r.path}`.toLowerCase().includes(q));
}

export function groupByOutcome(routes: NavRoute[]): Array<{ outcome: Outcome; label: string; routes: NavRoute[] }> {
  return OUTCOMES.map(outcome => ({ outcome, label: OUTCOME_LABELS[outcome], routes: routes.filter(r => r.outcome === outcome) })).filter(g => g.routes.length > 0);
}

/** Where a tool sends people next, resolved to visible registry rows (the "connection" shown on /tools). */
export function connectionsFor(route: NavRoute, viewer: NavViewer): NavRoute[] {
  return route.downstream.map(p => BY_PATH.get(p)).filter((r): r is NavRoute => !!r && canSeeRoute(r, viewer));
}

export { OUTCOMES, OUTCOME_LABELS, AUDIENCES, AUDIENCE_LABELS };
export type { Outcome, Audience };
